### ISSUE TITLE
Processor is running in the highest frequency with schedutil - TT Scheduler

### ISSUE THREAD

**Issue by AliTajelsir** [CachyOS/linux-cachyos#1]
- I tried `linux-tt 5.15.3-4` and `linux-cacule 5.15.5-2` from AUR in Arch Linux, and in both the processor is running in the highest frequency with `schedutil` in `intel_pstate=passive`
- The same happens with `powersave` and `performance` in `intel_pstate=active`
- I'm using `tlp` to set the governor
- This doesn't happen with `ondemand`
- Strangely enough, if I change from `schedutil` to `ondemand` and back to `schedutil`, the scaling will work as expected, but it revert to the highest frequency after reboot.
- If it helps, this doesn't happen with `linux zen 5.15.4.zen1-1`
- Any information I can provide to help?
- Thanks in advance!

**Comment by ptr1337** [comment]
> * I tried `linux-tt 5.15.3-4` and `linux-cacule 5.15.5-2` from AUR in Arch Linux, and in both the processor is running in the highest frequency with `schedutil` in `intel_pstate=passive`
> 
>     * The same happens with `powersave` and `performance` in `intel_pstate=active`
> 
>     * I'm using `tlp` to set the governor
> 
>     * This doesn't happen with `ondemand`
> 
>     * Strangely enough, if I change from `schedutil` to `ondemand` and back to `schedutil`, the scaling will work as expected, but it revert to the highest frequency after reboot.
> 
>     * If it helps, this doesn't happen with `linux zen 5.15.4.zen1-1`
> 
>     * Any information I can provide to help?
> 
>     * Thanks in advance!

How about if you using as cmdline intel_pstate=hwp ? Could be also a problem form the tt-scheduler. 

Check if the cmdline and call back please.

**Comment by AliTajelsir** [comment]
- In `linux-tt` and `linux-cacule`: 
  - With `intel_pstate=hwp` or `intel_pstate=active` and `powersave` or `performance` the processor is running at the highest frequency without turbo (1.8 GHz in  i5-8250U)
  - With `intel_pstate=passive` highest frequency with turbo (3.4 GHz)
- In `linux-zen`:
- With `intel_pstate=passive` (400 MHz)

**Comment by ptr1337** [comment]
Its a issue from the scheduler when no_hz_full is used i think. 

See here:

https://github.com/hamadmarri/TT-CPU-Scheduler/issues/5

@hamadmarri

**Comment by ptr1337** [comment]
> * In `linux-tt` and `linux-cacule`:
>       
>       * With `intel_pstate=hwp` or `intel_pstate=active` and `powersave` or `performance` the processor is running at the highest frequency without turbo (1.8 GHz in  i5-8250U)
>       * With `intel_pstate=passive` highest frequency with turbo (3.4 GHz)
> 
>     * In `linux-zen`:
> 
>     * With `intel_pstate=passive` (400 MHz)

You can also try 'intel_pstate=enable'. If its not getting solved, we need to switch to tickless idle only mode instead of completly tickless.

**Comment by AliTajelsir** [comment]
- Tried `linux-tt 5.15.6-1`  but with the same result.
- Changing to `ondemand` and back to `schedutil` fixes the locked frequency. So I'm doing this abomination:
  ```
  [Unit]
  Description=Set ondemend governor then schedutil
  After=multi-user.target suspend.target hibernate.target hybrid-sleep.target suspend-then-hibernate.target
  
  [Service]
  Type=oneshot
  ExecStart=/usr/bin/sh -c 'sleep 20 && cpupower frequency-set -g ondemand && cpupower frequency-set -g schedutil'
  
  [Install]
  WantedBy=multi-user.target
  ```

**Comment by ptr1337** [comment]
That’s a known issue at the tt kernel. Maybe it’s gonna fixed soon.  

I thought first it’s the no_hz_full and changed this back to the old default   

Same with the preempt behavior. But if there are no changes for you, it can be changed back. 

Maybe do a issue at the tt scheduler repo.
