### ISSUE TITLE
Error while compiling kernel

### ISSUE THREAD

**Issue by RiverOnVenus** [CachyOS/linux-cachyos#10]
Hi, when I try to compile the `linux-cachyos-bore`, the following error occurs:

[https://paste.mozilla.org/e2RYLdt6](https://paste.mozilla.org/e2RYLdt6)

This seems to be related to the `lrng` patch.

Regards

**Comment by ptr1337** [comment]
Hey, 

Thanks for the report. Im running currently a compile and will fix it. Did you compiled with GCC or LLVM ? 

Regards

**Comment by ptr1337** [comment]
I did reverted the patch now. Seems to be a error from it. Sadly dont got the time to debug it. 

I did tested the new lrng with 5.17 which compiled without problems. Since 5.17 will be released tomorrow, 5.16 will be not that much relevant in the upcoming weeks. Thanks for the report.

**Comment by RiverOnVenus** [comment]
> Hey,
> 
> Thanks for the report. Im running currently a compile and will fix it. Did you compiled with GCC or LLVM ?
> 
> Regards

Sorry for the late reply.

Tried both GCC and LLVM, same error. And use the default PGKBUILD.

**Comment by RiverOnVenus** [comment]
> I did reverted the patch now. Seems to be a error from it. Sadly dont got the time to debug it.
> 
> I did tested the new lrng with 5.17 which compiled without problems. Since 5.17 will be released tomorrow, 5.16 will be not that much relevant in the upcoming weeks. Thanks for the report.


Thank you for maintaining these kernels and patches for a long time.

Regards
