### ISSUE TITLE
[NVIDIA DKMS] Build failing on the latest mainline.

### ISSUE THREAD

**Issue by lphd12** [CachyOS/linux-cachyos#103]
Hello guys, on the latest mainline (6.3), my NVIDIA module is failing to build, I don't know if I did something wrong in the .config file when doing the menu configuration (at each major version i redo the .config file, for compatibility purposes), but in the lastest stable (6.2.12) NVIDIA module builds fine, can you guys help me to track down this issue? The "make.log" file says:

-   CC [M]  /var/lib/dkms/nvidia/525.47.18/build/nvidia/nv.o
  CC [M]  /var/lib/dkms/nvidia/525.47.18/build/nvidia/nv-pci.o
  CC [M]  /var/lib/dkms/nvidia/525.47.18/build/nvidia/nv-dmabuf.o
  CC [M]  /var/lib/dkms/nvidia/525.47.18/build/nvidia/nv-nano-timer.o
clang: error: argument unused during compilation: '-MD' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '-MD' [-Werror,-Wunused-command-line-argument]
make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/nvidia/525.47.18/build/nvidia/nv.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/nvidia/525.47.18/build/nvidia/nv-pci.o] Error 1
clang: error: argument unused during compilation: '-MD' [-Werror,-Wunused-command-line-argument]
make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/nvidia/525.47.18/build/nvidia/nv-dmabuf.o] Error 1
clang: error: argument unused during compilation: '-MD' [-Werror,-Wunused-command-line-argument]
make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/nvidia/525.47.18/build/nvidia/nv-nano-timer.o] Error 1
make[1]: *** [Makefile:2026: /var/lib/dkms/nvidia/525.47.18/build] Error 2
make: *** [Makefile:82: modules] Error 2

Is this related to the mainline itself? (Currently building kernels since the 6.1.x with [llvm-bolt](https://github.com/ptr1337/llvm-bolt-scripts))

PS: I'm currently using the "Vulkan Dev" branch "525.47.18", before 530.x IBT is not supported, so I disabled it in the .config file.

**Comment by ptr1337** [comment]
Hi @lphd12 ,

We also build our Kernel as default with the above mentioned llvm-bolt-scripts from me. This is not the problem.
You can find the prebuilt toolchain here: https://mirror.cachyos.org/llvm-bolt-15.tar.zst
I think that the current vulkan developer driver has a problem with 6.2/6.3.
I use the 530.x drivers and nvidia-dkms is compiling correctly. Please check this out.

**Comment by ventureoo** [comment]
> 525.47.18

Use the lastest stable driver instaed of vulkan beta driver until it's updated to 530.xx.
