### ISSUE TITLE
Reasons to disable MGLRU in the default config

### ISSUE THREAD

**Issue by aruhier** [CachyOS/linux-cachyos#114]
Hi,
I was surprised to see that Multigen LRU is disabled in the default configs, but enabled by default in the PKGBUILD:
```
# CONFIG_LRU_GEN is not set
# CONFIG_LRU_GEN_ENABLED is not set
```

I use the `linux-cachyos` config on Gentoo, therefore I enabled MGLRU myself, but I was wondering if there was any specific reason for it to be disabled in the config file.

**Comment by aruhier** [comment]
Thanks for the answer!

The base archlinux config seems to enable MG_LRU now, that's why I was surprised: https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/blob/main/config#L1158

**Comment by ptr1337** [comment]
> Thanks for the answer!
> 
> The base archlinux config seems to enable MG_LRU now, that's why I was surprised: https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/blob/main/config#L1158

We have updated now the config, I think it should be more clear now :)
Actually we could try to do the config "based" on CachyOS things and make them disabled over the config vars.
Generally that should work already fine.
But for users, which are looking on the config it would be easier I guess.

**Comment by aruhier** [comment]
Thanks a lot!
