### ISSUE TITLE
Does it support Secure Boot or a I missing some packages on Fedora?

### ISSUE THREAD

**Issue by msmafra** [CachyOS/linux-cachyos#116]
Hello there!

I'm trying to enable Secure Boot on my system, but it's only working with Fedora's official kernel. With kernel 6.3.5-cbl1.0 it shows a message about shim and grub i386 that I have to take a picture since it doesn't show on logs.

**Comment by sirlucjan** [comment]
You need to use your own keys. Have a look at:

https://blog.nil.im/?7a

**Comment by ptr1337** [comment]
Oh. Now you got us.
I really don't know about fedora and how to sign the keys at them.

On archlinux you can do this via "sbctl" and a unified boot image.

**Comment by msmafra** [comment]
Mine I just signed is working with Fedora's kernel, nvidia drivers etc. These helped me: 
https://rpmfusion.org/Howto/Secure%20Boot
https://github.com/dell/dkms#secure-boot

@sirlucjan that one is for systemd-boot and have a scary number of steps.

**Comment by sirlucjan** [comment]
Unfortunately, I don't use Fedora and can't help. In fact, the only person who can help is @bieszczaders - he uses Fedora and owns the repo on COPR. I only have sources on Github and a docker to generate spec rpm :D
