### ISSUE TITLE
Question regarding latency nice support with EEVDF-BORE

### ISSUE THREAD

**Issue by sjclayton** [CachyOS/linux-cachyos#117]
I noticed in recent commits that it has been stated that latency nice is not supported anymore in kernels 6.3-onwards... But does this apply to the EEVDF-BORE hybrid as well or just the other schedulers? 

I was under the impression that latency nice was a part of EEVDF by default. If someone can please confirm this, or better inform me it would be much appreciated.

**Comment by ptr1337** [comment]
Yes, actually there was a former latency nice patch, which worked without EEVDF for a bunch of time, but it seems it does not get further updated and just carried together with EEVDF.

So, EEVDF-BORE does include latency nice, but this is the only one.
