### ISSUE TITLE
Nvidia GPU not working

### ISSUE THREAD

**Issue by sandunder** [CachyOS/linux-cachyos#118]
`
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
`
I\`ve already installed `nvidia-dkms` and using kernel `linux-cachyos`.
It can work while I am running the `linux` kernel.

**Comment by ventureoo** [comment]
It looks like missing DKMS modules. Please reinstall the nvidia-dkms package:

`sudo pacman -S nvidia-dkms`

**Comment by sandunder** [comment]
It works out.
Thanks :)
