### ISSUE TITLE
Genshin Impact can't load Astrolabe.dll with error "Invalid access to memory location."

### ISSUE THREAD

**Issue by teppyboy** [CachyOS/linux-cachyos#121]
When you try to run Genshin Impact through Wine using CachyOS kernels it'll fail with the error 998 aka "Invalid access to memory location.", but with `linux` kernel from Arch repo the game works fine, so I've tried to debug from Wine and what I can see is it originated from this call:
```
0140:Call ntdll.LdrLoadDll(0030a020 L"Z:\\run\\media\\tretrauit\\f12dc9d6-14f2-4977-9a1d-8c71c2dc2de3\\Games\\Genshin Impact;C:\\windows\\system32;C:\\windows\\system;C:\\windows;.;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem;C:\\windows\\system32\\WindowsPowershell\\v1.0;C:\\Program Files (x86)\\Microsoft VS"...,00000000,0021ed10,0021ecb8) ret=1740248a2
...
0140:Ret  ntdll.LdrLoadDll() retval=c0000005 ret=1740248a2
...
```
The return value c0000005 which is then called using `ntdll.RtlNtStatusToDosError(c0000005)` and it translates to `3e6` aka Invalid access to memory location

The full log for that call can be found here: https://paste.cachyos.org/p/5bd3409.log (I'm not posting the whole log since its 700MB)

Hope someone can find the cause and fix it in the kernel patches, thanks.

**Comment by teppyboy** [comment]
Somehow reinstalling the game fixed for me (repairing with AAGL doesn't work either), still very curious why the standard kernel can load the corrupted DLL and the CachyOS one can't.

**Comment by ptr1337** [comment]
> Somehow reinstalling the game fixed for me (repairing with AAGL doesn't work either), still very curious why the standard kernel can load the corrupted DLL and the CachyOS one can't.

That is really weird. Maybe there was/is a issue in the VMA lock.
Anyways, you could check out the RC kernel, which uses the offical per VMA lock. That one should be fine
