### ISSUE TITLE
linux-cachyos-headers should provide linux-headers

### ISSUE THREAD

**Issue by 264-bit** [CachyOS/linux-cachyos#122]
Please add `Provides = linux-headers` to linux-cachyos-headers (and other headers packages) so packages which depend on linux-headers will avoid pulling in linux-headers when not needed.  Thanks!

**Comment by ptr1337** [comment]
> Please add `Provides = linux-headers` to linux-cachyos-headers (and other headers packages) so packages which depend on linux-headers will avoid pulling in linux-headers when not needed. Thanks!

That is actually not a good idea, since it would conflict if people want to use the default archlinux kernel.

**Comment by vnepogodin** [comment]
you shouldn't use headers from one kernel for another, because the headers are different

**Comment by 264-bit** [comment]
I know that.  That is not what I'm asking for at all.

Some packages like `opensnitch-ebpf-module` depend on `linux-headers`, since they need a set of kernel headers to compile against.  They don't need the official archlinux kernel headers, just any kernel headers installed.  Since cachyos-linux-headers does not set Provides = linux-headers, this package is pulling in linux-headers even though it isn't needed.

Note that other unofficial kernel header packages have set provides = linux-headers.

**Comment by ptr1337** [comment]
> I know that. That is not what I'm asking for at all.
> 
> Some packages like `opensnitch-ebpf-module` depend on `linux-headers`, since they need a set of kernel headers to compile against. They don't need the official archlinux kernel headers, just the current kernel headers installed. Since cachyos-linux-headers does not set Provides = linux-headers, this package is pulling in linux-headers even though it isn't needed.
> 
> Note that other unofficial kernel header packages have set provides = linux-headers.

Because they are build against the "linux-headers" from arch. You can use the dkms module and then it works fine.
Even if we add, provides linux-headers, the module wont load, because its in the wrong path installed.

Just use dkms or modify the PKGBUILD. We cant cover all AUR package modules, so DKMS is the way.
