### ISSUE TITLE
6.4 BORE update breaks usability

### ISSUE THREAD

**Issue by LuisB79** [CachyOS/linux-cachyos#126]
I'm running a raid 0  on 2 optane drives with f2fs in a arch install with linux-cachyos-bore, and i have been since 6.3.2, every update was running fine until i upgraded to kernel 6.4.0-1, /sysroot wont mount, i am not sure what is the error, i am unable to dump the error but i am able to upload pictures. While building i do not see any errors apparent, and mkinitcpio builds just fine

![20230627_203034](https://github.com/CachyOS/linux-cachyos/assets/95400651/85d078b9-6df7-4e20-9f37-e1358b15c85c)

![20230627_203036](https://github.com/CachyOS/linux-cachyos/assets/95400651/24e6a213-ceae-490f-88e4-fbd1c7c521f6)
![20230627_203058](https://github.com/CachyOS/linux-cachyos/assets/95400651/729d3351-7467-467d-86c7-33e00ca16fdd)

my mkinitcpio config file looks like this

> MODULES=(dm_mod raid0 f2fs)
> HOOKS=(systemd autodetect modconf keyboard sd-vconsole block mdadm_udev lvm2 filesystems fsck)
> COMPRESSION="zstd"
> COMPRESSION_OPTIONS=(-2)

i used this options to manage to see the problem in the .conf file for systemd boot
`options root=/dev/volgrp1/u03pool rw systemd.journald.forward_to_console=1 console=tty1 pause_on_oops=20`

i haven't found help on google or the arch forums, and i am able to boot just fine with arch linux 6.3.9

**Comment by LuisB79** [comment]
Debugging the issue it may be something related to lz4_decompress

**Comment by LuisB79** [comment]
Since it cant load the compressed module, that should be the reason it cant mount sysroot

**Comment by ptr1337** [comment]
Hi,

Actually someone else reported a equal issue. It seems this a upstream f2fs/raid issue from 6.4 (stable)
Could you check if following kernel has this issue also?
https://archlinux.org/packages/core-testing/x86_64/linux/

**Comment by sirlucjan** [comment]
@ptr1337 He is our user from Discord.

**Comment by LuisB79** [comment]
> 

arch 6.4 works just fine

**Comment by LuisB79** [comment]
The problem was related to the ALHP repo instead of using cachyos repo
