### ISSUE TITLE
linux-cachyos-bmq 5.17.4-1(db499cb) fails to compile with CONFIG_SCHED_ALT not set in config file

### ISSUE THREAD

**Issue by kskeigrshi** [CachyOS/linux-cachyos#13]
https://github.com/zen-kernel/zen-kernel/issues/277

This issue describes exactly the same problem and the solution also applies to here. I changed `#CONFIG_SCHED_ALT is not set` to `CONFIG_SCHED_ALT=y` in `config`and it compiled successfully. Please apply the corresponding fixes shown in the issue I mentioned above in the kernel patches.

https://github.com/zen-kernel/zen-kernel/commit/e1d4c120ca78d52c468b3935063d328c341416fa
https://github.com/zen-kernel/zen-kernel/commit/088047a81e4c38bfe79c005768976dae45ae960d

**Comment by ptr1337** [comment]
Hey! 

Thanks for your report! I did already pushed the new patch which fixes this issue.
Will push the fixed PKGBUILD in some minutes.

**Comment by ptr1337** [comment]
Fixed with https://github.com/CachyOS/linux-cachyos/commit/de7d8ef5a534a923a7278e32a89a114a431ffba5

Actually It should have `CONFIG_SCHED_ALT=y` enabled since the scripts in the PKGBUILD should enable that config variable, weird behavior. 
Thank you.

**Comment by kskeigrshi** [comment]
Somehow after that "fix" the BMQ and PDS variant kernels fail to use the alternative schedulers and fallback to CFS. Maybe it's only on my machine, but something tells me it's related to this problem. I hope I am wrong.

**Comment by ptr1337** [comment]
Hey @kskeigrshi ,

No its was a issue from my site. I did forget to add to enable SCHED_ALT with the other patch. Also I did overworked the PKGBUILD in general a bit and did added some more customize options, 

Thanks for the report. 

Fixed with https://github.com/CachyOS/linux-cachyos/commit/cef9370dc2464944f6d475efa5aae7e0a14ecb55
