### ISSUE TITLE
How to avoid the usage of ntfs3

### ISSUE THREAD

**Issue by lavilao** [CachyOS/linux-cachyos#134]
Hi guys I am using the cachyos kernel version 6.4.1, does anyone knows how to avoid it uses the ntfs3 driver when mounting a drive (with ntfs of course) on nautilus? The reason is very simple, that driver has corrupted my filesystem twice (the last time was on version 6.3.1)and had to go to windows to fix it so I would rather use the older ntfs-3g fuse driver. Does anyone knows how to do it? Thanks in advice.

**Comment by sirlucjan** [comment]
To disable the kernel module ntfs3, edit the file blacklist.conf inside /etc/modprobe.d/ and insert blacklist ntfs3 at the end of this file. If you don't have such a file create one or see if you don't have such a list in your etc/modprobe.d/modprobe.conf file

**Comment by lavilao** [comment]
it works! me and my files thank you.

**Comment by sirlucjan** [comment]
You're welcome!
