### ISSUE TITLE
Add tsc directsync support to cure tsc unreliabilty on numerous Lenovo laptops, please :)

### ISSUE THREAD

**Issue by mrwiwi** [CachyOS/linux-cachyos#143]
Hi guys, great  work on everthing, cachyos is amazing, using it on a Legion 5 and it's almost perfect !

Almost because of broken Lenovo bios, but thnaks to some users there are some kernel patches that can be done to "cure" an unstable tsc clocksource : https://forums.lenovo.com/t5/Other-Linux-Discussions/TSC-clocksource-not-work/m-p/5126977?page=4

The laptop is condamned to use HPET without it (even with tsc=reliable and hpet=disable and all other combinaisons), which hold back the general performance (gaming in mind according to users on reddit).

here is a dmesg log form my system without patchset : 

`
[    0.000000] tsc: Fast TSC calibration using PIT
[    0.000000] tsc: Detected 3293.733 MHz processor
[    0.038718] Kernel command line: initrd=\intel-ucode.img initrd=\amd-ucode.img initrd=\initramfs-linux-cachyos.img root=UUID=4060cd47-1452-44cf-af66-02d1d81aeb25 rw rootflags=subvol=/@ cryptdevice=UUID=a709e9c8-e40e-4d46-bb92-82a91c36229e:luks-a709e9c8-e40e-4d46-bb92-82a91c36229e zswap.enabled=0 nowatchdog clocksource=tsc tsc=directsync nvidia-drm.modeset=1 vfio_iommu_type1.allow_unsafe_interrupts=1 iommu=pt
[    0.102721] clocksource: tsc-early: mask: 0xffffffffffffffff max_cycles: 0x2f7a2c5998f, max_idle_ns: 440795303739 ns
[    0.228723] tsc: Marking TSC unstable due to check_tsc_sync_source failed
.....
[    0.092699] clocksource: hpet: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 133484873504 ns
[    0.102721] clocksource: tsc-early: mask: 0xffffffffffffffff max_cycles: 0x2f7a2c5998f, max_idle_ns: 440795303739 ns
[    0.236925] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 3822520892550000 ns
[    0.301770] clocksource: Switched to clocksource hpet
[    0.307587] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
`

Patches can be found [here](https://git.uplinklabs.net/steven/ec2-packages) (the TSC ones in linux-zen folder) to add an tsc=directsync option to boot parameters to fix that (tsc can recalibrate itself and become reliable again), i can't find for now how to implement them myself, if not i would be pull requesting now :) Can you please add them to the kernel ? A lot of us could benefit from it.

Thanks a lot again for all your time and work !

**Comment by ptr1337** [comment]
Hey @mrwiwi ,

Generally I would be open for this, but reading the comments of the patch does not seems to be a good patch to use:
https://lore.kernel.org/all/84f991e0-4d14-7ea9-7553-9f688df9cd49@collabora.com/T/#m156fc8ddb3f69691fefedb7bba49a280fe97938e

So, we need to see if this also affects other hardware, when the directsync option is not used.
We will check that in the team and come back to you. :)

**Comment by mrwiwi** [comment]
I thank you a lot for your considerations !

**Comment by etircopyh** [comment]
> So, we need to see if this also affects other hardware, when the directsync option is not used.
We will check that in the team and come back to you. :)

So, were there some complication or obstacles as to why these patches can't make it? It's rather a common issue with lenovo laptops and it would be helpful for a lot of people to have this option. Isn't it among Cachyos' advantages, to have options?
