### ISSUE TITLE
[Request] Dinit support

### ISSUE THREAD

**Issue by GrabbenD** [CachyOS/linux-cachyos#145]
Dinit is astonishingly fast on both modern and ancient hardware. The difference is day and night.

To try it out I've installed Artix and added CachyOS repositories but it seems like CachyOS tries to bring SystemD back in even though it's not necessary:

```console
# pacman -Syu
:: Synchronizing package databases...
 cachyos-v3 is up to date
 cachyos-core-v3 is up to date
 cachyos-extra-v3 is up to date
 cachyos is up to date
 system is up to date
 world is up to date
 galaxy is up to date
:: Starting full system upgrade...
warning: curl: local (8.2.1-1) is newer than cachyos-core-v3 (8.2.0-2.1)
warning: grub: local (2:2.12rc1-1) is newer than cachyos-v3 (2:2.06.r499.ge67a551a4-1)
warning: pacman-contrib: local (1.9.1-1) is newer than cachyos-extra-v3 (1.9.0-1.1)
resolving dependencies...
warning: cannot resolve "systemd-libs", a dependency of "dbus"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "dbus"
warning: cannot resolve "systemd-libs", a dependency of "device-mapper"
warning: cannot resolve "systemd-libs", a dependency of "util-linux"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "util-linux"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "p11-kit"
warning: cannot resolve "systemd-libs", a dependency of "procps-ng"
warning: cannot resolve "systemd-libs", a dependency of "dbus"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "dbus"
warning: cannot resolve "systemd-libs", a dependency of "dbus"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "dbus"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "p11-kit"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "p11-kit"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "pcsclite"
warning: cannot resolve "systemd", a dependency of "polkit"
warning: cannot resolve "systemd", a dependency of "polkit"
warning: cannot resolve "systemd-libs", a dependency of "procps-ng"
warning: cannot resolve "systemd-libs", a dependency of "util-linux"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "util-linux"
warning: cannot resolve "systemd-libs", a dependency of "dbus"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "dbus"
warning: cannot resolve "libsystemd.so=0-64", a dependency of "pcsclite"
warning: cannot resolve "systemd", a dependency of "polkit"
:: The following packages cannot be upgraded due to unresolvable dependencies:
      dbus  device-mapper  p11-kit  pcsclite  polkit  procps-ng  util-linux

:: Do you want to skip the above packages for this upgrade?
```

Is there any way to blacklist/ignore SystemD dependencies?

**Comment by ptr1337** [comment]
> Dinit is astonishingly fast on both modern and ancient hardware. The difference is day and night.
> 
> To try it out I've installed Artix and added CachyOS repositories but it seems like CachyOS tries to bring SystemD back in even though it's not necessary:
> 
> ```
> # pacman -Syu
> :: Synchronizing package databases...
>  cachyos-v3 is up to date
>  cachyos-core-v3 is up to date
>  cachyos-extra-v3 is up to date
>  cachyos is up to date
>  system is up to date
>  world is up to date
>  galaxy is up to date
> :: Starting full system upgrade...
> warning: curl: local (8.2.1-1) is newer than cachyos-core-v3 (8.2.0-2.1)
> warning: grub: local (2:2.12rc1-1) is newer than cachyos-v3 (2:2.06.r499.ge67a551a4-1)
> warning: pacman-contrib: local (1.9.1-1) is newer than cachyos-extra-v3 (1.9.0-1.1)
> resolving dependencies...
> warning: cannot resolve "systemd-libs", a dependency of "dbus"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "dbus"
> warning: cannot resolve "systemd-libs", a dependency of "device-mapper"
> warning: cannot resolve "systemd-libs", a dependency of "util-linux"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "util-linux"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "p11-kit"
> warning: cannot resolve "systemd-libs", a dependency of "procps-ng"
> warning: cannot resolve "systemd-libs", a dependency of "dbus"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "dbus"
> warning: cannot resolve "systemd-libs", a dependency of "dbus"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "dbus"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "p11-kit"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "p11-kit"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "pcsclite"
> warning: cannot resolve "systemd", a dependency of "polkit"
> warning: cannot resolve "systemd", a dependency of "polkit"
> warning: cannot resolve "systemd-libs", a dependency of "procps-ng"
> warning: cannot resolve "systemd-libs", a dependency of "util-linux"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "util-linux"
> warning: cannot resolve "systemd-libs", a dependency of "dbus"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "dbus"
> warning: cannot resolve "libsystemd.so=0-64", a dependency of "pcsclite"
> warning: cannot resolve "systemd", a dependency of "polkit"
> :: The following packages cannot be upgraded due to unresolvable dependencies:
>       dbus  device-mapper  p11-kit  pcsclite  polkit  procps-ng  util-linux
> 
> :: Do you want to skip the above packages for this upgrade?
> ```
> 
> Is there any way to blacklist/ignore SystemD dependencies?

We are recompiling the archlinux repositories, which mainly depends on packages on systemd and this also won't change.
You need to manually block packages from our repo, which do not fit to artix.

**Comment by GrabbenD** [comment]
Thanks for the quick response @ptr1337!
This makes sense and it's probably the best way forward.

Do you know any good way of blocking packages from a particular repository?
(I believe it should be enough to force `dbus  device-mapper  p11-kit  pcsclite  polkit  procps-ng  util-linux` to be used from Artix's repos instead of CachyOS).

**Comment by ptr1337** [comment]
Maybe try it with the IgnorePkg function in pacman and define the repository. 


Something like this:

IgnorePkg=cachyos-extra-v3/$pkgname

**Comment by GrabbenD** [comment]
Great find @ptr1337!

Maybe I've done something wrong?
I'm getting the exact same error message from above

I checked every package to get the right repository, e.g: 
```console
$ pacman -Ss ^dbus$
cachyos-core-v3/dbus 1.14.8-1.1 [installed: 1.14.8-1]
    Freedesktop.org message bus system
system/dbus 1.14.8-1 [installed]
    Freedesktop.org message bus system
```

Then I blacklisted these packages in `/etc/pacman.conf` like this
```
IgnorePkg = cachyos-core-v3/dbus cachyos-core-v3/device-mapper cachyos-core-v3/p11-kit cachyos-extra-v3/pcsclite cachyos-extra-v3/polkit cachyos-core-v3/procps-ng cachyos-core-v3/util-linux
```
