### ISSUE TITLE
linux-cachyos-pds

### ISSUE THREAD

**Issue by aloisiomarques** [CachyOS/linux-cachyos#147]
b2sum key is from the 6.4.7 kernel, even changing it to _minor = 8 shows an error in the key.

**Comment by ptr1337** [comment]
> b2sum key is from the 6.4.7 kernel, even changing it to _minor = 8 shows an error in the key.

We need to update linux-cachyos-pds, since the patchset does not work with 6.4.8.
We will update it on the weekend

**Comment by ptr1337** [comment]
https://github.com/CachyOS/linux-cachyos/commit/3447d67884c2670d1958781eee9e39250ab7c355

Fixed
