### ISSUE TITLE
[Request] BBRv3 is now available, interested in trying it out early?

### ISSUE THREAD

**Issue by wanlce** [CachyOS/linux-cachyos#148]
https://github.com/google/bbr/tree/v3
https://datatracker.ietf.org/meeting/117/materials/slides-117-ccwg-bbrv3-algorithm-bug-fixes-and-public-internet-deployment-00

**Comment by ptr1337** [comment]
https://github.com/CachyOS/linux-cachyos/commit/0593f78c1afca18aa85956b232098936884fc8ca


It's already used since 6.4.8 and enabled

**Comment by wanlce** [comment]
>



> [0593f78](https://github.com/CachyOS/linux-cachyos/commit/0593f78c1afca18aa85956b232098936884fc8ca)
> 
> It's already used since 6.4.8 and enabled

Amazing!  Great job!  Thanks！
I noticed that the README has not been updated  (
