### ISSUE TITLE
_use_llvm_lto=?

### ISSUE THREAD

**Issue by Lyapsus** [CachyOS/linux-cachyos#15]
Hello and thanks in advance for linux-cachyos!
Speaking about the problem, I constantly get
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/install.rs:1974:53

whatever I write next to "_use_llvm_lto=" in PKGBUILD trying to install linux-cachyos (and linux-cachyos-bore) from AUR.
I tried full, "full", 'full' (like scheduler is stated, in PKGBUILD code looks the same), y/n...

**Comment by ptr1337** [comment]
Hey, 

which llvm version are you running ? Maybe the llvm 13 version got some issues with full lto. 

Thin would work without problems, so I do provide them in the repo also and all are built fine. 

I’ll do let a run with full lto and llvm 13 when I’m at home 👍

**Comment by Lyapsus** [comment]
Oh didn't notice sorry.
Well, thin LTO didn't work out either with exactly the same error message, but the catch could be that I used LLVM 14.0.3-1 for that. Gonna try with standard 13.

**Comment by ptr1337** [comment]
Actually I pushed and build a 5.17.8 kernel with thinlto, full lto, and without lto. All with llvm and every built went fine. 

It seems something is broken in your toolchain ? 

>

**Comment by Lyapsus** [comment]
Hmm it always might be. How do I find out? At the rest of AUR compilations work just fine.

**Comment by ptr1337** [comment]
> Hmm it always might be. How do I find out? At the rest of AUR compilations work just fine.
Actually I mean every Kernel is provided in our repo's built with thinlto and llvm 13 successfully also. We are using for every built a chroot.

Try to built it in a chroot.

How did you built your llvm 14? Is everything correctly bootstrapped? 

I also have a bolted llvm here, you can try this also:
https://mirror.cachyos.org/llvm-bolt.tar.zst

Usage example:
`export PATH=/home/ptr1337/Documents/install/bin:${PATH}`
then check with:
`clang -v `your output

**Comment by ptr1337** [comment]
One thing which also seems odd to me:
Rust build error, makepkg is just bash shell. It's internal issue. Could be Paru, or another Rust written AUR helper

**Comment by Lyapsus** [comment]
> How did you built your llvm 14? Is everything correctly bootstrapped?
It was so called llvm+clang prebuilt package from https://www.archlinux.club/, I'll stick to standard 13 from now to avoid confusion

**Comment by Lyapsus** [comment]
> One thing which also seems odd to me: Rust build error, makepkg is just bash shell. It's internal issue. Could be Paru, or another Rust written AUR helper

Nice shot! Everything is just fine with pure makepkg so I should visit paru's issues, thanks a lot :)

**Comment by ptr1337** [comment]
Glad to hear!
