### ISSUE TITLE
6.4.9 fails to build under LLVM

### ISSUE THREAD

**Issue by sjclayton** [CachyOS/linux-cachyos#150]
Fails compile at link time, bunch of linker errors all referencing SRSO (did not save the errors)... seems to have to do with the recent config change

CONFIG_CPU_SRSO=y

Compiles fine under GCC.

**Comment by sirlucjan** [comment]
Could you try now? I've disabled it for thin/full LTO.

https://github.com/CachyOS/linux-cachyos/commit/e1aa47c963fe31debb28aca23f8d39f01e6c9c30

**Comment by sirlucjan** [comment]
This entry will be there as long as it is needed - if the upstream fixes the problem, then we will permanently remove it as unnecessary. If the problem is solved, can you close the issue?
