### ISSUE TITLE
Bcachefs patchset breaks the build for both kernel with default config and ZFS kmod

### ISSUE THREAD

**Issue by extSunset** [CachyOS/linux-cachyos#152]
The bcachefs patch causes problems when building the IVPU kernel module. By default, `CONFIG_DRM_ACCEL_IVPU` is set to `m` for kernel version 6.4+ (tested on 6.4.{9,10}). Build errors:
```
drivers/accel/ivpu/ivpu_gem.c:200:17: error: expected identifier
        ret = bo->ops->alloc_pages(bo);
                       ^
./include/linux/gfp.h:288:28: note: expanded from macro 'alloc_pages'
#define alloc_pages(...)                        alloc_hooks(alloc_pages_noprof(VA_ARGS))
                                                ^
./include/linux/alloc_tag.h:150:37: note: expanded from macro 'alloc_hooks'
#define alloc_hooks(_do_alloc)                                          \
                                                                        ^
drivers/accel/ivpu/ivpu_gem.c:200:17: error: expected expression 
./include/linux/gfp.h:288:28: note: expanded from macro 'alloc_pages'
#define alloc_pages(...)                        alloc_hooks(alloc_pages_noprof(VA_ARGS))
                                                ^
./include/linux/alloc_tag.h:151:2: note: expanded from macro 'alloc_hooks'
({                                                                      \
^
2 errors generated.
```

Also, the patchset prevents the ZFS kernel module from being built (tested on zfs-dkms 2.1.12 and 2.2.0-rc3, commit [f9a2d94](https://github.com/openzfs/zfs/commit/f9a2d94c957d0660ad1f4cfbb0a909eb8e6086df) via the internal linux-cachyos ZFS package). Build errors:
```
/var/lib/dkms/zfs-2.2.0/rc3/build/module/os/linux/spl/spl-kmem-cache.c:1252:10: error: call to undeclared function 'kmem_cache_alloc'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                        obj = kmem_cache_alloc(slc, kmem_flags_convert(flags));
                              ^
/var/lib/dkms/zfs-2.2.0/rc3/build/module/os/linux/spl/spl-kmem-cache.c:1252:8: error: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
                        obj = kmem_cache_alloc(slc, kmem_flags_convert(flags));
                              ^ ~~~~~~~~~~~~
```
Tested when building with LLVM 15.0.7 and 16.0.3.
The issue may also apply to the LTS version of the kernel.

**Comment by sirlucjan** [comment]
I think these errors are more eligible to be reported to bcachefs developers. Regarding the lack of compatibility of bcachefs with zfs, we are unable to resolve anything.

**Comment by sirlucjan** [comment]
Latest one currently.

**Comment by sirlucjan** [comment]
In a moment I will add an option that will prevent you from trying to build ZFS and bcachefs at the same time.

**Comment by sirlucjan** [comment]
@extSunset Could you check latest commits?

**Comment by sirlucjan** [comment]
I did as much as I was able to do - the rest of the work belongs to the developers.

**Comment by sirlucjan** [comment]
@extSunset 

Could you check if the error still occurs without applying this workaround? It has reportedly been resolved.

**Comment by sirlucjan** [comment]
I checked, it seems to be working.

**Comment by sirlucjan** [comment]
So I've reverted one workaround for bcachefs (related to config): https://github.com/CachyOS/linux-cachyos/commit/a4638a241efa02c5fbb31e53b212652794051b93

**Comment by sirlucjan** [comment]
Is everything working properly now? Can we remove workaround?

**Comment by sirlucjan** [comment]
@ptr1337  so why not remove the workaround?
