### ISSUE TITLE
Module dm_mod not found

### ISSUE THREAD

**Issue by GrabbenD** [CachyOS/linux-cachyos#153]
I'm trying to use cachyos lto kernel on bare metal this way:
```console
$ pacman -S linux-cachyos-lto
$ install -Dm0644 /usr/lib/modules/6.4.10-2-cachyos-lto/vmlinuz /boot/vmlinuz-linux
```

However, while booting the computer it hangs on:
```console
dracut-pre-udev[493]: modprobe: FATAL: Module dm_mod not found in directory /lib/modules/6.4.10-2-cachyos-lto
```

Path: `/lib/modules/6.4.10-2-cachyos-lto` exists and I've also tried starting the disk in Hyper-V (instead of baremetal) which gives me the same error.

Am I missing anything?

**Comment by GrabbenD** [comment]
My bad, I forgot to regenerate my initramfs modules (since I haven't installed Pacman hooks for dracut on this system yet https://wiki.archlinux.org/title/Dracut#Change_compression_program):
```console
mount /dev/sdb2 /mnt/root
mount /dev/sdb1 /mnt/root/boot
arch-chroot /mnt/root
dracut --force --no-hostonly-cmdline --no-hostonly /boot/initramfs-linux.img --kver 6.4.10-2-cachyos-lto
```

All good now!

**Comment by sirlucjan** [comment]
You can use our dracut with hooks: https://github.com/CachyOS/CachyOS-PKGBUILDS/tree/master/dracut

**Comment by GrabbenD** [comment]
@sirlucjan Thanks for sharing!

Is that package not available in CachyOS's repository? I'm only seeing dracut from Arch repos:
```
# pacman -Ss dracut
extra/dracut 059-3 [installed]
    An event driven initramfs infrastructure
```

**Comment by sirlucjan** [comment]
You need to compile it

**Comment by sirlucjan** [comment]
@GrabbenD I've updated sources on our GITHUB (I've added patch for systemd 254).

**Comment by GrabbenD** [comment]
Neat, thanks a ton @sirlucjan !
