### ISSUE TITLE
Dota2 stuck on loading screen

### ISSUE THREAD

**Issue by dragove** [CachyOS/linux-cachyos#154]
When launching dota2, it runs but stuck on the loading screen like below:

![Screenshot_20230813_201838](https://github.com/CachyOS/linux-cachyos/assets/24190403/1149b518-3020-4388-b876-fcec3bd02deb)

If I switch to another kernel (linux-zen in my case), it runs fine.

I've tried it with -vulkan -gl, with intel integrated graphics card and nvidia. They behave the same. Thus I think it is a kernel bug.  I don't konw how to correctly collect logs, I appreciate anyone can tell me what should I do to collect logs.

**Comment by ptr1337** [comment]
> When launching dota2, it runs but stuck on the loading screen like below:
> 
> ![Screenshot_20230813_201838](https://user-images.githubusercontent.com/24190403/260302278-1149b518-3020-4388-b876-fcec3bd02deb.png)
> 
> If I switch to another kernel (linux-zen in my case), it runs fine.
> 
> I've tried it with -vulkan -gl, with intel integrated graphics card and nvidia. They behave the same. Thus I think it is a kernel bug. I don't konw how to correctly collect logs, I appreciate anyone can tell me what should I do to collect logs.

Can you update to the latest kernel (6.4.10-2 or 6.4.10-3 in our repo)?
I also just installed DOTA 2 and check it out.

**Comment by ptr1337** [comment]
![image](https://github.com/CachyOS/linux-cachyos/assets/70081076/d31f4e61-d0ac-460d-a2da-fdc86c03eefb)
I just tested it and linux-cachyos 6.4.10-3 and it works fine.
Hardware:
1070 Ti
5950X

Since you run integrated graphics, do you use prime-run or something equal?
See here:
https://wiki.cachyos.org/en/notebooks

**Comment by dragove** [comment]
Oh, my bad, I'm using `cachyos-linux-lts` since linux 6.4 is not running well on my device (Sometimes I get audio distortion when using linux 6.4 and it seems that bug will be fixed in linux 6.5 but not in a fix version of 6.4 source: https://bbs.archlinux.org/viewtopic.php?id=287068 )

I'll try linux-cachyos 6.4 later and see if it only happens in lts kernel.

**Comment by ptr1337** [comment]
> Oh, my bad, I'm using `cachyos-linux-lts` since linux 6.4 is not running well on my device (Sometimes I get audio distortion when using linux 6.4 and it seems that bug will be fixed in linux 6.5 but not in a fix version of 6.4 source: https://bbs.archlinux.org/viewtopic.php?id=287068 )
> 
> I tested it with `prime-run` and got the same result.
> 
> I'll try linux-cachyos 6.4 later and see if it only happens in lts kernel.
> 
> Updated: I've tested with linux-cahcyos 6.4 and it runs well. Maybe it is a problem with the newest nvidia driver since normally we use `nvidia-lts` package for lts kernel. But In my case, I'm using `nvidia-open-dkms` with `linux-cachyos-lts`

Hi,

I have updated the patches for the 6.1 Kernel and it is currently compiling. I have reduced the problematic patches a bit and it should be now cleaner.
Feel free to bring feedback as soon it is up.

**Comment by dragove** [comment]
Now everything gets working. Thanks for your outstanding works!
