### ISSUE TITLE
Internet speed dropped and cpu load increased a lot when using linux-cachyos-bore

### ISSUE THREAD

**Issue by Boria138** [CachyOS/linux-cachyos#161]
This is when using cachyos bore 

![IMG_20230826_141724_083.png](https://github.com/CachyOS/linux-cachyos/assets/36843745/e43c2c07-54df-4220-a5bf-d5b156286514)

This is when using linux-zen

![IMG_20230826_141728_764.png](https://github.com/CachyOS/linux-cachyos/assets/36843745/653881b3-a8a9-469d-90db-ea5a233d8b7b)

**Comment by NextWork123** [comment]
Hello, please check if you are experiencing any issues with "bpftune." It is responsible for optimizing the internet connection, and that might be the cause of the problem.

To stop it, you can execute the following command: `sudo systemctl stop bpftune`

After that, please let us know if the issue persists.

**Comment by Boria138** [comment]
> Hello, please check if you are experiencing any issues with "bpftune." It is responsible for optimizing the internet connection, and that might be the cause of the problem.
> 
> To stop it, you can execute the following command: `sudo systemctl stop bpftune`
> 
> After that, please let us know if the issue persists.

I'm not using bpf-tune only cachyos-settings

**Comment by NextWork123** [comment]
Mh, okay. I had the same issue as you, and I disabled 'bpftune,' which fixed it.

**Comment by ventureoo** [comment]
> > Hello, please check if you are experiencing any issues with "bpftune." It is responsible for optimizing the internet connection, and that might be the cause of the problem.
> > To stop it, you can execute the following command: `sudo systemctl stop bpftune`
> > After that, please let us know if the issue persists.
> 
> I'm not using bpf-tune only cachyos-settings

bpftune is hard depedency for cachyos-settings. So I suggest you check to see if it's installed.

**Comment by Boria138** [comment]
> > > Hello, please check if you are experiencing any issues with "bpftune." It is responsible for optimizing the internet connection, and that might be the cause of the problem.
> > > To stop it, you can execute the following command: `sudo systemctl stop bpftune`
> > > After that, please let us know if the issue persists.
> > 
> > I'm not using bpf-tune only cachyos-settings
> 
> bpftune is hard depedency for cachyos-settings. So I suggest you check to see if it's installed.

I don't have the bpftune service

**Comment by ventureoo** [comment]
FWIW there may be a correlation between a drop in internet speed and CPU load. This may be a issue related with BBR3. Try to set ``net.ipv4.tcp_congestion_control = cubic``.

**Comment by Boria138** [comment]
> FWIW there may be a correlation between a drop in internet speed and CPU load. This may be a issue related with BBR3. Try to set ``net.ipv4.tcp_congestion_control = reno``.

Looks like it's really a bug bbr internet is back to normal and the CPU load is higher than on linux-zen but it's not that bad anymore
![Снимок экрана от 2023-08-26 11-45-46.png](https://github.com/CachyOS/linux-cachyos/assets/36843745/883d85e2-693e-41fa-9a7d-5e870d1aff3a)

**Comment by Boria138** [comment]
In zen kernel the load on the cores is more even than cachyos and after a while it turned out that the internet is not very stable either

**Comment by Boria138** [comment]
After a day of using the kernel in the end although the graph of Internet speed I have returned to normal (I guess if bbr3 so badly affects the Internet is better to return to bbr2), but the load graph to normal has not returned the processor is not only loaded almost to the maximum even from the lowest load and the load itself is not even, that is, some cores can just idle, I wanted to still throw logs, but I do not know where to leave them that would attach a link

**Comment by ptr1337** [comment]
I can't reproduce this in several tests on several devices.
BBR3 was tested from us from several devices and servers. None of them showed any regression in any tests.

The cpu usage with bbr2 is for me equal. You could try to change to "fq_codel" instead of "fq"

**Comment by Boria138** [comment]
I mistakenly installed linux-cachyos-headers not for bore scheduler but for eevdf, I reinstalled everything in the correct order and the errors disappeared

**Comment by NextWork123** [comment]
In light of your recent update, we will proceed to close the mentioned issue. Should you have any further inquiries, concerns, or require future assistance, please feel free to get in touch with us.

Best Regards
NextWorks
