### ISSUE TITLE
Thumbnails generate really slowly.

### ISSUE THREAD

**Issue by kerimcem** [CachyOS/linux-cachyos#162]
It boots slow compared to other cores,gnome xfce,intel Pentium G3220,4gb ram.

**Comment by ventureoo** [comment]
Could you please provide more information? What file manager do you use? Are there any errors in system logs (journalctl)?

**Comment by ptr1337** [comment]
Is this still a issue?

**Comment by kerimcem** [comment]
no,it got better over time,thankyou.
