### ISSUE TITLE
6.5.0 - Load average peculiarities

### ISSUE THREAD

**Issue by sjclayton** [CachyOS/linux-cachyos#165]
I set NR_CPUS to 6 when building as I have a six core processor (w/ no SMT).... since kernel 6.5.0 my 1/5/15 minute load averages seem to start at 3.00 instead of 0.00 with nothing intensive running at all. 

When using the system it reacts as normal, and it appears when under load that the averages scale normally, but starting at 3.00 instead of 0.... I run a process the numbers jump up... like a what a 1.48 1 min load would normally be... but instead I see 4.48... and then when the load stops it drops back to 3.00 or roughly there abouts (always some small processes running)

Nothing else has changed with my config, except the 6.5.0 kernel update. I don't know if this is caused by one of the patches, or whether it's upstream. Thought I'd report it here to see if anyone else notices anything similar.

**Comment by sjclayton** [comment]
Just wanted to post an update -- I tried booting up with the 6.4.12 normal Arch kernel, and this issue is not present at all, also I tried booting with 6.4.12-cachyos (I run the base variant with EEVDF/BORE compiled w/LLVM) and everything is normal there too... 

I looked at the kernel bug tracker and there are no reports of anything similar to this as of yet. So I'm starting to wonder if it it's related to one of the patches CachyOS is applying.

**Comment by ptr1337** [comment]
Hi,

Could you please try a kernel directly out of our repository and check if this issue is present?
There is also in the testing repo at archlinux a 6.5 Kernel, which would be possible to test.

We currently do not patch anything, which should affect this. So I think this is an upstream kernel regression maybe (paired with eevdf).

**Comment by sjclayton** [comment]
@ptr1337 I just tried the linux-cachyos package from the repo, and same issue as when I compile it manually for my machine. 

So maybe a regression?? I wouldn't know how to report it properly, or what to explain it as...

**Comment by ptr1337** [comment]
> 

Do you see anything, which is using the power?
Maybe some kind of discard,scrub, fstrim, .. ?

The only way analyizing this, would be with "perf top" i think.
Please also check the 6.5 Kernel from the archlinux repository.

**Comment by ptr1337** [comment]
> @ptr1337 Nothing is running at all other than what normally runs when my system is sitting idle (I have btrfs scrub and fstrim only set to run at certain times) and discard runs on demand, which isn't constantly, I can post a screenshot of atop or htop... so you can see the usr / sys / idle %
> 
> I will try the 6.5 Arch kernel when I get a chance, if the problem isn't present there then it must have something to do with EEVDF and something that was changed between 6.4.12 and 6.5.0.

I don't think it is EEVDF, but you can install any non-EEVDF Kernel out of the repository to verify. (linux-cachyos-cfs for example).
There is just one commit, which got added to EEVDF between 6.4 and 6.5 from our side.
Please check following:
- Default 6.5.0 Arch Kernel (to verify if its a 6.5 issue or a CachyOS one)

If we know, if this is present at the default arch kernel or not, we can start bisecting at the CachyOS part.
The CachyOS part is on 6.5 very small. So, I don't think its the issue, but we will see.

**Comment by sjclayton** [comment]
No go, on the 6.5 Arch kernel.... So it looks like this has to be something upstream then... not CachyOS related...

Only thing is I don't know how to report this.... or what specifically to describe it as, also what section it would go under.

Maybe this is something you would know better about.

**Comment by tjumar** [comment]
I'm having the same issue, all 3 load avg were at 300 after a few hours of normal desktop usage.
It's happening on both cachyos and linux-tkg with bore+eevdf, it's not happening on cachyos & tkg with just bore, also doesn't happen on arch linux-zen.

I noticed something in dmesg that happens very early on boot only on my bore+eevdf tests:
On cachyos with bore+eevdf: `kernel: psi: inconsistent task state! task=1:swapper/0 cpu=0 psi_flags=4 clear=0 set=4`
On tkg: `kernel: psi: inconsistent task state! task=115:kworker/0:2 cpu=0 psi_flags=4 clear=0 set=4`

**Comment by ptr1337** [comment]
> I'm having the same issue, all 3 load avg were at 300 (never seen that high on my 5700x) after a few hours of normal desktop usage.
> 
> It's happening on both cachyos and linux-tkg with bore+eevdf, it's not happening on cachyos & tkg with just bore, also doesn't happen on arch linux-zen.
> 
> I noticed something in dmesg that happens very early on boot only on my bore+eevdf tests: On cachyos with bore+eevdf: `kernel: psi: inconsistent task state! task=1:swapper/0 cpu=0 psi_flags=4 clear=0 set=4` On tkg: `kernel: psi: inconsistent task state! task=115:kworker/0:2 cpu=0 psi_flags=4 clear=0 set=4`

Mhm. I can't reproduce this on my side.
But It could be from EEVDF according your description.

**Comment by ventureoo** [comment]
> > I'm having the same issue, all 3 load avg were at 300 (never seen that high on my 5700x) after a few hours of normal desktop usage.
> > It's happening on both cachyos and linux-tkg with bore+eevdf, it's not happening on cachyos & tkg with just bore, also doesn't happen on arch linux-zen.
> > I noticed something in dmesg that happens very early on boot only on my bore+eevdf tests: On cachyos with bore+eevdf: `kernel: psi: inconsistent task state! task=1:swapper/0 cpu=0 psi_flags=4 clear=0 set=4` On tkg: `kernel: psi: inconsistent task state! task=115:kworker/0:2 cpu=0 psi_flags=4 clear=0 set=4`
> 
> Mhm. I can't reproduce this on my side. But It could be from EEVDF according your description.

I'm leaning more towards the fact that it may be related to Intel's latest regressions in 6.5.

https://www.phoronix.com/review/linux65-intel-regression

Can I ask those in this thread what CPU you have?

**Comment by sjclayton** [comment]
> I'm having the same issue, all 3 load avg were at 300 (never seen that high on my 5700x) after a few hours of normal desktop usage.
> 
> It's happening on both cachyos and linux-tkg with bore+eevdf, it's not happening on cachyos & tkg with just bore, also doesn't happen on arch linux-zen.
> 
> I noticed something in dmesg that happens very early on boot only on my bore+eevdf tests: On cachyos with bore+eevdf: `kernel: psi: inconsistent task state! task=1:swapper/0 cpu=0 psi_flags=4 clear=0 set=4` On tkg: `kernel: psi: inconsistent task state! task=115:kworker/0:2 cpu=0 psi_flags=4 clear=0 set=4`

I take it you mean all 3 load avgs were at 3.00 not 300 after a few hours... correct?... I'm going to assume so, as 300 would be pretty impossible on a 5700x.

Also AMD here, still having the issue... haven't noticed anything in dmesg here though,  but for me it happens on the plain Arch kernel as well without BORE or EEVDF, if it's 6.5.x the problem is there.

Hoping this can get figured out somehow soon, as it's mighty annoying when you have systems with the issue that you have remote monitoring setup for.

**Comment by tjumar** [comment]
Wish I had made a screenshot but it was 300 not 3.00, that's why it caught my eye. Both btop and htop reported the same. After boot it starts at something like 20 and keeps climbing.
I'll compile bore+eevdf again tomorrow and see if I can snap a screenshot after a while.

**Comment by sjclayton** [comment]
@tjumar Does your system otherwise seem like it's running fine though.... or is it slow / laggy when this is happening?

My system is completely normal other than the numbers being wrong.

**Comment by tjumar** [comment]
I was mostly on desktop browsing, but in the hour game time I got in yesterday I didn't notice any slowdowns.

**Comment by sjclayton** [comment]
Seems it may have something to do with this...

[Possible bug report: kernel 6.5.0/6.5.1 high load when CIFS share is mounted (cifsd-cfid-laundromat in"D" state)](https://www.uwsg.indiana.edu/hypermail/linux/kernel/2309.2/01931.html)

I have 2 SMB/CIFS shares mounted on my main system at boot, and I tried un-mounting them and the problem disappears, as soon as I remount them the falsely reported load avg's return.

**Comment by sjclayton** [comment]
I'm going to close this as I don't think there is reason to keep it open now, as it's most likely not a CachyOS issue.
