### ISSUE TITLE
6.4.x and 6.5.x Lenovo Legion Linux (LLL) not working properly

### ISSUE THREAD

**Issue by msmafra** [CachyOS/linux-cachyos#168]
Hello there!

Since 6.4.x and now with 6.5.x kernels, the LLL modules by from [johnfanv2/LenovoLegionLinux](https://github.com/johnfanv2/LenovoLegionLinux), specifically the Performance mode changing is not working.
This has an integration with Gnome's Energy Mode (power-profiles-daemon.service), where, when you change via Gnome's controls or via the keyboard shortcut (on my case Fn + Q) it changes between the 3 available power/energy modes and sets the colour of the the laptop's power button LED to indicate which mode you're in.

When I clone and install from the git repository it works as soon as a restart power-profiles-daemon.service.

**Comment by ptr1337** [comment]
Hi @msmafra 

Sorry, I did not track his releases, but I have updated it right now here:
https://github.com/CachyOS/linux/compare/1cbdd7735660...3a26c8199cba

With 6.5.3 this will be included. Please check as soon it is released.

**Comment by ptr1337** [comment]
> Thank you kindly.

6.5.3 is up. Can you please test again?

**Comment by msmafra** [comment]
It's working! Thank you kindly.
I think worked with  6.5.3-cbe1.0 too, not just 6.5.3-cbe2.0
