### ISSUE TITLE
AMD HDR patchset

### ISSUE THREAD

**Issue by akhilbalaji94** [CachyOS/linux-cachyos#170]
Will the AMD HDR patchset removed in 6.2 https://github.com/CachyOS/linux-cachyos/commit/3178762151dd73e346a3decb821840d90dd64bf4 be added back?

**Comment by ptr1337** [comment]
> Will the AMD HDR patchset removed in 6.2 [3178762](https://github.com/CachyOS/linux-cachyos/commit/3178762151dd73e346a3decb821840d90dd64bf4) be added back?

The AMD HDR Patchset is already included in 6.5.
See: https://github.com/CachyOS/kernel-patches/blob/master/6.5/0001-amd-hdr.patch
