### ISSUE TITLE
Files did not pass the validity check

### ISSUE THREAD

**Issue by nutta-git** [CachyOS/linux-cachyos#172]
Hi, both [linux](https://aur.archlinux.org/packages/linux-cachyos) and [header](https://aur.archlinux.org/packages/linux-cachyos-headers) fails to pass the validity check. 

`Aur (2)                    Old Version  New Version  Make Only
aur/linux-cachyos          6.5.3-1      6.5.4-1      No
aur/linux-cachyos-headers  6.5.3-1      6.5.4-1      No

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: linux-cachyos 6.5.4-1 (Tue 19 Sep 2023 10:29:41 AM EDT)
==> Retrieving sources...
  -> Found linux-6.5.4.tar.xz
  -> Found config
  -> Found auto-cpu-optimization.sh
  -> Found 0001-cachyos-base-all.patch
  -> Found 0001-EEVDF-cachy.patch
  -> Found 0001-bore-eevdf.patch
==> Validating source files with b2sums...
    linux-6.5.4.tar.xz ... Passed
    config ... Passed
    auto-cpu-optimization.sh ... Passed
    0001-cachyos-base-all.patch ... FAILED
    0001-EEVDF-cachy.patch ... FAILED
    0001-bore-eevdf.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'linux-cachyos-6.5.4-1 (linux-cachyos linux-cachyos-headers)': 
error: packages failed to build: linux-cachyos-6.5.4-1 (linux-cachyos linux-cachyos-headers)
`

**Comment by ptr1337** [comment]
> Hi, both [linux](https://aur.archlinux.org/packages/linux-cachyos) and [header](https://aur.archlinux.org/packages/linux-cachyos-headers) fails to pass the validity check.
> 
> `Aur (2) Old Version New Version Make Only aur/linux-cachyos 6.5.3-1 6.5.4-1 No aur/linux-cachyos-headers 6.5.3-1 6.5.4-1 No
> 
> :: Proceed to review? [Y/n]: y
> 
> :: Downloading PKGBUILDs... PKGBUILDs up to date nothing new to review fetching devel info... ==> Making package: linux-cachyos 6.5.4-1 (Tue 19 Sep 2023 10:29:41 AM EDT) ==> Retrieving sources... -> Found linux-6.5.4.tar.xz -> Found config -> Found auto-cpu-optimization.sh -> Found 0001-cachyos-base-all.patch -> Found 0001-EEVDF-cachy.patch -> Found 0001-bore-eevdf.patch ==> Validating source files with b2sums... linux-6.5.4.tar.xz ... Passed config ... Passed auto-cpu-optimization.sh ... Passed 0001-cachyos-base-all.patch ... FAILED 0001-EEVDF-cachy.patch ... FAILED 0001-bore-eevdf.patch ... FAILED ==> ERROR: One or more files did not pass the validity check! error: failed to download sources for 'linux-cachyos-6.5.4-1 (linux-cachyos linux-cachyos-headers)': error: packages failed to build: linux-cachyos-6.5.4-1 (linux-cachyos linux-cachyos-headers) `

Works for me:
```
time makepkg -s 
==> Making package: linux-cachyos 6.5.4-1 (Di 19 Sep 2023 16:45:51 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found linux-6.5.4.tar.xz
  -> Found config
  -> Found auto-cpu-optimization.sh
  -> Found 0001-cachyos-base-all.patch
  -> Found 0001-EEVDF-cachy.patch
  -> Found 0001-bore-eevdf.patch
==> Validating source files with b2sums...
    linux-6.5.4.tar.xz ... Passed
    config ... Passed
    auto-cpu-optimization.sh ... Passed
    0001-cachyos-base-all.patch ... Passed
    0001-EEVDF-cachy.patch ... Passed
    0001-bore-eevdf.patch ... Passed
```

I think paru does cache the patches. I don't suggest you to use paru to update the packages or remove the cache folder of paru before.

**Comment by nutta-git** [comment]
It was paru's cache, clearing it solved the issue.
Thank you
