### ISSUE TITLE
 Linux-Pollrate-Patch

### ISSUE THREAD

**Issue by dnodno** [CachyOS/linux-cachyos#175]
could you apply [Linux-Pollrate-Patch](https://github.com/KarsMulder/Linux-Pollrate-Patch) to the kernel by default? 

it exposes "usbcore.interrupt_interval_override" boot option for modifying the pollrate of usb devices such as Sony DS4 game controller

apologies for submitting this here but I'm not sure how to create a pull request and how i applied this patch probably isn't satisfactory

**Comment by ptr1337** [comment]
This patch wont be added from our side yet.
