### ISSUE TITLE
Does linux-cachyos kernel sign the out-of-tree kernel modules?

### ISSUE THREAD

**Issue by Bryan2333** [CachyOS/linux-cachyos#176]
I've enabled Secure Boot on my Arch system. I'm wondering if linux-cachyos will automatically sign the out-of-tree modules required by some VM software like VirtualBox.

**Comment by ptr1337** [comment]
> I've enabled Secure Boot on my Arch system. I'm wondering if linux-cachyos will automatically sign the out-of-tree modules required by some VM software like VirtualBox.

That depends if DKMS does that. Im not sure about secure boot.
linux-cachyos has nothing to do with that. If it works with the default linux, then it should work.

**Comment by Bryan2333** [comment]
OK, thanks for you replies.
