### ISSUE TITLE
_processor_opt option not working

### ISSUE THREAD

**Issue by Bryan2333** [CachyOS/linux-cachyos#177]
Before building the package, I ran these commands to disable auto optimization.

-  `sed -i 's/_processor_opt=${_processor_opt-}/_processor_opt=zen3/g' PKGBUILD` 
-  `sed -i 's/_use_auto_optimization=${_use_auto_optimization-y}/_use_auto_optimization=n/g' PKGBUILD`

But after I ran `makepkg -sc`, the `APPLYING AUTO-CPU-OPTIMIZATION` was still there.

**Comment by Bryan2333** [comment]
I also tried setting the environment variable by `export` command, but it did not work.

**Comment by ptr1337** [comment]
> Before building the package, I ran these commands to disable auto optimization.
> 
> * `sed -i 's/_processor_opt=${_processor_opt-}/_processor_opt=zen3/g' PKGBUILD`
> * `sed -i 's/_use_auto_optimization=${_use_auto_optimization-y}/_use_auto_optimization=n/g' PKGBUILD`
> 
> But after I ran `makepkg -sc`, the `APPLYING AUTO-CPU-OPTIMIZATION` was still there.

You should not set it to "n". "n" would also mean you will enable this.
You need to keep the variable empty, example:
`sed -i 's/_use_auto_optimization=${_use_auto_optimization-y}/_use_auto_optimization=/g' PKGBUILD
`

Also see here:
https://github.com/CachyOS/linux-cachyos/blob/master/script.sh#L2
