### ISSUE TITLE
Localmodconfig breaking usb ports

### ISSUE THREAD

**Issue by HyperChocolat** [CachyOS/linux-cachyos#179]
i know that is a config issue but since the 99% here are pc users will be nice to add a scripts/enable blablabla for auto enable the usb drivers for storage media, phones and things like that. sometimes even the usb keyboards drivers are deleted due this

**Comment by ptr1337** [comment]
This is a misconfiguration from your modprobed-db config. You need to fix this on your own.
Also see here:
https://wiki.archlinux.org/title/Modprobed-db
