### ISSUE TITLE
[FR] make optizimation selection more automatic

### ISSUE THREAD

**Issue by vp1981** [CachyOS/linux-cachyos#18]
Hello, this is small feature request. Would you mind to change the logic of optimization selection?

I propose the following patch for `PKGBUILD`:
```
--- PKGBUILD.orig       2022-06-09 09:13:11.196175022 +0800
+++ PKGBUILD    2022-06-09 09:14:19.951060678 +0800
@@ -224,11 +224,12 @@

     if [ -n "$_use_auto_optimization" ]; then
         "${srcdir}"/auto-cpu-optimization.sh
+       _use_optimization_select=
     fi

     if [ -n "$_use_optimization_select" ]; then
         source "${startdir}"/configure
-        cpu_arch
+        echo "${_use_optimization_select}" | cpu_arch
     fi

     ### Selecting the CPU scheduler
```

Rationale:
1. if I understand the purpose of the script [`auto-cpu-optimization.sh`](https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos-pds/auto-cpu-optimization.sh) correctly, setting `_use_auto_optimization` to `y` (or either non nil value) should effectively deselect `_use_optimization_select` (set it to nil).
2. (change in behavior) if one sets `_use_optimization_select`, one will be prompted to choose "arch" during the build, but it is more convenient to set the "arch" ID in PKGBUILD and pass it to `cpu_arch`, so as not to interrupt the "build process" run by `makepkg` (I didn't try other tools).

P.S. I build kernels (packages) for several "arch"s and use the `echo` approach to build packages without interruption (a kind of automation of package building).

**Comment by ptr1337** [comment]
Hey @vp1981 

Thanks for your suggestion. Actually im not sure where would be the profit of it? The auto-cpu-optimization.sh, is thought to autodetect the cpu march, but since I got some false positive with it I disabled it as default for now and enabled the manual selection.

I think I got what you want to tell with your message, I gonna take a watch.

If you want to PR it feel free!

**Comment by vp1981** [comment]
Hello @ptr1337 .

Let me explain my current workflow with package building. I use a small [wrapper script](https://git.sr.ht/~vp1981/scripts/tree/master/item/bin/buildpkg) for `makepkg` to semi-automatically build several packages, including kernel packages optimized for some architectures.

The kernel building process is started as follows
```
buildpkg -s 4
```
where `-s` stands for "stage 4"
```
stage4=(
  'linux-cachyos-pds/skylake'
  'linux-cachyos-pds/haswell'
  'linux-cachyos-pds/zen2'
  'linux-cachyos-pds/sandybridge'
  'linux-cachyos-pds/ivybridge'
  'linux-cachyos-pds/native'
  'linux-cachyos-pds/generic'
)
```
and it builds [`linux-cachyos-pds`](https://git.sr.ht/~vp1981/pkgbuild/tree/master/item/linux-cachyos-pds) packages (a small adaption of your `linux-cachyos-pds` from AUR) for the listed architectures on a build host.

The build host is one with the `native` kernel package, the other packages are for systems which I use or maintain. Here is an excerpt from `PKGBUILD` for "skylake":
```
...
## Apply Kernel automatic Optimization
_use_auto_optimization=

## Apply Kernel Optimization selecting
_use_optimization_select=48
...
_sfx=-skylake
if [ -n "$_use_llvm_lto" ]; then
  pkgbase=linux-cachyos-${_cpusched}-lto
else
  pkgbase=linux-cachyos-${_cpusched}${_sfx}
fi
...
if [ -n "$_use_auto_optimization" ]; then
    "${srcdir}"/auto-cpu-optimization.sh
  fi

  if [ -n "$_use_optimization_select" ]; then
    source "${startdir}"/configure
    echo "${_use_optimization_select}" | cpu_arch
  fi
...
```

The `_use_auto_optimization` is useless if I build a kernel package for a host other than the build host (I made such error in the past and found that kernel wouldn't boot :). So if `_use_optimization_select` is not just some non-nil value, but the correct number (for `configure` script), one may just run `makepkg` without prompt from the script.

If you think the approach is worthwhile, I'll make PR for the feature

**Comment by ptr1337** [comment]
Hey!

Now i understand it better. Actually we could merge that into it but I would say maybe as a extra function. Actually I will try to rework the auto optimization so that it does not report wrong marches.

Then we can replace the optimization select function with how you handle it for building.
I think using this for not building reason would be hard for users which does not know their "march number". But if the auto optimization runs correctly, then it should not hurt much.

Regards.

**Comment by ptr1337** [comment]
@vp1981 
Hey,

i did updated the auto optimization script and also you can set now at _processor_opt= your march which you want to compile.
https://github.com/CachyOS/linux-cachyos/commit/78c444c0fa3fd4ca17b82f1e67dc57f05cbe3129
Would help this in that problem?

Regards

**Comment by ptr1337** [comment]
Did fixed now also the auto optimization script so that all cpu marches will be correctly detected and used.

**Comment by vp1981** [comment]
Hello.
Thank you! I didn't test new `PKGBUILD` yet but it looks good. As for auto optimization, do I understand correctly, that "auto optimization" is equivalent to "native_intel || native_amd"?

**Comment by ptr1337** [comment]
> Hello. Thank you! I didn't test new `PKGBUILD` yet but it looks good. As for auto optimization, do I understand correctly, that "auto optimization" is equivalent to "native_intel || native_amd"?

Hey, 

the auto optimization if enabled detects automatically your cpu march with following command:
`gcc -Q -march=native --help=target`

and will use then the detected march for your rig. I inclueded into the script some fixes for wrong detected marches.
