### ISSUE TITLE
linux-cachyos-6.6.0-1 breaks the vmware modules (6.6-rc7 and linux-amd-6.6.0-1 work fine)

### ISSUE THREAD

**Issue by Mangoes** [CachyOS/linux-cachyos#181]
Hi,

The dkms [vmware-workstation 17.5.0-1](https://aur.archlinux.org/packages/vmware-workstation) modules fail to build when installing linux-cachyos-6.6.0-1.

Everything was fine with the rc7 and [linux-amd 6.6.v.0-1](https://aur.archlinux.org/packages/linux-amd).

I could post more info, but I think it would be easier for you to reproduce this if you install vmware-workstation (AUR).

Thanks!

**Comment by ptr1337** [comment]
> Hi,
> 
> The dkms [vmware-workstation 17.5.0-1](https://aur.archlinux.org/packages/vmware-workstation) modules fail to build when installing linux-cachyos-6.6.0-1.
> 
> Everything was fine with the rc7 and [linux-amd 6.6.v.0-1](https://aur.archlinux.org/packages/linux-amd).
> 
> I could post more info, but I think it would be easier for you to reproduce this if you install vmware-workstation (AUR).
> 
> Thanks!

Hi,

Can you provide logs? Also are you sure you did the build the kernel with gcc and not llvm(thin)lto?
The GCC variant should work without problems, the thinlto variant is known to not work with vmware-dkms. This needs to be fixed upstream

**Comment by Mangoes** [comment]
> Can you provide logs? Also are you sure you did the build the kernel with gcc and not llvm(thin)lto? The GCC variant should work without problems, the thinlto variant is known to not work with vmware-dkms. This needs to be fixed upstream

I have built linux-cachyos-6.6.0-1 with exactly the same PGDBUILD settings as I had built linux-cachyos-rc 6.6.rc7-1. (it uses llvm by default, but I don't know where to change it to gcc?. I have NOT enabled lto).

With linux-cachyos-rc 6.6.rc7-1 it worked. I have also installed linux-amd 6.6.v.0-1, so I know the release 6.6 also works.

The only change I see, is that you have added some cachyos patches to the final release.

Thanks!

Log is attached:
[make.log.zip](https://github.com/CachyOS/linux-cachyos/files/13217477/make.log.zip)

**Comment by ptr1337** [comment]
Hi,

Somehow this seems unlikely to me. The Kernel does not use llvm as default, it does use GCC.
The patches did not change between rc7-1 and release commit as you can see here:
https://github.com/CachyOS/kernel-patches/commit/7b8cf7c800c3aab6e81e9c791bf27a8c21e520bf#diff-de0da65ddbe61dfd950d597fdf58c1fd6a9230b2224d58a784e2c6b5093545cb

I also can't reproduce this see following log:
```
(4/7) Install DKMS modules
==> dkms install --no-depmod vmware-workstation/17.5.0_22583795 -k 6.5.9-1-cachyos-eevdf
==> dkms install --no-depmod vmware-workstation/17.5.0_22583795 -k 6.5.9-1-cachyos-bore
==> dkms install --no-depmod vmware-workstation/17.5.0_22583795 -k 6.5.9-1-cachyos-cfs
==> dkms install --no-depmod vmware-workstation/17.5.0_22583795 -k 6.4.0-rc2-3-cachyos-sched-ext
==> dkms install --no-depmod vmware-workstation/17.5.0_22583795 -k 6.6.0-1-cachyos
==> dkms install --no-depmod vmware-workstation/17.5.0_22583795 -k 6.5.9-1-cachyos-lto
Error! Bad return status for module build on kernel: 6.5.9-1-cachyos-lto (x86_64)
Consult /var/lib/dkms/vmware-workstation/17.5.0_22583795/build/make.log for more information.
==> WARNING: `dkms install --no-depmod vmware-workstation/17.5.0_22583795 -k 6.5.9-1-cachyos-lto' exited 10
==> dkms install --no-depmod vmware-workstation/17.5.0_22583795 -k 6.6.0-rc2-1-sched-ext-git-gbac7dab4f8f5
==> dkms install --no-depmod vmware-workstation/17.5.0_22583795 -k 6.6.0-rc7-2-cachyos-rc
==> depmod 6.6.0-1-cachyos
==> depmod 6.5.9-1-cachyos-eevdf
==> depmod 6.4.0-rc2-3-cachyos-sched-ext
==> depmod 6.6.0-rc7-2-cachyos-rc
==> depmod 6.6.0-rc2-1-sched-ext-git-gbac7dab4f8f5
==> depmod 6.5.9-1-cachyos-cfs
==> depmod 6.5.9-1-cachyos-bore
```

There you can see, that rc7 and 6.6.0 stable dkms are working fine. There seems to be something on your end. Did you added any changes to the your build?
As you can see above, the "LTO" variant is failing (which does use clang, and clang introduced with clang-16 the wstrict-prototypes warning to error)

**Comment by Mangoes** [comment]
> Did you added any changes to the your build?

I always build it with kfci enabled (this makes it also use clang). I have now disabled kfci, and EVERYTHING IS FINE (it switched to using gcc with this change). The vmware modules now build correctly.

What do you think of kfci performance wise? Is it useful?

(You can close this after this).

Thanks for your help.

**Comment by ptr1337** [comment]
Hi,

kCFI is a implentation of CFI for the kernel.
it does more likely reduce the performance and not improve it. But the performance which CFI takes should be between 1-5 %

Here is a article about it:
https://lwn.net/Articles/810077/
https://source.android.com/docs/security/test/kcf
