### ISSUE TITLE
linux-cachyos-hardened-lto - nvidia driver is out of date

### ISSUE THREAD

**Issue by ilikenwf** [CachyOS/linux-cachyos#185]
Is there any kind of enumerated list anywhere of what hardening you have enabled? Likewise, how EEVDF + BORE compares to just one or the other, stock, etc...

I'd also love to see how your kernel compares to zen.

**Comment by ilikenwf** [comment]
Ah, it appears that I need to install the driver, but the nvidia package for this one is out of date.

**Comment by sirlucjan** [comment]
We use the hardened patch from Arch Linux: https://github.com/anthraxx/linux-hardened/releases/tag/6.5.9-hardened1

The latest Nvidia driver is version 545.29.02:
https://github.com/CachyOS/linux-cachyos/blob/master/archive/linux-cachyos-hardened/PKGBUILD#L203

However, actually the -lto version did not build this kernel for some reason, we will investigate with @ptr1337 and @vnepogodin

**Comment by ptr1337** [comment]
> Is there any kind of enumerated list anywhere of what hardening you have enabled? Likewise, how EEVDF + BORE compares to just one or the other, stock, etc...
> 
> I'd also love to see how your kernel compares to zen.

Hi,

The hardened patchset is based on "linux-hardened". Same counts for the config, so we will push the 6.6 as soon anthraxx updates his patchset and config on top of our patchset and the bore scheduler.
Basically a bit optimized linux-hardened variant.

Related to the rebuild of nvidia I will take a look into.

**Comment by ilikenwf** [comment]
Good to know, thanks for digging.

I've been super lazy lately, I'm actually the AUR maintainer of the linux-zen-git PKGBUILD but haven't updated it in a while. I've been using and building zen since it was known as the kamikaze patchset on the gentoo forums 10-15 years ago.

Have you ported any of the Zen patchset pieces over? Some of their low latency stuff is pretty good. I haven't really benchmarked between stock kernel, zen, linux-cachyos-lto, and linux-cachyos-hardened-lto but would love to at some point.

On my current (new) machine it is hard to feel much difference latency wise because it's a System76 Serval WS with an i9-13900HX...my last laptop I would have been able to get by more with what feels faster but now I'm not sure I can sense a difference because I have 32 cores and 64gb ram....

**Comment by ptr1337** [comment]
> Good to know, thanks for letting me know. I do like hardening as long as the performance impact is low.
> 
> I've been super lazy lately, I'm actually the AUR maintainer of the linux-zen-git PKGBUILD but haven't updated it in a while. I've been using and building zen since it was known as the kamikaze patchset on the gentoo forums 10-15 years ago.
> 
> Have you ported any of the Zen patchset pieces over? Some of their low latency stuff is pretty good. I haven't really benchmarked between stock kernel, zen, linux-cachyos-lto, and linux-cachyos-hardened-lto but would love to at some point.
> 
> On my current (new) machine it is hard to feel much difference latency wise because it's a System76 Serval WS with an i9-13900HX...my last laptop I would have been able to get by more with what feels faster but now I'm not sure I can sense a difference because I have 32 cores and 64gb ram....

We are using some equal changes as ZEN does, but we don't follow them completlely. You can mainly find them in the 0001-cachy.patch or https://github.com/CachyOS/linux/commits/6.6/cachy

Some stuff is included in this commit:
https://github.com/CachyOS/linux/commit/2d71e8f80b66d06c3d673d53a805c14963466df8

Since the "cfs" tweaks dont exist anymore, due EEVDF has replaced it.
We are working currently in finding a better base_slice value, which will be a bit higher then zen uses, but only minimally over it, to improve the responsives under load. EEVDF's latency is already very great.

The BORE Scheduler does already apply some minimal changes there, which you can find at this part:
https://github.com/CachyOS/kernel-patches/blob/master/6.6/sched/0001-bore-cachy.patch#L328-L369

**Comment by ilikenwf** [comment]
I will admit, the EEVDF+BORE amalgamation in the cachyos-lto kernel feels great so far...and I ported my librewolf profile over to cachy-browser...that actually did make a noticeable latency difference for me...all the benefits but no downsides.
