### ISSUE TITLE
sched-ext: No such file or directory

### ISSUE THREAD

**Issue by extSunset** [CachyOS/linux-cachyos#186]
When trying to build a kernel with sched-ext, I get an error that this directory is missing:
https://github.com/CachyOS/linux-cachyos/blob/7fab8238805a91898554070712c09290d3d3c0e5/linux-cachyos/PKGBUILD#L698
Isn't the path supposed to be like this?
```
cd "$srcdir/$_srcname/tools/sched_ext"
```
Same here:
https://github.com/CachyOS/linux-cachyos/blob/7fab8238805a91898554070712c09290d3d3c0e5/linux-cachyos/PKGBUILD#L847

**Comment by sirlucjan** [comment]
Thanks for report.

Could you check now? https://github.com/CachyOS/linux-cachyos/commit/96f27a595b629a59973df54638816e17f9042c02
