### ISSUE TITLE
Build fail undefined symbol: preempt_model_none

### ISSUE THREAD

**Issue by Wireless4024** [CachyOS/linux-cachyos#19]
I'm using Arch linux and build `linux-cachyos-bmq` using `yay` 

What I changed in PKGBUILD
```
_NUMAdisable=n
_cc_harder=y
_per_gov=n
_HZ_ticks=1000
_preempt=full
_use_auto_optimization=y
_use_llvm_lto=thin
```

my config (mostly enable numa stuff)
[config-5.18.3-1-cachyos-bmq-lto.txt](https://github.com/CachyOS/linux-cachyos/files/8883369/config-5.18.3-1-cachyos-bmq-lto.txt)

here is error
```
  AR      drivers/gpu/built-in.a
  AR      drivers/built-in.a
drivers/infiniband/hw/hfi1/hfi1.prelink.o: warning: objtool: tune_serdes()+0x55a: can't find jump dest instruction at .text.tune_serdes+0xbae
  GEN     .version

  CHK     include/generated/compile.h
  GEN     .tmp_initcalls.lds
  LTO     vmlinux.o
  OBJTOOL vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
ld.lld: error: undefined symbol: preempt_model_none
>>> referenced by fbdev.c
>>>               vmlinux.o:(print_trace_header)

ld.lld: error: undefined symbol: preempt_model_voluntary
>>> referenced by fbdev.c
>>>               vmlinux.o:(print_trace_header)

ld.lld: error: undefined symbol: preempt_model_full
>>> referenced by fbdev.c
>>>               vmlinux.o:(print_trace_header)
make: *** [Makefile:1157: vmlinux] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by ptr1337** [comment]
Hey, 
Thanks for your report. It seems that i did something at the merge process with 5.18.3 wrong, I did probably already fixed it right now and compile now a test kernel.
I will push a new pkgrel with the updated patch.

**Comment by Wireless4024** [comment]
IIRC `linux-cachyos-bmq` failed to build since 5.17.x

**Comment by ptr1337** [comment]
> IIRC `linux-cachyos-bmq` failed to build since 5.17.x

I dont think so, since the server did built the kernels fine.
I did right now also a compile which went fine, but I did also updated a patch which caused your issue when building with llvm.
`cachyos-v3/linux-cachyos-bmq 5.18.3-1 [installed: 5.18.3-2]
    The Linux BMQ scheduler Kernel by CachyOS with other patches and improvements kernel and modules
cachyos-v3/linux-cachyos-bmq-headers 5.18.3-1 [installed: 5.18.3-2]
    Headers and scripts for building modules for the Linux BMQ scheduler Kernel by CachyOS with
    other patches and improvements kernel
cachyos-v3/linux-cachyos-bmq-lto 5.18.3-1
    The Linux BMQ scheduler Kernel by CachyOS with other patches and improvements kernel and modules
cachyos-v3/linux-cachyos-bmq-lto-headers 5.18.3-1
    Headers and scripts for building modules for the Linux BMQ scheduler Kernel by CachyOS with
    other patches and improvements kernel
cachyos-v3/linux-cachyos-bmq-lto-zfs 5.18.3-1
    zfs module for the Linux BMQ scheduler Kernel by CachyOS with other patches and improvements
    kernel`

Pushing update in some minutes.

**Comment by Wireless4024** [comment]
Thanks for update, I'll close if it work.

**Comment by ptr1337** [comment]
Pushed:
https://github.com/CachyOS/linux-cachyos/commit/f80190a1580dd4dc6ac35c6e4715151276e6a39e

**Comment by Wireless4024** [comment]
```shell
$ yay cachy bmq
==> 1 2
```
after nconfig it said :
```
==> Sources are ready.
 -> could not find PKGDEST for: linux-cachyos-bmq
```
work around :
remove `linux-cachyos-bmq-lto/src` and cd into `linux-cachyos-bmq` then `MAKEPKG` work fine

**Comment by ptr1337** [comment]
Config does not reset, it does prepare to your device the config / or if missing config variables are there. 
I take a watch, thought normally all missing CONFIG variables are in

**Comment by ptr1337** [comment]
Just did tested myself, enabled THIN LTO got no prompts. 
It seems that paru caches the config, maybe also the patches which would be really mad. I really not recommend to use a aur-helper for that in general.

Checking for updates, yes. But not for building.
If you want to have a easy building solution check out our Kernel Manager which is a GUI for building the kernel and configure it.

https://wiki.cachyos.org/en/home/kernel-manager

**Comment by Wireless4024** [comment]
does kernel-manager allow to edit advanced config? I did a lot of config like disable THP, tracing, use schedutil gov, enable numa support

**Comment by ptr1337** [comment]
> does kernel-manager allow to edit advanced config? I did a lot of config like disable THP, tracing, use schedutil gov, enable numa support

You can change most stuff already in the PKGBUILD at the top, if you want to do additional configuration just enable "makenconfig" which does start then a config menu where you can select/change more advanced functions. 

The options which are available right now you can see here:
https://wiki.cachyos.org/cachyos-km2.png

makenconfig, build_zfs, will be added soon.

**Comment by Wireless4024** [comment]
ok great. last question `make nconfig` vs `make menuconfig` which is better?

**Comment by ptr1337** [comment]
> ok great. last question `make nconfig` vs `make menuconfig` which is better?

Actually I could all "make config" solution as variable. The difference mostly is just how the configuration part looks like.
