### ISSUE TITLE
Enabling PREEMPT_AUTO and PREEMPT_RT will result in PREEMPT_RT disabled

### ISSUE THREAD

**Issue by olm52** [CachyOS/linux-cachyos#193]
In the linux-cachyos-rt PKGBUILD there is:

rt) scripts/config -e PREEMPT_COUNT -e PREEMPTION -d PREEMPT_VOLUNTARY -d PREEMPT -d PREEMPT_NONE -e PREEMPT_RT -e PREEMPT_AUTO -d PREEMPT_DYNAMIC -e HAVE_PREEMPT_AUTO -d PREEMPT_BUILD;;

However I think that PREEMPT_AUTO and PREEMPT_RT should not enabled at the same time. This will result in PREEMPT_RT not enabled. 

A more simple configuration could be:
rt) scripts/config -e PREEMPT_RT -e HAVE_PREEMPT_AUTO;

that will result in:

```
CONFIG_PREEMPT_BUILD=y
CONFIG_PREEMPT_BUILD_AUTO=y
CONFIG_HAVE_PREEMPT_AUTO=y
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
# CONFIG_PREEMPT is not set
# CONFIG_PREEMPT_AUTO is not set
CONFIG_PREEMPT_RT=y
CONFIG_PREEMPT_COUNT=y
CONFIG_PREEMPTION=y
CONFIG_SCHED_CORE=y
```

See last RT patch 6.6-rt12 (I think you are using an older one):

```
+config PREEMPT_AUTO
+	bool "Automagic preemption mode with runtime tweaking support"
+	depends on HAVE_PREEMPT_AUTO
+	select PREEMPT_BUILD_AUTO
+	help
+	  Add some sensible blurb here
+
 config PREEMPT_RT
 	bool "Fully Preemptible Kernel (Real-Time)"
 	depends on EXPERT && ARCH_SUPPORTS_RT
+	select PREEMPT_BUILD_AUTO if HAVE_PREEMPT_AUTO
 	select PREEMPTION
 	help
 	  This option turns the kernel into a real-time kernel by replacing
```

It is no clear in available documentation what "runtime tweaking support" is about. Using only PREEMPT_AUTO will not allow to use chrt to set fifo priority for example (unless there is some unknown tweaking...)

**Comment by ptr1337** [comment]
> In the linux-cachyos-rt PKGBUILD there is:
> 
> rt) scripts/config -e PREEMPT_COUNT -e PREEMPTION -d PREEMPT_VOLUNTARY -d PREEMPT -d PREEMPT_NONE -e PREEMPT_RT -e PREEMPT_AUTO -d PREEMPT_DYNAMIC -e HAVE_PREEMPT_AUTO -d PREEMPT_BUILD;;
> 
> However I think that PREEMPT_AUTO and PREEMPT_RT should not enabled at the same time. This will result in PREEMPT_RT not enabled.
> 
> A more simple configuration could be: rt) scripts/config -e PREEMPT_RT -e HAVE_PREEMPT_AUTO;
> 
> that will result in:
> 
> ```
> CONFIG_PREEMPT_BUILD=y
> CONFIG_PREEMPT_BUILD_AUTO=y
> CONFIG_HAVE_PREEMPT_AUTO=y
> # CONFIG_PREEMPT_NONE is not set
> # CONFIG_PREEMPT_VOLUNTARY is not set
> # CONFIG_PREEMPT is not set
> # CONFIG_PREEMPT_AUTO is not set
> CONFIG_PREEMPT_RT=y
> CONFIG_PREEMPT_COUNT=y
> CONFIG_PREEMPTION=y
> CONFIG_SCHED_CORE=y
> ```
> 
> See last RT patch 6.6-rt12 (I think you are using an older one):
> 
> ```
> +config PREEMPT_AUTO
> +	bool "Automagic preemption mode with runtime tweaking support"
> +	depends on HAVE_PREEMPT_AUTO
> +	select PREEMPT_BUILD_AUTO
> +	help
> +	  Add some sensible blurb here
> +
>  config PREEMPT_RT
>  	bool "Fully Preemptible Kernel (Real-Time)"
>  	depends on EXPERT && ARCH_SUPPORTS_RT
> +	select PREEMPT_BUILD_AUTO if HAVE_PREEMPT_AUTO
>  	select PREEMPTION
>  	help
>  	  This option turns the kernel into a real-time kernel by replacing
> ```
> 
> It is no clear in available documentation what "runtime tweaking support" is about. Using only PREEMPT_AUTO will not allow to use chrt to set fifo priority for example (unless there is some unknown tweaking...)

Hi,

PREEMPT_AUTO is the NEW preemption modell for RT. You can read this here:
https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/tree/patches/PREEMPT_AUTO.patch?h=v6.6-rc6-rt10-patches


Did you test, if PREEMPT_AUTO is really not possible to set to fifo?
We will check this later and will otherwise the change the configs to it. Arch has also made (somwhere) a commit at the RT kernel, where they did change from PREEMPT_RT to PREEMPT_AUTO.

@ventureoo What do you think?

**Comment by ventureoo** [comment]
Unfortunately you are right, PREEMPT_AUTO does make PREEMPT_RT not set. Which is a bit confusing to me, as I'm not quite sure why PREEMPT_AUTO would then become part of the RT patches.

**Comment by olm52** [comment]
I have tested various configurations for some time... and the only working is the one reported before:
rt) scripts/config -e PREEMPT_RT -e HAVE_PREEMPT_AUTO;
The conclusion is that with PREEMPT_AUTO some tweaking/extra configuration (not reported) is necessary.
