### ISSUE TITLE
Allow building ZFS with Clang

### ISSUE THREAD

**Issue by extSunset** [CachyOS/linux-cachyos#195]
I suggest removing workaround to allow building ZFS with Clang (LTO), but with `-Wno-error=uninitialized` added to KCFLAGS when building ZFS.
https://github.com/CachyOS/linux-cachyos/blob/7bf97b170e22853199340de66928fa1442daa959/linux-cachyos/PKGBUILD#L304-L308

Or a patch could be added based on this comment.
https://github.com/openzfs/zfs/issues/15384#issuecomment-1792826711

**Comment by ptr1337** [comment]
Hi,

I will try the next days adding `-Wno-error=uninitialized`. 
You could also try adding the folliowing before the ZFS part:

```
export KCPPFLAGS+=' -Wno-error=uninitialized
export KCFLAGS+=' -Wno-error=uninitialized
```

**Comment by ptr1337** [comment]
Fix does work. We will add it to the PKBUILD as a temporally workaround.
