### ISSUE TITLE
6.6.0-cb2.0.fc39.x86_64 :: eevdf enabled?

### ISSUE THREAD

**Issue by stefangweichinger** [CachyOS/linux-cachyos#197]
I run 6.6.0-cb2.0.fc39.x86_64 on Fedora 39 and wonder, is EEVDF enabled? (How) can I check this?
Thanks for all your great work!

**Comment by sirlucjan** [comment]
EEVDF is enabled by default. In kernel 6.6, this replaced CFS and is active by default.

**Comment by stefangweichinger** [comment]
@sirlucjan thanks for the fast and helpful reply

**Comment by sirlucjan** [comment]
You're welcome.

**Comment by stefangweichinger** [comment]
even if this issue is closed: let me add that this kernel is super snappy in my F39 gnome session. even with balanced energy settings.
