### ISSUE TITLE
Not build linux-cachyos-bore - Not downloading 0001-migrate.patch 404

### ISSUE THREAD

**Issue by KirMozor** [CachyOS/linux-cachyos#20]
```
➜  Tools git clone https://github.com/CachyOS/linux-cachyos.git                                                                                     
Cloning into 'linux-cachyos'...
remote: Enumerating objects: 5846, done.
remote: Counting objects: 100% (1834/1834), done.
remote: Compressing objects: 100% (582/582), done.
remote: Total 5846 (delta 1258), reused 1823 (delta 1252), pack-reused 4012
Receiving objects: 100% (5846/5846), 5.58 MiB | 238.00 KiB/s, done.
Resolving deltas: 100% (3835/3835), done.
➜  Tools cd linux-cachyos/linux-cachyos-bore
➜  linux-cachyos-bore git:(master) sed -i 's/_use_llvm_lto=/_use_llvm_lto=full/' PKGBUILD
➜  linux-cachyos-bore git:(master) ✗ nvim PKGBUILD
➜  linux-cachyos-bore git:(master) ✗ sed -i 's/_makenconfig=/_makenconfig=y/' PKGBUILD
➜  linux-cachyos-bore git:(master) ✗ makepkg -sric                                     
==> Making package: linux-cachyos-bore-lto 5.18.3-2 (Mon 20 Jun 2022 12:56:27 AM +06)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading linux-5.18.3.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  123M  100  123M    0     0   235k      0  0:08:16  0:08:16 --:--:--  239k
  -> Found config
  -> Downloading 0001-bore-sched.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8139  100  8139    0     0   5726      0  0:00:01  0:00:01 --:--:--  5727
  -> Downloading 0001-migrate.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://raw.githubusercontent.com/ptr1337/kernel-patches/master/5.18/0001-migrate.patch
    Aborting...
```
My PKGBUILD file: https://pastebin.com/Fj5vyfMW

**Comment by RiverOnVenus** [comment]
> ```
> ➜  Tools git clone https://github.com/CachyOS/linux-cachyos.git                                                                                     
> Cloning into 'linux-cachyos'...
> remote: Enumerating objects: 5846, done.
> remote: Counting objects: 100% (1834/1834), done.
> remote: Compressing objects: 100% (582/582), done.
> remote: Total 5846 (delta 1258), reused 1823 (delta 1252), pack-reused 4012
> Receiving objects: 100% (5846/5846), 5.58 MiB | 238.00 KiB/s, done.
> Resolving deltas: 100% (3835/3835), done.
> ➜  Tools cd linux-cachyos/linux-cachyos-bore
> ➜  linux-cachyos-bore git:(master) sed -i 's/_use_llvm_lto=/_use_llvm_lto=full/' PKGBUILD
> ➜  linux-cachyos-bore git:(master) ✗ nvim PKGBUILD
> ➜  linux-cachyos-bore git:(master) ✗ sed -i 's/_makenconfig=/_makenconfig=y/' PKGBUILD
> ➜  linux-cachyos-bore git:(master) ✗ makepkg -sric                                     
> ==> Making package: linux-cachyos-bore-lto 5.18.3-2 (Mon 20 Jun 2022 12:56:27 AM +06)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Downloading linux-5.18.3.tar.xz...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  123M  100  123M    0     0   235k      0  0:08:16  0:08:16 --:--:--  239k
>   -> Found config
>   -> Downloading 0001-bore-sched.patch...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  8139  100  8139    0     0   5726      0  0:00:01  0:00:01 --:--:--  5727
>   -> Downloading 0001-migrate.patch...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0    14    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 404
> ==> ERROR: Failure while downloading https://raw.githubusercontent.com/ptr1337/kernel-patches/master/5.18/0001-migrate.patch
>     Aborting...
> ```
> 
> My PKGBUILD file: [pastebin.com/Fj5vyfMW](https://pastebin.com/Fj5vyfMW)

Why is it 5.18.5 in PKGBUILD but in download linux-5.18.3?

And there is no 0001-migrate.patch in the latest PKGBUILD. It seems to be included in 0001-cachy.patch.

Maybe re-clone the latest repository and build it again will solve your problem.

I just tried it and there was no problem.[https://paste.mozilla.org/HZQL7GSL](https://paste.mozilla.org/HZQL7GSL)
