### ISSUE TITLE
skylake2 missing in config but assigned in optimization

### ISSUE THREAD

**Issue by olm52** [CachyOS/linux-cachyos#200]
In auto-cpu-optimization.sh there is:

SKYLAKE-AVX512) MARCH="SKYLAKE2";;

but SKYLAKE2 does not exist in kernel config
In  configure script there are only these 2 lines for SKYLAKE:

  > 49) MSKYLAKE : Select this for 6th Gen Core processors in the Skylake family.\n \
  > 50) MSKYLAKEX : Select this for 6th Gen Core processors in the Skylake X family.\n \

**Comment by ptr1337** [comment]
Hi olm52,

Yes, you are right. I needs to be updated.

**Comment by ptr1337** [comment]
Sorry for the delay, its fixed here:
https://github.com/CachyOS/linux-cachyos/commit/37c9c7d16a50395083ee5d66ee0f514f7f46d311
