### ISSUE TITLE
Wrong config option for Steam Deck

### ISSUE THREAD

**Issue by kode54** [CachyOS/linux-cachyos#202]
`s/DRM_AMD_COLOR_STEAMDECK/CONFIG_DRM_AMD_COLOR_STEAMDECK/` needs to be applied.

**Comment by ptr1337** [comment]
> `s/DRM_AMD_COLOR_STEAMDECK/CONFIG_DRM_AMD_COLOR_STEAMDECK/` needs to be applied.


Yes, I noticed. Was a copy paste issue :(
Will fix it after work
