### ISSUE TITLE
Kernel 6.7 runs into bug

### ISSUE THREAD

**Issue by Betaminos** [CachyOS/linux-cachyos#211]
Hello there,

I have updated my device (Intel 1165g7 with an Intel AX201) to the latest version (6.7.0-2) of linux-cachyos-lto and got stuck at boot.
The device had been running  version 6.6.9 (I think, might have been 6.6.10) just fine and still boots the linux-lts kernel just fine.

Booting the LTS kernel and looking into journalctl, I am able to find this issue:
> Jan 10 17:55:05 oxp kernel: iwlwifi 0000:00:14.3: Registered PHC clock: iwlwifi-PTP, with index: 0
Jan 10 17:55:05 oxp kernel: BUG: kernel NULL pointer dereference, address: 0000000000000027
Jan 10 17:55:07 oxp kernel: #PF: supervisor read access in kernel mode
Jan 10 17:55:07 oxp kernel: #PF: error_code(0x0000) - not-present page
Jan 10 17:55:07 oxp kernel: PGD 0 P4D 0 
Jan 10 17:55:07 oxp kernel: Oops: 0000 [#1] PREEMPT SMP NOPTI
Jan 10 17:55:07 oxp kernel: CPU: 1 PID: 508 Comm: NetworkManager Tainted: G     U             6.7.0-1-cachyos #1 7ac8f176531ce14e23536bca11d29bd855c2d126
Jan 10 17:55:07 oxp kernel: Hardware name: ONE-NETBOOK TECHNOLOGY CO., LTD. ONE XPLAYER/ONE XPLAYER, BIOS 1AWHY9.16 07/29/2021
Jan 10 17:55:07 oxp kernel: RIP: 0010:iwl_mvm_vif_dbgfs_add_link+0x7e/0xc0 [iwlmvm]
Jan 10 17:55:07 oxp kernel: Code: 03 f3 48 ab 4d 85 ed 74 34 48 89 f3 4c 89 e9 48 c7 c2 d0 6e 88 c1 4c 89 e7 be 64 00 00 00 e8 69 a6 cd e9 48 8b b5 c8 1c 00 00 <49> 8b 7d 28 4c 89 e2 e8 26 73 17 e9 48 89 83 a8 05 00 00 48 8b 44
Jan 10 17:55:07 oxp kernel: RSP: 0018:ffffb5e240f17528 EFLAGS: 00010246
Jan 10 17:55:07 oxp kernel: RAX: 0000000000000018 RBX: ffff99a7febd1c38 RCX: 0000000000000007
Jan 10 17:55:07 oxp kernel: RDX: 0000000000000000 RSI: ffffffffffffffff RDI: 0000000040f1752c
Jan 10 17:55:07 oxp kernel: RBP: ffff99a7febc1fc8 R08: ffffffffc1886ee3 R09: 0000000000000000
Jan 10 17:55:07 oxp kernel: R10: 0000000000000001 R11: ffff99a641022740 R12: ffffb5e240f1752c
Jan 10 17:55:07 oxp kernel: R13: ffffffffffffffff R14: ffff99a7febc1fc8 R15: ffff99a7febc1ff8
Jan 10 17:55:07 oxp kernel: FS:  000075beed16f200(0000) GS:ffff99a9dfa80000(0000) knlGS:0000000000000000
Jan 10 17:55:07 oxp kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jan 10 17:55:07 oxp kernel: CR2: 0000000000000027 CR3: 0000000319590005 CR4: 0000000000f70ef0
Jan 10 17:55:07 oxp kernel: PKRU: 55555554
Jan 10 17:55:07 oxp kernel: Call Trace:
Jan 10 17:55:07 oxp kernel:  <TASK>
Jan 10 17:55:07 oxp kernel:  ? __die+0x10f/0x120
Jan 10 17:55:07 oxp kernel:  ? page_fault_oops+0x171/0x4e0
Jan 10 17:55:07 oxp kernel:  ? iwl_trans_txq_send_hcmd+0x378/0x450 [iwlwifi 3940a8dc9c07da7cae772959db6bee70abb9a64a]
Jan 10 17:55:07 oxp kernel:  ? exc_page_fault+0x7f/0x180
Jan 10 17:55:07 oxp kernel:  ? asm_exc_page_fault+0x26/0x30
Jan 10 17:55:07 oxp kernel:  ? iwl_mvm_vif_dbgfs_add_link+0x7e/0xc0 [iwlmvm fe51517ac1558995d120518ebd75b9887f4b1c56]
Jan 10 17:55:07 oxp kernel:  ? iwl_mvm_vif_dbgfs_add_link+0x77/0xc0 [iwlmvm fe51517ac1558995d120518ebd75b9887f4b1c56]
Jan 10 17:55:07 oxp kernel:  iwl_mvm_mld_mac_add_interface+0x2f9/0x360 [iwlmvm fe51517ac1558995d120518ebd75b9887f4b1c56]
Jan 10 17:55:07 oxp kernel:  drv_add_interface+0x4f/0x230 [mac80211 61dd4b653cc4ebe2bed93583066fa47650cd325e]
Jan 10 17:55:07 oxp kernel:  ieee80211_do_open+0x4f0/0x7c0 [mac80211 61dd4b653cc4ebe2bed93583066fa47650cd325e]
Jan 10 17:55:07 oxp kernel:  ieee80211_open+0x66/0x90 [mac80211 61dd4b653cc4ebe2bed93583066fa47650cd325e]
Jan 10 17:55:07 oxp kernel:  __dev_open+0x128/0x1f0
Jan 10 17:55:07 oxp kernel:  __dev_change_flags+0x28c/0x330
Jan 10 17:55:07 oxp kernel:  ? rtnl_getlink+0x296/0x440
Jan 10 17:55:07 oxp kernel:  dev_change_flags+0x43/0x260
Jan 10 17:55:07 oxp kernel:  do_setlink+0x3be/0x1400
Jan 10 17:55:07 oxp kernel:  ? __nla_parse+0x43/0x2a0
Jan 10 17:55:07 oxp kernel:  __rtnl_newlink+0x5cc/0xb70
Jan 10 17:55:07 oxp kernel:  ? rtnl_newlink+0x2e/0x70
Jan 10 17:55:07 oxp kernel:  rtnl_newlink+0x47/0x70
Jan 10 17:55:07 oxp kernel:  rtnetlink_rcv_msg+0x14f/0x3c0
Jan 10 17:55:07 oxp kernel:  ? netlink_unicast+0x21b/0x600
Jan 10 17:55:07 oxp kernel:  ? __skb_try_recv_datagram+0xcc/0x320
Jan 10 17:55:07 oxp kernel:  ? __pfx_rtnetlink_rcv_msg+0x10/0x10
Jan 10 17:55:07 oxp kernel:  netlink_rcv_skb+0x58/0x110
Jan 10 17:55:07 oxp kernel:  netlink_unicast+0x557/0x600
Jan 10 17:55:07 oxp kernel:  netlink_sendmsg+0x250/0x4d0
Jan 10 17:55:07 oxp kernel:  ____sys_sendmsg+0x395/0x3d0
Jan 10 17:55:07 oxp kernel:  ___sys_sendmsg+0x15a/0x1e0
Jan 10 17:55:07 oxp kernel:  __sys_sendmsg+0xc8/0x100
Jan 10 17:55:07 oxp kernel:  do_syscall_64+0x61/0xe0
Jan 10 17:55:07 oxp kernel:  ? syscall_exit_to_user_mode+0x2b/0x40
Jan 10 17:55:07 oxp kernel:  ? do_syscall_64+0x70/0xe0
Jan 10 17:55:07 oxp kernel:  ? syscall_exit_to_user_mode+0x2b/0x40
Jan 10 17:55:07 oxp kernel:  ? do_syscall_64+0x70/0xe0
Jan 10 17:55:07 oxp kernel:  ? exit_to_user_mode_prepare+0x132/0x1f0
Jan 10 17:55:07 oxp kernel:  entry_SYSCALL_64_after_hwframe+0x6e/0x76
Jan 10 17:55:07 oxp kernel: RIP: 0033:0x75beed936a5e
Jan 10 17:55:07 oxp kernel: Code: 20 89 54 24 1c 48 89 74 24 10 89 7c 24 08 e8 e9 55 f6 ff 41 89 c0 8b 54 24 1c 48 8b 74 24 10 b8 2e 00 00 00 8b 7c 24 08 0f 05 <48> 3d 00 f0 ff ff 77 3a 44 89 c7 48 89 44 24 08 e8 3d 56 f6 ff 48
Jan 10 17:55:07 oxp kernel: RSP: 002b:00007ffe938d85b0 EFLAGS: 00000293 ORIG_RAX: 000000000000002e
Jan 10 17:55:07 oxp kernel: RAX: ffffffffffffffda RBX: 000000000000000a RCX: 000075beed936a5e
Jan 10 17:55:07 oxp kernel: RDX: 0000000000000000 RSI: 00007ffe938d85f0 RDI: 000000000000000d
Jan 10 17:55:07 oxp kernel: RBP: 00007ffe938d89c0 R08: 0000000000000000 R09: 0000000000000000
Jan 10 17:55:07 oxp kernel: R10: 0000000000000000 R11: 0000000000000293 R12: 00005e85d07682a0
Jan 10 17:55:07 oxp kernel: R13: 0000000000000001 R14: 0000000000000000 R15: 0000000000000000
Jan 10 17:55:07 oxp kernel:  </TASK>
Jan 10 17:55:07 oxp kernel: Modules linked in: ccm algif_aead crypto_null des3_ede_x86_64 cbc des_generic libdes algif_skcipher cmac md4 algif_hash af_alg bnep snd_sof_pci_intel_tgl snd_sof_intel_hda_common x86_pkg_temp_thermal intel_powerclamp soundwire_intel coretemp snd_sof_intel_hda_mlink soundwire_cadence kvm_intel snd_sof_intel_hda snd_sof_pci snd_sof_xtensa_dsp kvm snd_sof snd_sof_utils snd_soc_hdac_hda irqbypass crct10dif_pclmul snd_hda_ext_core crc32_pclmul polyval_clmulni snd_soc_acpi_intel_match polyval_generic gf128mul snd_soc_acpi soundwire_generic_allocation ghash_clmulni_intel soundwire_bus sha512_ssse3 sha1_ssse3 btusb snd_soc_core iwlmvm aesni_intel snd_compress hid_multitouch btrtl mac80211 crypto_simd ac97_bus snd_hda_codec_hdmi snd_pcm_dmaengine libarc4 snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio 8250_dw mousedev spi_pxa2xx_platform dw_dmac snd_hda_intel snd_intel_dspcfg cryptd btintel snd_intel_sdw_acpi processor_thermal_device_pci_legacy btbcm snd_hda_codec mei_hdcp iwlwifi btmtk mei_pxp
Jan 10 17:55:07 oxp kernel:  processor_thermal_device joydev rapl snd_hda_core processor_thermal_wt_hint snd_hwdep rtsx_usb_ms vfat processor_thermal_rfim intel_cstate intel_rapl_msr fat memstick snd_pcm spi_nor intel_uncore bluetooth snd_timer processor_thermal_rapl pcspkr xpad snd cfg80211 intel_rapl_common mtd mei_me i2c_i801 ff_memless usbhid processor_thermal_wt_req acpi_cpufreq processor_thermal_power_floor ecdh_generic mei wmi_bmof intel_lpss_pci soundcore i2c_smbus crc16 processor_thermal_mbox i2c_hid_acpi rfkill intel_lpss idma64 int340x_thermal_zone i2c_hid igen6_edac intel_soc_dts_iosf int3400_thermal acpi_thermal_rel acpi_pad acpi_tad platform_profile mac_hid ip6t_REJECT nf_reject_ipv6 xt_hl ip6t_rt ipt_REJECT nf_reject_ipv4 xt_limit xt_addrtype xt_tcpudp xt_conntrack nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 ip6table_filter ip6_tables iptable_filter sch_cake pkcs8_key_parser i2c_dev crypto_user loop fuse dm_mod nfnetlink ip_tables x_tables rtsx_usb_sdmmc mmc_core rtsx_usb serio_raw crc32c_intel sha256_ssse3 nvme atkbd
Jan 10 17:55:07 oxp kernel:  xhci_pci nvme_core libps2 xhci_pci_renesas spi_intel_pci nvme_auth spi_intel vivaldi_fmap i8042 serio btrfs blake2b_generic i915 i2c_algo_bit drm_buddy video wmi ttm intel_gtt drm_display_helper cec
Jan 10 17:55:07 oxp kernel: CR2: 0000000000000027
Jan 10 17:55:07 oxp kernel: ---[ end trace 0000000000000000 ]---
Jan 10 17:55:07 oxp kernel: RIP: 0010:iwl_mvm_vif_dbgfs_add_link+0x7e/0xc0 [iwlmvm]
Jan 10 17:55:07 oxp kernel: Code: 03 f3 48 ab 4d 85 ed 74 34 48 89 f3 4c 89 e9 48 c7 c2 d0 6e 88 c1 4c 89 e7 be 64 00 00 00 e8 69 a6 cd e9 48 8b b5 c8 1c 00 00 <49> 8b 7d 28 4c 89 e2 e8 26 73 17 e9 48 89 83 a8 05 00 00 48 8b 44
Jan 10 17:55:07 oxp kernel: RSP: 0018:ffffb5e240f17528 EFLAGS: 00010246
Jan 10 17:55:07 oxp kernel: RAX: 0000000000000018 RBX: ffff99a7febd1c38 RCX: 0000000000000007
Jan 10 17:55:07 oxp kernel: RDX: 0000000000000000 RSI: ffffffffffffffff RDI: 0000000040f1752c
Jan 10 17:55:07 oxp kernel: RBP: ffff99a7febc1fc8 R08: ffffffffc1886ee3 R09: 0000000000000000
Jan 10 17:55:07 oxp kernel: R10: 0000000000000001 R11: ffff99a641022740 R12: ffffb5e240f1752c
Jan 10 17:55:07 oxp kernel: R13: ffffffffffffffff R14: ffff99a7febc1fc8 R15: ffff99a7febc1ff8
Jan 10 17:55:07 oxp kernel: FS:  000075beed16f200(0000) GS:ffff99a9dfa80000(0000) knlGS:0000000000000000
Jan 10 17:55:07 oxp kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jan 10 17:55:07 oxp kernel: CR2: 0000000000000027 CR3: 0000000319590005 CR4: 0000000000f70ef0
Jan 10 17:55:07 oxp kernel: PKRU: 55555554
Jan 10 17:55:07 oxp kernel: note: NetworkManager[508] exited with irqs disabled

When I use the pre-compiled 6.7 kernel provided by cachyos mirrors, I am getting stuck with this error.
I have so far tried (kernel and their matching headers from the matching instruction set) the following variants:
- cachyos/linux-cachyos 6.7.0-1
- cachyos-v3/linux-cachyos 6.7.0-2
- cachyos-v3/linux-cachyos-lto 6.7.0-2
- cachyos-v4/linux-cachyos-lto 6.7.0-2

In case it helps, these are my kernel arguments (working with LTS and up to 6.6):
`options root=PARTUUID=[...] zswap.enabled=0 rootflags=subvol=/@ rw rootfstype=btrfs processor.max_cstate=9 intel_idle.max_cstate=9 nmi_watchdog=0 nowatchdog mitigations=off kernel.kexec_load_disabled=1 audit=0 split_lock_detect=off threadirqs split_lock_detect=off intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp nomce page_alloc.shuffle=1 vsyscall=none debugfs=off tsc=reliable clocksource=tsc intel_pstate=disable`

Thank you for your insights!

**Comment by ptr1337** [comment]
Hi,

Thanks for your report.
I think there is currently a issue with a various set of wifi drivers:
https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues/18

We need to wait until these are fixed in upstream. Since we dont change anything on the wifi patches, it is unlikely that it is an issue of our patchset.

**Comment by Betaminos** [comment]
> Thanks for your report. I think there is currently a issue with a various set of wifi drivers: https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues/18
> 
> We need to wait until these are fixed in upstream. Since we dont change anything on the wifi patches, it is unlikely that it is an issue of our patchset.

Thanks for pointing me to this, it does sound like the issue I am facing.

**Comment by ptr1337** [comment]
> > Thanks for your report. I think there is currently a issue with a various set of wifi drivers: https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues/18
> > We need to wait until these are fixed in upstream. Since we dont change anything on the wifi patches, it is unlikely that it is an issue of our patchset.
> 
> Thanks for pointing me to this, it does sound like the issue I am facing.

Could you recheck with the latest kernel in the repo?

**Comment by Betaminos** [comment]
> Could you recheck with the latest kernel in the repo?

Unfortunately still running into the same issue when running:
- linux-cachyos-lto 6.7.0-4
- linux 6.7.arch3-1

The only one working is the LTS, which is at this version:
- linux-lts 6.6.11-2

These are the very latest versions available to me right now via the cachyos mirrors.

**Comment by ptr1337** [comment]
> > Could you recheck with the latest kernel in the repo?
> 
> Unfortunately still running into the same issue when running:
> 
>     * linux-cachyos-lto 6.7.0-4
> 
>     * linux 6.7.arch3-1
> 
> 
> The only one working is the LTS, which is at this version:
> 
>     * linux-lts 6.6.11-2
> 
> 
> These are the very latest versions available to me right now via the cachyos mirrors.

There is also a linux-cachyos-lts, just in case. :)

**Comment by Betaminos** [comment]
I tried to find the reason for this bug, as it was not fixed by the work done in the linked ticket, and have come across it being triggered by the kernel argument "debugfs=off".
It seems to be a regression with kernel 6.7, as the kernels mentioned above can be made to work by omitting this argument and I have been using this argument for several months by now, without any issues prior to 6.7.

**Comment by ptr1337** [comment]
> I tried to find the reason for this bug, as it was not fixed by the work done in the linked ticket, and have come across it being triggered by the kernel argument "debugfs=off". It seems to be a regression with kernel 6.7, as the kernels mentioned above can be made to work by omitting this argument and I have been using this argument for several months by now, without any issues prior to 6.7.

Sadly nothing yet for 6.7.1 queued for this issue:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/log/?h=linux-6.7.y

Might consider a bugreport at bugzilla

**Comment by ptr1337** [comment]
This should be fixed in earlier kernel versions
