### ISSUE TITLE
6.7 - kernel panic with ath11k

### ISSUE THREAD

**Issue by ilikenwf** [CachyOS/linux-cachyos#212]
This is also happening on the mainline arch kernel.

https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues/18

**Comment by ptr1337** [comment]
Thanks for the report.
I saw also the issue on the gitlab issue tracker of archlinux. We need to wait until someone has identified the broken commit with bisecting

**Comment by ilikenwf** [comment]
Kernel bugzilla has a patch:

https://bugzilla.kernel.org/show_bug.cgi?id=218364

**Comment by ilikenwf** [comment]
I can confirm the fix works - thank you.
