### ISSUE TITLE
Cannot load kernel module because of CONFIG_MODULE_SIG=y

### ISSUE THREAD

**Issue by pkejval** [CachyOS/linux-cachyos#213]
Hello, I can't load kernel module "ryzen_smu" https://github.com/leogx9r/ryzen_smu because kernel is compiled with these config flags below. Could you modify it to =n or is this intended? I want this kernel module for using "ryzenadj" https://github.com/FlyGoat/RyzenAdj.

```
CONFIG_MODULE_SIG=y
CONFIG_MODULE_SIG_ALL=y
```

I'm getting this dmesg error when loading module:
```
[    2.154813] ryzen_smu: loading out-of-tree module taints kernel.
[    2.154816] ryzen_smu: module verification failed: signature and/or required key missing - tainting kernel
```

**Comment by sirlucjan** [comment]
Yes, it's intentional. It's taken straight from the Arch Linux config

https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/blob/main/config?ref_type=heads#L956-965

**Comment by pkejval** [comment]
OK. Thank you for answering.
