### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by deepinsideDrury** [CachyOS/linux-cachyos#215]
:: 进行安装吗？ [Y/n] y
:: 正在获取软件包......
 mkinitcpio-37.2-1-any                                                                                    53.0 KiB   227 KiB/s 00:00 [---------------------------------------------------------------------------------] 100%
 gst-plugin-pipewire-1:1.0.1-1-x86_64                                                                     48.2 KiB   130 KiB/s 00:00 [---------------------------------------------------------------------------------] 100%
 alsa-card-profiles-1:1.0.1-1-x86_64                                                                      28.6 KiB  71.1 KiB/s 00:00 [---------------------------------------------------------------------------------] 100%
 pipewire-alsa-1:1.0.1-1-x86_64                                                                            5.0 KiB  12.2 KiB/s 00:00 [---------------------------------------------------------------------------------] 100%
 bluez-hid2hci-5.72-2.1-x86_64                                                                            11.5 KiB  16.2 KiB/s 00:01 [---------------------------------------------------------------------------------] 100%
 libmaxminddb-1.9.1-1.1-x86_64                                                                            25.1 KiB  31.2 KiB/s 00:01 [---------------------------------------------------------------------------------] 100%
 md4c-0.5.0-1.1-x86_64                                                                                    74.3 KiB  85.0 KiB/s 00:01 [---------------------------------------------------------------------------------] 100%
linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst下载失败
linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst下载失败
 全部 (9/9)                                                                                              161.3 MiB  7.88 MiB/s 00:20 [---------------------------------------------------------------------------------] 100%
错误：无法从 kr.cachyos.org : Maximum file size exceeded 获取文件 'linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 kr.cachyos.org : Maximum file size exceeded 获取文件 'linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 mirror.truenetwork.ru : Maximum file size exceeded 获取文件 'linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 mirror.truenetwork.ru : Maximum file size exceeded 获取文件 'linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 mirror.lesviallon.fr : Maximum file size exceeded 获取文件 'linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 mirror.lesviallon.fr : Maximum file size exceeded 获取文件 'linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 aur.cachyos.org : Maximum file size exceeded 获取文件 'linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 cdn.cachyos.nyc.soulharsh007.dev : Maximum file size exceeded 获取文件 'linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 us.cachyos.org : Maximum file size exceeded 获取文件 'linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 mirror.cachyos.org : Maximum file size exceeded 获取文件 'linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 mirror.albony.xyz : Maximum file size exceeded 获取文件 'linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 hun.cachyos.org : Maximum file size exceeded 获取文件 'linux-cachyos-headers-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 aur.cachyos.org : Failed to connect to aur.cachyos.org port 443 after 10002 ms: Timeout was reached 获取文件 'linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 cdn.cachyos.nyc.soulharsh007.dev : Maximum file size exceeded 获取文件 'linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 us.cachyos.org : Maximum file size exceeded 获取文件 'linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 mirror.cachyos.org : Maximum file size exceeded 获取文件 'linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 mirror.albony.xyz : Maximum file size exceeded 获取文件 'linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst'
错误：无法从 hun.cachyos.org : Maximum file size exceeded 获取文件 'linux-cachyos-6.7.0-4-x86_64_v3.pkg.tar.zst'
警告：无法获取某些文件
错误：无法提交处理 (下载数据库出错)
发生错误，没有软件包被更新。

**Comment by ptr1337** [comment]
Could you try a sudo pacman -Syu?

linux-cachyos-6.7.0-4 is not anymore in the repository.

**Comment by deepinsideDrury** [comment]
after sh /usr/share/cachyos-hello/scripts/rootshell.sh cachyos-rate-mirrors; and it's ok
