### ISSUE TITLE
[REQUEST] Disable specify configs if the cpu microarchitecture is amd or intel

### ISSUE THREAD

**Issue by AldairbotHerotaku** [CachyOS/linux-cachyos#22]
like on configure put
```
elif [[ "$_microarchitecture" = "45" ]]; then
    scripts/config --disable CONFIG_GENERIC_CPU
    scripts/config --disable CONFIG_AGP_AMD64 
    scripts/config --disable CONFIG_MICROCODE_AMD
    scripts/config --enable CONFIG_MIVYBRIDGE
```
because you can't put a AMD Opteron/Athlon64 on a intel board

**Comment by ptr1337** [comment]
Hey @AldairbotHerotaku 

Thanks for your request. That would work for the processor - select and the configure script for it.
At the auto detect it would be a bit harder to add.

Does this change anything into compatibility ? If you remove the amd-ucode from your system it wont be loaded anyways.
Regards

**Comment by AldairbotHerotaku** [comment]
> Does this change anything into compatibility ? If you remove the amd-ucode from your system it wont be loaded anyways. Regards

I do not speak specifically about the microcode. I talk about loading, for example, the Conf_x86_AMD_platform_Device or rather known as AMD ACPI2PLATFORM Devices Support or in the Intel case the CONFIG_INTEL_IDLE (Cpuidle Driver for Intel Processors)  that is useless if you have an diferent cpu but it is compiled no matter if you use _localmodcfg =
And the only way to remove it would be manually doing it with _makenconfig in each new version of cachyos

There are no problems with compatibility, but it improves the start time a bit (almost invaluable 3 or 4 seconds)

**Comment by ptr1337** [comment]
> > Does this change anything into compatibility ? If you remove the amd-ucode from your system it wont be loaded anyways. Regards
> 
> I do not speak specifically about the microcode. I talk about loading, for example, the Conf_x86_AMD_platform_Device or rather known as AMD ACPI2PLATFORM Devices Support or in the Intel case the Intel Low Power Subsystem Support that is useless if you have an diferent cpu but it is compiled no matter if you use _localmodcfg = And the only way to remove it would be manually doing it with _makenconfig in each new version of cachyos
> 
> There are no problems with compatibility, but it improves the start time a bit (Almost unappreciable 3 or 4 seconds)

I dont really know how we should do this automatically without doing possible breaking from machines.
If you have a idea, feel free to PR it.
