### ISSUE TITLE
Package needs bump due to outdated checksum

### ISSUE THREAD

**Issue by xuanruiqi** [CachyOS/linux-cachyos#220]
```
Validating source files with b2sums...
    linux-6.7.1.tar.xz ... Passed
    config ... Passed
    auto-cpu-optimization.sh ... Passed
    0001-cachyos-base-all.patch ... Passed
    0001-sched-ext.patch ... Passed
    bore-tuning-sysctl.patch ... FAILED
```

**Comment by xuanruiqi** [comment]
Oh sorry, it's the linux-cachyos package!

**Comment by xuanruiqi** [comment]
but I'm guessing all packages that include this patch will need to be bumped

**Comment by sirlucjan** [comment]
As far as I can see, only linux-bore has this patch enabled by default. For the others, you have to update the checksums manually. What I noticed has been updated: https://github.com/CachyOS/linux-cachyos/commit/585f3bbff4bf1dd3927e3f0212d6df207b78e367
