### ISSUE TITLE
linux-cachyos-rc doesn't apply 0001-sched-ext.patch

### ISSUE THREAD

**Issue by kode54** [CachyOS/linux-cachyos#222]
The current release of the PKGBUILD as of 61e2f30833b4391a1d991cb38409a0af4ca214a0 does not apply this patch, so sched-ext doesn't get built into the kernel.

**Comment by ptr1337** [comment]
We will update it soon!

**Comment by ptr1337** [comment]
Should be good now, working on my side. sched-ext will be also again default included with rc2.
