### ISSUE TITLE
Mesa 1:24 update breaks my XWayland apps w/ CachyOS Kernel

### ISSUE THREAD

**Issue by tommy141x** [CachyOS/linux-cachyos#226]
Rocket League which runs through XWayland is super stuttery (unplayable) even tho the fps shows 600+
and other apps that run under XWayland are running with no errors but don't show a window (like Spotify or intellij idea or just a basic hello world electron app) 
Aside from XWayland, it also appeared the whole DE & some other apps had lower framerates or were performing worse.

## How I produced this problem:
```
[2024-02-17T14:00:39-0500] [ALPM] upgraded libva-mesa-driver (1:23.3.5-2 -> 1:24.0.1-1)
[2024-02-17T14:00:40-0500] [ALPM] upgraded mesa (1:23.3.5-2 -> 1:24.0.1-1)
```
As soon as I downgraded mesa from ``1:24.0.1-1`` to ``1:23.3.5-1`` the Spotify window appeared.

## My System Specs:
Kernel: 6.7.5-2-cachyos
OS: Arch Linux x86_64
DE: Gnome 45.4 (Wayland)
CPU: AMD Ryzen 9 3900x
GPU: NVIDIA GeForce RTX 4070Ti (Using Proprietary Drivers)

## What I have tested:
* Gnome 45.4 & Gnome 46.1 Beta w/ CachyOS kernel (Problem Persisted)
* Gnome 45.4 w/ Arch Kernel (No Issues, Unable to reproduce)

I also tried mesa-git, but I had the same issue, for now I have downgraded to 1:23.3 for mesa drivers.

**Comment by ptr1337** [comment]
Hi Tommy,

I will try to reproduce this. I have an equal setup (4070 Super, 7950X3D).
If it is happening with "mesa" then I guess this is an upstream issue since mesa is currently not shipped from our side.

Which Kernel version you had with the arch kernel?

**Comment by ptr1337** [comment]
I have tried to reproduce this issue on KDE 5.27.10, Wayland, xorg-xwayland (including explicit sync patches) and mesa 24 and cant reproduce this issue.
Im using the 550 drivers.

Played serveral rounds rocket league and no issues so far.

**Comment by tommy141x** [comment]
My arch kernel is ``6.7.5.arch1-1``, I am going to try the 550 drivers w/ the newer xorg that I believe you sent me earlier and test. If that does not work I will try to record or screenshare the issue.

**Comment by tommy141x** [comment]
The newer xorg-xwayland package with the sync patch still breaks gnome shell for me and I have to use the normal one to boot into gnome. I am still having the same issue with the mesa package even with 550 drivers. I have a little bit more testing to do on the Arch kernel side but that'll take a bit because I have some homework to do.

**Comment by tommy141x** [comment]
https://github.com/CachyOS/linux-cachyos/assets/57594516/c15cc974-0ab3-4be1-bf47-d841c274c435

**Comment by tommy141x** [comment]
Okay after installing nvidia-dkms seperately and using linux-cachyos instead of linux-cachyos-nvidia (so that I can have nvidia drivers for all my kernels) turns out this issue is reproducible on the regular Arch kernel.
