### ISSUE TITLE
6.7.x freezing first time akmod is running

### ISSUE THREAD

**Issue by msmafra** [CachyOS/linux-cachyos#231]
Hello there.

It's the 4th time I had it with kernel  6.7.x-cb after a new version is installed and I reboot, it hangs at the nvidia driver compilation/build/installation that is ran by akmod during boot. As the next boot everything is fine it seems to be freezing as soon as akmod finishes.

**Comment by ptr1337** [comment]
> Hello there.
> 
> It's the 4th time I had it with kernel 6.7.x-cb after a new version is installed and I reboot, it hangs at the nvidia driver compilation/build/installation that is ran by akmod during boot. As the next boot everything is fine it seems to be freezing as soon as akmod finishes.

Hi,

We really need logs for this. We dont have this issue currently on CachyOS or any arch linux distrubution, so I think this is probably some kind of bad interaction with akmods.

**Comment by msmafra** [comment]
[boot2051.log](https://github.com/CachyOS/linux-cachyos/files/14451357/boot2051.log)
[boot2048.log](https://github.com/CachyOS/linux-cachyos/files/14451358/boot2048.log)

**Comment by ptr1337** [comment]
@msmafra 
What I can see on 2048.log is following:
```
2024-02-28T20:50:06-0300 tars kernel: [drm:nv_drm_atomic_commit [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to apply atomic modeset.  Error code: -22
```
This seems to be an issue when "fbdev=1" is used in the nvidia driver and when the nvidia modules are not included into the initramfs.

Please change your dracut.conf (i think fedora uses dracut) to automatically include loaded modules and regenerate the images. That should help

**Comment by msmafra** [comment]
I forgot to mention that it happened once or twice with 6.6.x too.

These are my dracut and modprobe conf files as I dont use NVIDIA drivers from RPMFusion's those apply everything. I had no problems before.

```
❯ cat /etc/dracut.conf.d/nvidia-dracut.conf
add_drivers+=" nvidia nvidia_modeset nvidia_drm "
install_items+=" /etc/modprobe.d/nvidia-modeset.conf "

❯ cat /etc/dracut.conf.d/nvidia-force.conf
# https://wiki.archlinux.org/title/Dracut#Early_kernel_module_loading
force_drivers+=" nvidia nvidia_modeset nvidia_uvm nvidia_drm "

 ❯ cat /etc/modprobe.d/nvidia-modeset.conf
options nvidia-drm modeset=1 fbdev=1
#options nvidia NVreg_UsePageAttributeTable=1 NVreg_InitializeSystemMemoryAllocations=0 NVreg_DynamicPowerManagement=0x02
options nvidia NVreg_RegistryDwords="PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3"

❯ cat /etc/modprobe.d/nvidia-installer-disable-nouveau.conf
# generated by nvidia-installer
blacklist nouveau
options nouveau modeset=0
```

Coming to mind that I added changed some paramenters in /etc/modprobe.d/nvidia-modeset.conf for testing Hyprland, but just last week, which wouldn't affect previous ones.

**Comment by ptr1337** [comment]
We dont have this issue on CachyOS or archlinux at all, which is weird. My personal guess would be some kind of issue with akmods, when it does at booting compile the nvidia modules but they are not properly early loaded from the initramfs.

the configs are looking fine tho.

**Comment by msmafra** [comment]
I'll see if it happens with next version 550.54.14 will when available

**Comment by msmafra** [comment]
Hello there!

After the update to 550.54.14 it happened again, but at leas I discovered that it just don´t  keep booting into GDM. And if I do a Ctrl + Alt + Del it will, eventually, reboot. Takes some 40+ seconds, but it reboots. So, at least, I don't have to forcefully shut it down.
Today with the update to 6.7.9-cb1.0 it happened again and I decided to test with fedora default kernel (6.7.7-200) by uninstalling it; rebooting; installing it back; and rebooting. With Fedora's kernel the "freeze" during the "first" boot did not occure. Akmods ran and I got to GDM with no issues.
As it wasn't a thing that used to happen even with previous versions of Cachyos's  kernel, I'm lost.

**Comment by msmafra** [comment]
Could that be related to the same bug as is warned here?
```
Important Notice: Clang-compiled LTO Kernel Repository

This repository offers a kernel compiled with Clang and LTO (Link-Time Optimization). It's crucial to note that enabling this repository may disrupt AKMODs functionality on kernels compiled with GCC, such as the stock Fedora kernel or kernel-cachyos (non-LTO).

Please be aware that if you activate this repository, akmods modules may not work correctly on GCC-compiled kernels.
```
From **https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/**

I don't use the LTO COPR, I use this one https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos

**Comment by ptr1337** [comment]
> Could that be related to the same bug as is warned here?
> 
> ```
> Important Notice: Clang-compiled LTO Kernel Repository
> 
> This repository offers a kernel compiled with Clang and LTO (Link-Time Optimization). It's crucial to note that enabling this repository may disrupt AKMODs functionality on kernels compiled with GCC, such as the stock Fedora kernel or kernel-cachyos (non-LTO).
> 
> Please be aware that if you activate this repository, akmods modules may not work correctly on GCC-compiled kernels.
> ```
> 
> From **https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/**
> 
> I don't use the LTO COPR, I use this one https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos

I dont know, where this is coming from. I think it would be the best to ask in discord the fedora maintainers.
Or you should switch to precompiled nvidia modules/dkms, and avoid using akmods.

**Comment by msmafra** [comment]
> > Could that be related to the same bug as is warned here?
> > ```
> > Important Notice: Clang-compiled LTO Kernel Repository
> > 
> > This repository offers a kernel compiled with Clang and LTO (Link-Time Optimization). It's crucial to note that enabling this repository may disrupt AKMODs functionality on kernels compiled with GCC, such as the stock Fedora kernel or kernel-cachyos (non-LTO).
> > 
> > Please be aware that if you activate this repository, akmods modules may not work correctly on GCC-compiled kernels.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From **https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/**
> > I don't use the LTO COPR, I use this one https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos
> 
> I dont know, where this is coming from. I think it would be the best to ask in discord the fedora maintainers. Or you should switch to precompiled nvidia modules/dkms, and avoid using akmods.
I never used DKMS. I'll try to switch

**Comment by msmafra** [comment]
With the last 2 updates 6.8.2 and 6.8.3 it also froze using DKMS. And at least with 6.8.3, it did not allow me to turn off by pressing the power button and restart with Ctrl + Alt + Del. Maybe it should've waited more, with akmods it took kind of a minute to do, but this last time with DKMS it was more.

**Comment by msmafra** [comment]
> > Could that be related to the same bug as is warned here?
> > ```
> > Important Notice: Clang-compiled LTO Kernel Repository
> > 
> > This repository offers a kernel compiled with Clang and LTO (Link-Time Optimization). It's crucial to note that enabling this repository may disrupt AKMODs functionality on kernels compiled with GCC, such as the stock Fedora kernel or kernel-cachyos (non-LTO).
> > 
> > Please be aware that if you activate this repository, akmods modules may not work correctly on GCC-compiled kernels.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From **https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/**
> > I don't use the LTO COPR, I use this one https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos
> 
> I dont know, where this is coming from. I think it would be the best to ask in discord the fedora maintainers. Or you should switch to precompiled nvidia modules/dkms, and avoid using akmods.

My intention here was ask if some code or some paramenter from the LTO one was by mistake used on the "Normal" kernel too.
