### ISSUE TITLE
"does not have a valid architecture - linux-cachyos-eevdf"

### ISSUE THREAD

**Issue by euandreesteves** [CachyOS/linux-cachyos#233]
`[god@god ~]$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra                                                                                 8.4 MiB  17.8 MiB/s 00:00 [###################################################################] 100%
 multilib is up to date
 cachyos-v3 is up to date
 cachyos-core-v3 is up to date
 cachyos-extra-v3 is up to date
 cachyos                                                                             411.3 KiB   249 KiB/s 00:02 [###################################################################] 100%
:: Starting full system upgrade...
error: failed to prepare transaction (package architecture is not valid)
:: package linux-cachyos-eevdf-6.7.9-1-x86_64_v3 does not have a valid architecture
:: package linux-cachyos-eevdf-headers-6.7.9-1-x86_64_v3 does not have a valid architecture`

**Comment by ptr1337** [comment]
Please follow the CachyOS repo add instruction correctly.
You need to use our provided pacman or manually modify the Architecture = auto to Architecture = x86_64 x86_64_v3

**Comment by 103sbavert** [comment]
https://wiki.cachyos.org/features/optimized_repos/

I fail to see where this is ever mentioned on this page. I may be mistaken, please guide me.

**Comment by 1Naim** [comment]
https://wiki.cachyos.org/features/optimized_repos/#adding-our-repositories-to-an-existing-arch-linux-install

> Installing the CachyOS Pacman will install a forked pacman with features added from CachyOS, like “INSTALLED_FROM” and an **automatic architecture check**

**Comment by 103sbavert** [comment]
Hmmm I don't see any mentions of modifying the pacman.conf's architecture option

**Comment by 1Naim** [comment]
It doesn't have to be modified if you're running CachyOS's pacman.

**Comment by gwuen** [comment]
> It doesn't have to be modified if you're running CachyOS's pacman.

The note in the Wiki regarding Pacman continues as follows:

> Pacman 6.1 added a feature validation feature, which could lead when using the Arch Linux pacman into warnings. [...] If you want to avoid this, don’t add the “cachyos” repository, which contains the customized pacman. All other repositories like cachyos-v3, cachyos-v4, cachyos-extra/core-v3/4 are safe to add.

This suggests you can use the custom repos without the customized Pacman. The additional config that is necessary is not mentioned anywhere on this page. Not a major problem, but I think the documentation is lacking in this regard.

Thank you for maintaining the optimized repos, though!

**Comment by vnepogodin** [comment]
If you are not using our pacman, you are required to edit /etc/pacman.conf to include valid arches instead of auto

**Comment by gwuen** [comment]
> If you are not using our pacman, you are required to edit /etc/pacman.conf to include valid arches instead of auto

Thanks, I'm already aware of this, my comment was just referring to this not being mentioned anywhere on the [Wiki page for custom repos](https://wiki.cachyos.org/features/optimized_repos/) :)

**Comment by dataprolet** [comment]
I had the same issue and found this thread. I'm with @103sbavert and @gwuen that this should be mentioned in the wiki. If it's a valid usecase to use CachyOS's repositories  without it's version of pacman than this should sufficiently documented.

**Comment by gwuen** [comment]
Apparently, it's not a “valid use case”:

> It is not really something we do want to support, since there are quite a bunch of pacman features we do relay on.
>
> We know that few enhanced users utilizing it on their own with blocking our pacman, but it often results into not wanted issues and therefore should be not noted in the wiki

Am I the only one who interprets the Wiki as suggesting that not using the custom Pacman is a “safe” option? But considering that's not the case, I'm strongly for removing or rephrasing this note.

**Comment by cldylan** [comment]
> Am I the only one who interprets the Wiki as suggesting that not using the custom Pacman is a “safe” option? But considering that's not the case, I'm strongly for removing or rephrasing this note.

I agree, I found it quite confusing as I interpreted it as not installing their pacman being the "safer" option. I also ended up finding this thread and modifying `/etc/pacman.conf` but I feel like this could be a bit clearer. Regardless, thanks for all the work!
