### ISSUE TITLE
wiped boot parameters

### ISSUE THREAD

**Issue by dnodno** [CachyOS/linux-cachyos#234]
Hi could you make it so that boot parameters are not wiped after each pacman kernel update

**Comment by dnodno** [comment]
I am using systemd-boot btw, not sure if grub has this issue

**Comment by sirlucjan** [comment]
You've to configure this file: https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/systemd-boot-manager/sdboot-manage.conf

You've to add parametrs here https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/systemd-boot-manager/sdboot-manage.conf#L4 or disable this option: https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/systemd-boot-manager/sdboot-manage.conf#L38
