### ISSUE TITLE
error on hp 1620 4 core

### ISSUE THREAD

**Issue by pro9code** [CachyOS/linux-cachyos#235]
https://gist.github.com/pro9code/c5c93f1830928b862c572909afaf6040

**Comment by pro9code** [comment]
https://gist.github.com/pro9code/c5c93f1830928b862c572909afaf6040

**Comment by ptr1337** [comment]
> https://gist.github.com/pro9code/c5c93f1830928b862c572909afaf6040

It seems like you have selected multiple Desktop Envrioments. Please use only one.
