### ISSUE TITLE
Bad performance with the new 6.8.1-2 eevdf kernel

### ISSUE THREAD

**Issue by ShadowFlarer** [CachyOS/linux-cachyos#236]
Just want to report this, the new version 6.8.1-2 introduced a performance issue, the entire system is very slow from boot to something like gaming, i rolled back to version 6.8.1-1 and everything returned to normal, tried to install the 6.8.1-2 version 3 times and all 3 i had performance issues.

I use Nvidia and i'm using the new driver 550.67, in my first try using the new kernel i was on the 550.54.14 driver and the problem persisted, my CPU is a Ryzen 5 5600 so it's zen 3.

**Comment by ptr1337** [comment]
> Just want to report this, the new version 6.8.1-2 introduced a performance issue, the entire system is very slow from boot to something like gaming, i rolled back to version 6.8.1-1 and everything returned to normal, tried to install the 6.8.1-2 version 3 times and all 3 i had performance issues.
> 
> I use Nvidia and i'm using the new driver 550.67, in my first try using the new kernel i was on the 550.54.14 driver and the problem persisted, my CPU is a Ryzen 5 5600 so it's zen 3.

This could be an regression in the amd-pstate update.
Which cpu scaling driver you are using?

**Comment by ShadowFlarer** [comment]
> > Just want to report this, the new version 6.8.1-2 introduced a performance issue, the entire system is very slow from boot to something like gaming, i rolled back to version 6.8.1-1 and everything returned to normal, tried to install the 6.8.1-2 version 3 times and all 3 i had performance issues.
> > I use Nvidia and i'm using the new driver 550.67, in my first try using the new kernel i was on the 550.54.14 driver and the problem persisted, my CPU is a Ryzen 5 5600 so it's zen 3.
> 
> This could be an regression in the amd-pstate update. Which cpu scaling driver you are using?

Yes i'm using amd-pstate, only that one actually.

**Comment by ptr1337** [comment]
> > > Just want to report this, the new version 6.8.1-2 introduced a performance issue, the entire system is very slow from boot to something like gaming, i rolled back to version 6.8.1-1 and everything returned to normal, tried to install the 6.8.1-2 version 3 times and all 3 i had performance issues.
> > > I use Nvidia and i'm using the new driver 550.67, in my first try using the new kernel i was on the 550.54.14 driver and the problem persisted, my CPU is a Ryzen 5 5600 so it's zen 3.
> > 
> > 
> > This could be an regression in the amd-pstate update. Which cpu scaling driver you are using?
> 
> Yes i'm using amd-pstate, only that one actually.

Which mode? Active, passive or guided?

**Comment by ptr1337** [comment]
Please give me also an output of sudo cpupower frequency-info

**Comment by ShadowFlarer** [comment]
Yep is on active.

Here is the frequency info (some parts are in portuguese, sorry about that):

  driver: amd-pstate-epp
  CPUs que rodam na mesma frequência de hardware: 9
  CPUs que precisam ter suas frequências coordenadas por software: 9
  maior latência de transição:  Cannot determine or is not supported.
  limites do hardware: 550 MHz - 4.47 GHz
  reguladores do cpufreq disponíveis: performance powersave
  política de frequência atual deve estar entre 550 MHz e 4.47 GHz.
                  O regulador "performance" deve decidir qual velocidade usar
                  dentro desse limite.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 4.26 GHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes
    AMD PSTATE Highest Performance: 166. Maximum Frequency: 4.47 GHz.
    AMD PSTATE Nominal Performance: 130. Nominal Frequency: 3.50 GHz.
    AMD PSTATE Lowest Non-linear Performance: 65. Lowest Non-linear Frequency: 1.75 GHz.
    AMD PSTATE Lowest Performance: 21. Lowest Frequency: 550 MHz.

Weirdly enough is sayng amd-pstate-epp even though i don't have that enabled.

Also, if helps i'm on Gnome and my energy options is on performance.

**Comment by ptr1337** [comment]
cc @superm1

Short info:
amd-pstate/pref-core got updated to the latest revision, user on zen3 is facing issues with performance.
Downgrading to previous revision does fix the performance issue
Here you can find the diff of the patch:
https://github.com/CachyOS/linux/commit/8775385d1f22fde8242514a2b921b120d27344ca

@ShadowFlarer We will try to reproduce on other users machine

**Comment by superm1** [comment]
Can you please respond to the mailing list submission?

I'm currently OOO, so this will be the best way to get feedback to the submitter.

**Comment by kmate95** [comment]
amd_pstate crashes on boot and falls back to acpi-cpufreq on ZEN2  Ryzen 9 3900X
 Arch Linux version 6.8.1-2-cachyos (linux-cachyos@cachyos) (clang version 17.0.6, LLD 17.0.6)  SMP PREEMPT_DYNAMIC Tue, 19 Mar 2024 
```
Mar 20 12:48:32 kernel: processor cpu0: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: fbcon: Taking over console
  Mar 20 12:48:32 kernel: processor cpu1: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu2: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu3: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu4: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu5: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu6: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu7: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu8: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu9: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu10: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu11: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu12: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu13: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu14: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu15: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu16: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu17: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu18: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu19: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu20: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu21: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: processor cpu22: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: ata6: SATA link up 6.0 Gbps (SStatus 133 SControl 300)
  Mar 20 12:48:32 kernel: processor cpu23: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
  Mar 20 12:48:32 kernel: amd_pstate: failed to register with return -19
```
Seems to miss a "* 10" somewhere...

**Comment by ptr1337** [comment]
> amd_pstate crashes on boot and falls back to acpi-cpufreq on ZEN2 Ryzen 9 3900X Arch Linux version 6.8.1-2-cachyos (linux-cachyos@cachyos) (clang version 17.0.6, LLD 17.0.6) SMP PREEMPT_DYNAMIC Tue, 19 Mar 2024
> 
> ```
> Mar 20 12:48:32 kernel: processor cpu0: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: fbcon: Taking over console
>   Mar 20 12:48:32 kernel: processor cpu1: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu2: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu3: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu4: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu5: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu6: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu7: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu8: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu9: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu10: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu11: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu12: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu13: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu14: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu15: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu16: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu17: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu18: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu19: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu20: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu21: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: processor cpu22: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: ata6: SATA link up 6.0 Gbps (SStatus 133 SControl 300)
>   Mar 20 12:48:32 kernel: processor cpu23: min_freq(550000) or max_freq(478995) or nominal_freq (3801000) value is incorrect
>   Mar 20 12:48:32 kernel: amd_pstate: failed to register with return -19
> ```
> 
> Seems to miss a "* 10" somewhere... EDIT: fails with every combination of amd_pstate=* and amd_prefcore=disable kernel parameters

Thanks, I see the issue. Ill revert the recent changes then for now.

**Comment by ptr1337** [comment]
Recompile is running https://github.com/CachyOS/linux-cachyos/commit/a226edb9dfde883bbf480650e11c6a7d3d29f826

It should be available in around 1-2 hours for the v3 repository.
