### ISSUE TITLE
fastsync

### ISSUE THREAD

**Issue by dnodno** [CachyOS/linux-cachyos#239]
when will fastsync support be added to proton-cachyos? at the moment it only works with proton-8-cachyos

**Comment by ptr1337** [comment]
Its already available in proton-cachyos

**Comment by dnodno** [comment]
proton log i get "fastsync: /dev/winesync not available. (Please check winesync module)" when using PROTON_USE_WINESYNC=1 launch option, but don't have this issue with proton-8-cachyos

**Comment by ptr1337** [comment]
> proton log i get "fastsync: /dev/winesync not available. (Please check winesync module)" when using PROTON_USE_WINESYNC=1 launch option, but don't have this issue with proton-8-cachyos

Please update proton-cachyos to the latest version.
Ive tested it locally together with "winesync-dkms winesync-header winesync-udev-rule" and it does launch fastsync correctly.

**Comment by dnodno** [comment]
i forgot that i was using Nobara kernel, fastsync is working fine with linux-cachyos/proton-cachyos

**Comment by dnodno** [comment]
please reconsider adding the pollrate patch that Nobara uses it would save so much pain

**Comment by ptr1337** [comment]
> please reconsider adding the pollrate patch that Nobara uses it would save so much pain

Please open a seperate issue for this to discuss there.
