### ISSUE TITLE
Issues installing cachyos-bore with paru

### ISSUE THREAD

**Issue by LethalManBoob** [CachyOS/linux-cachyos#24]
**First is the error i get when i attempt to install both the base and headers**

2 aur/linux-cachyos-bore-headers 5.19.0-2 [+1 ~0.01]
    Headers and scripts for building modules for the Linux BORE scheduler Kernel by CachyOS with 
    other patches and improvements kernel
1 aur/linux-cachyos-bore 5.19.0-2 [+1 ~0.01]
    The Linux BORE scheduler Kernel by CachyOS with other patches and improvements kernel and 
    modules
:: Packages to install (eg: 1 2 3, 1-3):
:: 1 2
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) linux-cachyos-bore-5.19.0-2 (linux-cachyos-bore linux-cachyos-bore-headers)

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
error: File exists (os error 17)

**Then the error i get when i attempt to install one or the other**

2 aur/linux-cachyos-bore-headers 5.19.0-2 [+1 ~0.01]
    Headers and scripts for building modules for the Linux BORE scheduler Kernel by CachyOS with 
    other patches and improvements kernel
1 aur/linux-cachyos-bore 5.19.0-2 [+1 ~0.01]
    The Linux BORE scheduler Kernel by CachyOS with other patches and improvements kernel and 
    modules
:: Packages to install (eg: 1 2 3, 1-3):
:: 1
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) linux-cachyos-bore-5.19.0-2

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
:: Accept changes? [Y/n]: y
fetching devel info...
==> Making package: linux-cachyos-bore 5.19.0-2 (Mon 08 Aug 2022 17:10:36 BST)
==> Retrieving sources...
  -> Found linux-5.19.tar.xz
  -> Found config
  -> Found auto-cpu-optimization.sh
  -> Found 0001-cachyos-base-all.patch
  -> Found 0001-bore.patch
==> Validating source files with sha256sums...
    linux-5.19.tar.xz ... Passed
    config ... FAILED
    auto-cpu-optimization.sh ... Passed
    0001-cachyos-base-all.patch ... FAILED
    0001-bore.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'linux-cachyos-bore-5.19.0-2': 
error: packages failed to build: linux-cachyos-bore-5.19.0-2

**Comment by sirlucjan** [comment]
```lucjan at archlinux ~/Pobrane 18:47:55    
❯ export LANG=C
lucjan at archlinux ~/Pobrane 18:47:56    
❯ git cl aur:linux-cachyos-bore                         
Cloning into 'linux-cachyos-bore'...
remote: Enumerating objects: 383, done.
remote: Counting objects: 100% (383/383), done.
remote: Compressing objects: 100% (354/354), done.
remote: Total 383 (delta 192), reused 209 (delta 29), pack-reused 0
Receiving objects: 100% (383/383), 407.67 KiB | 2.43 MiB/s, done.
Resolving deltas: 100% (192/192), done.
lucjan at archlinux ~/Pobrane 18:48:01    
❯ cd linux-cachyos-bore        
lucjan at archlinux ~/Pobrane/linux-cachyos-bore 18:48:03 cc7ea01c master    
❯ makepkg -srd --sign
==> Making package: linux-cachyos-bore 5.19.0-2 (pon, 8 sie 2022, 18:48:08)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Downloading linux-5.19.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  125M  100  125M    0     0  32.5M      0  0:00:03  0:00:03 --:--:-- 32.5M
  -> Found config
  -> Found auto-cpu-optimization.sh
  -> Downloading 0001-cachyos-base-all.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1710k  100 1710k    0     0  2886k      0 --:--:-- --:--:-- --:--:-- 2889k
  -> Downloading 0001-bore.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8262  100  8262    0     0  19432      0 --:--:-- --:--:-- --:--:-- 19394
==> Validating source files with sha256sums...
    linux-5.19.tar.xz ... Passed
    config ... Passed
    auto-cpu-optimization.sh ... Passed
    0001-cachyos-base-all.patch ... Passed
    0001-bore.patch ... Passed
==> Extracting sources...
  -> Extracting linux-5.19.tar.xz with bsdtar```

Checksums are correct now.

**Comment by ptr1337** [comment]
Was my bad. But in general please dont use paru really for building kernels from the aur. We had already really really weird issue's which where just based on paru. Kinda insane.

Also you can customize a lot of things to your suits in the PKGBUILD, so a 
```
paru -G linux-cachyos-bore
cd linux-cachyos-bore
makepkg -si
```
is in most cases better, then to use paru

Thanks for your report
