### ISSUE TITLE
Fan control not working properly on asus laptops.

### ISSUE THREAD

**Issue by merrkry** [CachyOS/linux-cachyos#243]
[asusctl](https://gitlab.com/asus-linux/asusctl) has a feature that allow the user to set custom fan curves on asus laptops. This feature works with official linux kernels (stable, zen and 6.6 lts kernels are tested), when both custom gpu and cpu fan curves are enabled.

On cachyos kernels (`6.8.6-1-cachyos-bore`):

- sensors have no reading under `asus-isa-0000`, both cpu and gpu fan readings are 0.
- gpu fan stopped, when enabling custom cpu fan. (checked physically)

System info and Logs can be found [here](https://gitlab.com/asus-linux/asusctl/-/issues/478) (not a relevant issue tho).

Asusctl side says it's not their problem. Considering that `asusctl` is in official cachyos repo, i am here.

I want to know if cachyos make any patches on asus or fan control stuffs?

**Comment by ptr1337** [comment]
Could you please retest on 6.9?

Personally I suspect that maybe the deckify branch is causing that, but please check with 6.9 and let us know.

**Comment by merrkry** [comment]
> Could you please retest on 6.9?您能在 6.9 上重新测试吗？

I was on 6.8.9 and found this problem disappeared. After upgrading to 6.9 it works as well. I think this issue can be closed.
