### ISSUE TITLE
Add LAVD Kernel Scheduler

### ISSUE THREAD

**Issue by ajdgsu** [CachyOS/linux-cachyos#245]
Just noticed that a new gaming specific scheduler cames out, and the performance looks pretty promising: https://www.phoronix.com/news/LAVD-Scheduler-Linux-Gaming

**Comment by ptr1337** [comment]
Thats already included in the default kernel since several month with the sched-ext framework.
Just install "scx-scheds" and then run "sudo scx_lavd" and it will run the lavd scheduler
