### ISSUE TITLE
Proposal: Incorporate Patches to Revert AMDGPU Lower Power Limits Enforcement from Linux 6.7

### ISSUE THREAD

**Issue by rsrmean** [CachyOS/linux-cachyos#246]
Hello,

since Linux 6.7, [the AMDGPU driver has been changed](https://www.phoronix.com/news/AMDGPU-Lower-Power-Limit) in a way that a lower power limit set by the graphics card BIOS is being enforced, preventing users from setting power limits below this threshold.

Note that this is **not** about surpassing the upper power limit, but about power saving.

[ZEN applied](https://github.com/zen-kernel/zen-kernel/issues/344) a [patch](https://gitlab.freedesktop.org/drm/amd/uploads/4af61751f8fa08340990b48824e4f9c5/amdgpu-ignore-min-pcap.patch) for solving this. They also enforce using a kernel boot parameter for enabling the lower power limit.

It would be nice if this could be incorporated in CachyOS kernels.

**Comment by ptr1337** [comment]
This is already applied
