### ISSUE TITLE
[AMD] PState Zen 2 not working

### ISSUE THREAD

**Issue by ptr1337** [CachyOS/linux-cachyos#247]
Hi @superm1

as discussed in the E-Mail, ill just create a issue here to have better tracking.

Current State:
1. 6.9 Kernel without amd-pstate patches --> working

2. 6.9 Kernel with latest amd-pstate cpb boost & amd-pstate fixes and enhancements v12 --> not working https://paste.cachyos.org/p/b6dddae --> Patches: https://github.com/CachyOS/linux/commits/6.9/amd-pstate/

3. Kernel with v10 amd-pstate fixes and enhancements --> not working (due wrongly reported freq issue) --> https://paste.cachyos.org/p/c480247 , this was also reported here: https://github.com/CachyOS/linux-cachyos/issues/236 and fixed with newer versions

We will attach the dynamic debug as soon as possible from a clean v12 build and from a non patched kernel.

**Comment by superm1** [comment]
Dyndbg for this file too please; https://git.kernel.org/pub/scm/linux/kernel/git/rafael/linux-pm.git/tree/drivers/acpi/cppc_acpi.c?h=bleeding-edge#n1250

**Comment by ptr1337** [comment]
@superm1

Sorry for the noise. It seems its not this patchset, which is affected.
the latest cpb-boost and amd-pstate-fixes v12 are fine.

We have additional commits in, which where picked from the "linux-pf" kernel (https://codeberg.org/pf-kernel/linux)

Following commits:
https://github.com/CachyOS/linux/commit/de0fc04c2d548054d1ad8a34e9c40b602afea942 - (probably not the breaker)
https://github.com/CachyOS/linux/commit/829b315ae075a527b78ad98334cf0dfac45d88a5 - (probably not the breaker)
https://github.com/CachyOS/linux/commit/b870a22229d98665ddc1d87c2d431094df10397e - (probably the breaker)
https://github.com/CachyOS/linux/commit/8fd0d0ab03b51b0e9e07f24de30746dfe34d7847 - (probably the breaker)

So, its just questionable, why this issue was not visible on Zen3 or Zen4.

**Comment by superm1** [comment]
> https://github.com/CachyOS/linux/commit/de0fc04c2d548054d1ad8a34e9c40b602afea942 - (probably not the breaker)
> https://github.com/CachyOS/linux/commit/829b315ae075a527b78ad98334cf0dfac45d88a5 - (probably not the breaker)

Agree; probably not the cause, those are headed to 6.10 as well.

> https://github.com/CachyOS/linux/commit/b870a22229d98665ddc1d87c2d431094df10397e - (probably the breaker)

This was never merged and so it's not getting good testing coverage, I think you should drop it.  
https://lore.kernel.org/linux-pm/20240227071133.3405003-1-li.meng@amd.com/

> https://github.com/CachyOS/linux/commit/8fd0d0ab03b51b0e9e07f24de30746dfe34d7847 - (probably the breaker)

This is the wrong fix for this problem, please drop it.  The _correct_ fix should be submitted soon ™.

**Comment by ptr1337** [comment]
> This is the wrong fix for this problem, please drop it. The correct fix should be submitted soon ™.

This would be very important to some of our users, since several people reported issues with it and this was also the reason, why we have pulled it in the past.

> This was never merged and so it's not getting good testing coverage, I think you should drop it.
Thanks, we will drop it and keep the patches from amd-pstate (next).

Sorry for the noise again and thanks for helping.

**Comment by ptr1337** [comment]
FYI @pfactum ,

You should consider to drop the above 2 patches from your tree, it breaks amd-pstate on some CPUs.

**Comment by pfactum** [comment]
These:

```
$ git log --oneline amd-pstate-6.8~2..amd-pstate-6.8
2031648ce0d3f Revert "amd_pstate: fix erroneous highest_perf value on some CPUs"
8deec09d7de89 Revert "cpufreq/amd-pstate: fix setting policy current frequency value"
```

?

**Comment by ptr1337** [comment]
> These:
> 
> ```
> $ git log --oneline amd-pstate-6.8~2..amd-pstate-6.8
> 2031648ce0d3f Revert "amd_pstate: fix erroneous highest_perf value on some CPUs"
> 8deec09d7de89 Revert "cpufreq/amd-pstate: fix setting policy current frequency value"
> ```
> 
> ?

Yes, these reverts you should apply to your branch.

**Comment by pfactum** [comment]
Done then, thanks.
