### ISSUE TITLE
Kernel landlock message on the logs

### ISSUE THREAD

**Issue by msmafra** [CachyOS/linux-cachyos#249]
Hello there!

I'm on 6.9.0-cb1.0.fc40.x86_64 and getting this message on the logs. What does it mean?

![Captura de tela de 2024-05-16 10-49-53](https://github.com/CachyOS/linux-cachyos/assets/1005457/14f80806-e47b-4c54-a2ae-1c6ed084b175)

```
❯ uname -a
Linux tars 6.9.0-cb1.0.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May 13 17:59:23 UTC 2024 x86_64 GNU/Linux

❯ dmesg | grep landlock || journalctl -kb -g landlock
dmesg: read kernel buffer failed: Operação não permitida
mai 16 10:23:17 tars kernel: landlock: Disabled but requested by user space. You should enable Landlock at boot time: https://docs.kernel.org/userspace-api/landlock.html#boot-time-configuration

❯ zgrep -h "^CONFIG_LSM=" "/boot/config-$(uname -r)" /proc/config.gz 2>/dev/null
CONFIG_LSM="“lockdown,yama,integrity,selinux,bpf,landlock”"
CONFIG_LSM="“lockdown,yama,integrity,selinux,bpf,landlock”"
```

**Comment by ptr1337** [comment]
Hi,

related to our config has nothing changed.
Either its an upstream issue or the config from fedora maintainer.

The config variable above loocks fine (e.G LSM). You should maybe check if  LANDLOCK_SECURITY is set
