### ISSUE TITLE
hardware accelerated video playback is broken on 5.19.2 and 5.19.3

### ISSUE THREAD

**Issue by lavilao** [CachyOS/linux-cachyos#25]
Hi, first of all thank you for your amazing work, I just compiled linux-bore 5.19.3 (previously 5.19.2, same behavior) and everytime I try to play a video on mpv with hardware acceleration the gpu hangs. I use an intel n3050 with intel hd 400 graphics on manjaro. Do you know what could it be causing this? is it fixable or is a bug that can only be fixed upstream? thanks in advice

**Comment by sirlucjan** [comment]
First of all - did you use your own config or did you use the default one? Did you check if this problem occurs on another scheduler? Did you check if the same thing happens on kernel 5.19 with Manjaro?

**Comment by ptr1337** [comment]
> Hi, first of all thank you for your amazing work, I just compiled linux-bore 5.19.3 (previously 5.19.2, same behavior) and everytime I try to play a video on mpv with hardware acceleration the gpu hangs. I use an intel n3050 with intel hd 400 graphics on manjaro. Do you know what could it be causing this? is it fixable or is a bug that can only be fixed upstream? thanks in advice

Hey!

Thanks for the report.

Do you can reproduce this issue on the default kernel (5.19.2 / 5.19.3) from manjaro/arch?
Would be good to know.

Regards

**Comment by lavilao** [comment]
yes it seems to be reproduceable
https://www.reddit.com/r/archlinux/comments/wriv5k/video_playback_is_broken_on_linux_5192_and/

**Comment by sirlucjan** [comment]
Have you checked if this problem also occurs on the kernel from Manjaro?

**Comment by lavilao** [comment]
also here https://www.reddit.com/r/archlinux/comments/wuvmr1/kernel_5193arch11_issue/ the user LuisBelloR (not the OP) seems to have the same issue

**Comment by lavilao** [comment]
@sirlucjan no I have not, will try now

**Comment by lavilao** [comment]
It also happens on manjaros kernel, also theirs is 5.19.1

**Comment by SM9CC** [comment]
If its a kernel issue, you should raise it here: https://bugzilla.kernel.org/

**Comment by lavilao** [comment]
Thanks, did not knew that was the site for kernel bugs

**Comment by ptr1337** [comment]
There are some updates in 5.19.4 with the intel drm driver. But im unsure if it fixes your problem.

you could download from our mirrors a 6.0 rc kernel. May it is there fixed.

**Comment by lavilao** [comment]
links to the mirrors?

**Comment by sirlucjan** [comment]
https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/cachyos-mirrorlist/cachyos-mirrorlist

https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/cachyos-v3-mirrorlist/cachyos-v3-mirrorlist

**Comment by lavilao** [comment]
Downloaded and tested linux-cachyos-rc-6.0... still has the problem. Can't compile 5.19.4, it takes 3 hours and power is unstable

**Comment by sirlucjan** [comment]
So you should reported bug in upstream.

**Comment by ptr1337** [comment]
> Downloaded and tested linux-cachyos-rc-6.0... still has the problem. Can't compile 5.19.4, it takes 3 hours and power is unstable

Our buildserver should be done with the next hours. Then you can find the kernels there :)

**Comment by lavilao** [comment]
@ptr1337 time to wait then

**Comment by lavilao** [comment]
Tested 5.19.4, still broken. It seems I Will have to wait until 6.x so I Will not bother You guys anymore, thank You for your time and help provided.
