### ISSUE TITLE
Network connection issues

### ISSUE THREAD

**Issue by lil0programmer** [CachyOS/linux-cachyos#255]
I regularly get timed out from my connection & I get reported from the wifi manager "connectivity limited", this gets fixed when I manually disconect fromthe network & reconect to it. Tell me what logs or info should I share, because I'm quite lost.

**Comment by ptr1337** [comment]
Hi,

Is this reproduceable on other kernels? Does this issue exists on the LTS kernel?

**Comment by lil0programmer** [comment]
> Hi,
> 
> Is this reproduceable on other kernels? Does this issue exists on the LTS kernel?

Hi ptr, i haven't tried other kernels, but I will do.. what kernel version would be appropriate?

**Comment by ptr1337** [comment]
> > Hi,
> > Is this reproduceable on other kernels? Does this issue exists on the LTS kernel?
> 
> Hi ptr, i haven't tried other kernels, but I will do.. what kernel version would be appropriate?

Please try sudo pacman -S linux-cachyos-lts linux-cachyos-lts-headers

**Comment by ptr1337** [comment]
Reopen if this is still an issue.

**Comment by lil0programmer** [comment]
Hi Peter this is still an issue, I'll do what you stated before.

**Comment by ptr1337** [comment]
> Hi Peter this is still an issue, I'll do what you stated before.

How about LTS kernels?

**Comment by lil0programmer** [comment]
You mean "sudo pacman -S linux-cachyos-lts linux-cachyos-lts-headers" ? I don't think they solved the issue succesfully

**Comment by ventureoo** [comment]
We're not changing anything in network stuff except for BBR3 patch. You can try disabling it via:
```
sudo sysctl -w net.ipv4.tcp_congestion_control=cubic
```
But it looks more like an upstream issue with the our network driver or your setup.
