### ISSUE TITLE
proton-cachyos: low frame rate with PROTON_ENABLE_WAYLAND=1 on wayland

### ISSUE THREAD

**Issue by dnodno** [CachyOS/linux-cachyos#256]
unable to hit frame limit (500fps) in Rocket League with PROTON_ENABLE_WAYLAND=1 
frame rate is between 170 and 180 with this setting enabled
disabled is solid 500 fps

**Comment by dnodno** [comment]
I should also mention it's not syncing behavior as the monitor refresh rate is 144 hz

**Comment by Pogogo007** [comment]
This is known. WINE's wayland driver is quite new and experimental

**Comment by dougg0k** [comment]
In RDR2, PROTON_ENABLE_WAYLAND=1 caused input to not work / register in-game.

**Comment by ptr1337** [comment]
> In RDR2, PROTON_ENABLE_WAYLAND=1 caused input to not work / register in-game.

Yeah, we will need to wait for Proton 10.
