### ISSUE TITLE
Linux-Cachyos-Hardened kernel gets error when building

### ISSUE THREAD

**Issue by EricLin0509** [CachyOS/linux-cachyos#279]
I want to build a custom cachyos kernel for my system, but it gets error when building. Here is the log:

>   CC [M]  arch/x86/crypto/crc32-pclmul.mod.o
ld.lld: error: undefined symbol: proc_dointvec_minmax_sysadmin
>>> referenced by usercopy_64.c
>>>               vmlinux.o:(printk_sysctls.llvm.11678322890589939808)
>>> referenced by usercopy_64.c
>>>               vmlinux.o:(printk_sysctls.llvm.11678322890589939808)
>>> referenced by usercopy_64.c
>>>               vmlinux.o:(inodes_sysctls)
>>> referenced 2 more times

**Comment by ptr1337** [comment]
We already noticed. Looking into.
