### ISSUE TITLE
Kernel repo producing unusuable kernels

### ISSUE THREAD

**Issue by LethalManBoob** [CachyOS/linux-cachyos#28]
[kernel]
SigLevel = Optional TrustAll
Server = https://repo.blacksky3.com/$arch/$repo

That is the repo im using and this is my download. I am using the one labeled "kernel". not "chaotic-aur".
![Screenshot from 2022-09-10 11-32-22](https://user-images.githubusercontent.com/30273211/189479447-842a6c96-14f8-481f-9750-5359a02d1ccf.png)

However i cannot boot with it. I tried both bore and cacule-rdb. both had same result. sticking on initializing graphical interface and soft locking. 
[log.txt](https://github.com/CachyOS/linux-cachyos/files/9540100/log.txt)

**Comment by ptr1337** [comment]
Huh? That seems odd to me?

We DON'T host this repo! Its actually not our kernel repo and seems like someone providing/using our Kernel.

**Comment by ptr1337** [comment]
Just a question - Where did you found this repo?

**Comment by ptr1337** [comment]
Anyways, in the readme or here you can find our Kernels which are compiled in a chroot and two different march's.
In x86-64-v3 GCC, LTO x86-64-v3, LTO x86-64, x86-64 GCC.

https://wiki.cachyos.org/en/home/Repo

**Comment by sirlucjan** [comment]
That isn't CachyOS repo. Please report bug to proper maintainer.

**Comment by LethalManBoob** [comment]
> That isn't CachyOS repo. Please report bug to proper maintainer. @blacksky3

Alright. I got confused because there was no "linux-bore" kernel on blacksky3's repos.

**Comment by ptr1337** [comment]
> > That isn't CachyOS repo. Please report bug to proper maintainer. @blacksky3
> 
> Alright. I got confused because there was no "linux-bore" kernel on blacksky3's repos.

Well, I would also think that he provide the Kernels from the AUR and not a own one.
Feel free to test our Kernel :)

**Comment by LethalManBoob** [comment]
> > > That isn't CachyOS repo. Please report bug to proper maintainer. @blacksky3
> > 
> > 
> > Alright. I got confused because there was no "linux-bore" kernel on blacksky3's repos.
> 
> Well, I would also think that he provide the Kernels from the AUR and not a own one. Feel free to test our Kernel :)

I tried the cachyos-bore from chaotic-aur and it works fine. just the blacksky version is broke.

**Comment by ptr1337** [comment]
Well, I'll close here.
Better use the Kernel's maintained from us, which are really well tested from us and many users.
