### ISSUE TITLE
CachyOS + Hyprland fresh install login issues

### ISSUE THREAD

**Issue by frankhuurman** [CachyOS/linux-cachyos#282]
Yesterday I installed CachyOS(July ISO) and Hyprland through the CachyOS installer but I ran into some issues which I think are Hyprland issues but thought I'd mention it anyway in case I'm overlooking a simple fix.
I'm on a Acer aspire i5 5200u laptop, 8 GBs of RAM, sata SSD in it, HD Graphics 5500 iGPU.

Steps that I did:
After the fresh installation I boot to a SDDM login screen but can't seem to login with the user that I set up during installation. The user is selected and Hyprland is the only DE option in the dropdown top-left.
After I put in my password and press enter it turns my cursor into a cross and it flashes the screen for a second and I'm back to an empty/fresh SDDM login screen again.

When I switch to a TTY I can actually login with the same credentials but when I try to run Hyprland I get this error:
Hyprland: symbol lookup error: Hyprland: undefined symbol: _ZNK9Hyprutils4Math4CBox6extentEv

Feel free to close the issue if it's something Hyprland should fix but would love to know if I'm missing something from the CachyOS side or if there's a simple fix available. I can imagine it's just Hyprland being unstable for now.

Thanks in advance!

**Comment by ptr1337** [comment]
Should be fixed already. Arch had a mismatch due the hyprutils additon.

**Comment by frankhuurman** [comment]
Thanks for the quick reply, closing and trying a reinstall tomorrow :)
