### ISSUE TITLE
AMD RYZEN 5 2500U kernel is configured as ZEN3 instead of ZEN

### ISSUE THREAD

**Issue by hifi25nl** [CachyOS/linux-cachyos#30]
In AMD RYZEN 5 2500U kernel is configured as ZEN3 instead of ZEN:
Strangely the auto-cpu-optimization.sh is giving MARCH=ZNVER1 instead of ZEN

**Comment by ptr1337** [comment]
> In AMD RYZEN 5 2500U kernel is configured as ZEN3 instead of ZEN: Strangely the auto-cpu-optimization.sh is giving MARCH=ZNVER1 instead of ZEN

Can you give me your output of:
`gcc -Q -march=native --help=target|grep march=|awk '{print $2}'|head -1`

Normally it should set it correctly:
https://github.com/CachyOS/linux-cachyos/blob/master/linux-bore/auto-cpu-optimization.sh#L4

**Comment by ptr1337** [comment]
I see, I found the issue thanks

**Comment by hifi25nl** [comment]
Yes that fixed it, thanks
