### ISSUE TITLE
Rebooting with linux-cachyos kernel skips grub

### ISSUE THREAD

**Issue by dfd** [CachyOS/linux-cachyos#307]
Every time I try to reboot (from either kde or hyprland), using the linux-cachyos kernel, the following happens:

1.  Prompts me for my encryption key, which I enter
2.  After unlocking, it shows a splash screen with the OEM logo and the CachyOS logo (I normally see this after the grub menu, but grub isn't shown after reboot)
3.  Monitors go into power saving mode
4.  I have to press the power button for a hard shut down

Also, I'm on a dual boot desktop with  Intel Core i7-14700 (16+12) @ 5.40 GHz.

It's happened to me every time I've rebooted since I installed CachyOS 6 weeks ago (so I think it applies to at least 6.10 as well), but never happens on cold boots.

I also tested with the cachy-lts kernel and it did not have the issue.

I captured logs with `sudo journalctl -b -1`, but there are 2089 lines just from the reboot to the hard shut down.

Are there certain parts of the log you need to help diagnose?  Is there something you'd like me to grep first?

**Comment by 1Naim** [comment]
Can you please test with Arch's kernel? `sudo pacman -S linux linux-headers`

**Comment by dfd** [comment]
Good idea.  I tried with the arch kernel and had the same problem, so I guess the problem is upstream.

**Comment by 1Naim** [comment]
Is this still the case with 6.11.2? There were 700 commits added on top of 6.11.1 so it might have been fixed.

**Comment by dfd** [comment]
Yes, I tested with Linux 6.11.2-3-cachyos and still did not reboot properly.

**Comment by 1Naim** [comment]
What's the output of `cat /proc/cmdline`. Would be nice to see if it differs between this and the LTS kern that you have if there are any.

**Comment by dfd** [comment]
I just checked, and there's no difference in `/proc/cmdline` for the `linux-cachyos` and `linux-cachyos-lts` cases other than the `BOOT_IMAGE`.

In both cases, it looks like this:
```
BOOT_IMAGE=/@/boot/vmlinuz-linux-cachyos root=UUID=35c44ea6-a221-4561-8c80-25548a5207e7 rw rootflags=subvol=@ nowatchdog nvme_load=YES zswap.enabled=0 splash cryptdevice=UUID=7b78fee5-5d66-4c56-a274-fb8b3fe202dd:luks-7b78fee5-5d66-4c56-a274-fb8b3fe202dd root=/dev/mapper/luks-7b78fee5-5d66-4c56-a274-fb8b3fe202dd splash loglevel=3
```

There are two `root`s defined.  Maybe that's a problem?  Although I'm not sure why it would be OK for the lts and not OK for the latest.

**Comment by 1Naim** [comment]
> There are two `root`s defined. Maybe that's a problem

That shouldn't be an issue. Next can you send me a copy of your grub config? You can send it via `paste-cachyos /etc/default/grub`. You can upload the contents of the file manually if it doesn't upload from the terminal. Thanks!

**Comment by dfd** [comment]
OK, I think it uploaded, but the output in the terminal isn't clear.

**Comment by ptr1337** [comment]
You need to paste it here

**Comment by dfd** [comment]
OK, I'll paste, although it just looks like a bunch of javascript and html to me.

**Comment by dfd** [comment]
`https://paste.cachyos.org<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}.main-content{margin:8rem auto;max-width:60rem;padding-left:1.5rem}@media (width <= 720px){.main-content{margin-top:4rem}}.h2{font-size:1.5rem;font-weight:500;line-height:2.25rem}@media (width <= 720px){.h2{font-size:1.25rem;line-height:1.5rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);background-repeat:no-repeat;background-size:contain;padding-left:34px}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "paste.cachyos.org",cType: 'managed',cNounce: '13593',cRay: '8d0b3d7a8e4957cc',cHash: '2270be6dff9d45b',cH: 'wPvuZsZCmkhWT7fqMGIfMX.X19TwMYnnnaHXdDGR6Zw-1728611854-1.1.1.1-vXAbz6WLXWIuwB1s5P_7mDl0IItngA2A1vu1BkWPJXY7BTEQMJxlj8pmiDLn5I.N',cUPMDTk: "\/?__cf_chl_tk=6_AdXFPIUVKhpXmaVJ5Pt2rZvoFKgGfgncWf6lEHCis-1728611854-1.0.1.1-jB2sTa24D0kDomudU1kzJcCnf1sFCFCLD1DyS4RLyLc",cFPWv: 'b',cITimeS: '1728611854',cTTimeMs: '1000',cMTimeMs: '390000',cTplV: 5,cTplB: 'cf',cK: "",fa: "\/?__cf_chl_f_tk=6_AdXFPIUVKhpXmaVJ5Pt2rZvoFKgGfgncWf6lEHCis-1728611854-1.0.1.1-jB2sTa24D0kDomudU1kzJcCnf1sFCFCLD1DyS4RLyLc",md: "AtvUCTemdJHNXHZq3ca.qBEyXr_GW7EfEaUKvsz.GKQ-1728611854-1.1.1.1-llzRnWiZzNIzxdsbMqQwHt_coYVfNWbh2cdLdkIP1GFpl2wt5kChmKo3k6YOQ9dngjDTOIbEPs9WMUjL.bfdW5uL1sHWm02Tr27rKebmKBSw6K.23PDpq0BLJv0rvYNvsryr9sDfpEP_1yJIM6WJdJPJqGCyRpAGwzZz6M_cevkch.PySH1ReIv_o4NXWfLLizlUpjxizu9PuuFe3X9oVUfwLBWr7UXu6DYE0_ok7.BLIV3olPze2Kg4xWXLcv2yRcMxz40migpsbiXw1p0dclKsf63RN2_dH32wpMgM7iPbX5eaWlkBOyCT6OzlfTFKkfwxdiKqE1RirrkYFP6EeaXuvwrw6y6ueFhGKrSZf14l9cTTZ1g.B31ytwF_W06nJtikvoV.1fw5Xb8E925.841uG4BetRs8Nqd5v6dWIsGmCXQ0mFpBy5rYKNctvEUCka_bO7ZbmKI9784I0T4Fqr_uhBQ9ANIDRdtc8yDAuNGHGb5pzj852Vo5RmggL35f4PB8nS.MdAJlZlmBz7i1Q.aBikhYC_70YKBE0NDBMePjPdTj0e7KtmPOGvC8aLKydkEff3ah9GAsiQ9loDPrIMG8suw7nfLtnQvrbG2rsew_3FLJyKk_kIXR5tSL4r.M2egyieBBFcqkuVIx.3kTBR5Qxxly7WBZcoB7PGQLdmbafr9KIJ5P4GI1kLwp2mfDKKd.8_smQxQ3UqqIiRam1GB0Yxh_aPddyAuc3Fj2aemMsGQHOBf_gAX7mlv7Vg2SgDd70d2hAzZasp9BFbONI2eQXXX5Z5ipfRF2ZM6oBRezBHgQmtqW3ICoA5CbD3OsV3gDBudQ.MbhxqtOHF9ZqqHPlY4KwwJW0QLywhY3annc0wl__hBeS1tNx8.uVQgN8ka2FNOPpVrnxg8l8pOsSNrg8nsD69C7wuY9WJWfFZ6NpYdDQm8uAvuiu8annBDp.qskCY_vLDhWo5sb5vL.NsKQcYaVYHx13JBk4Th8X_wD431azd2l8n._plqcNY.9FJTtS0kR1sHldgo0R82wBtWBnWABDBzbI8uReTzW8PJzJI5kHdgJcoalqAcqmyu7AX7ImLHx1BcDexHRPJq1a5olQs_OAvTmGnF.RXygznzoWIB_khxkn2WoT.K0sKbdSN88SYLWNvsml..1z8rjP_bYqZLVgEceiWhjRDGokRCbcMwKKbKWt9onAlJY5E7jS7wu0owJG5QdRj.WSFKJ1JJjqjzSsaBUWZ7sRMGPZTanluld4dS5gDuapnos0b8MmDHSygtVV2PuoKIElom_5KQ98imWbI.ceSTpcSgZY.sXyGiT9FhvZ1_WraLrR.gqC8pUZvjyfzC0Dsj.ZJjKkucJqRP5KReOnOJdjdxAFwYHY.BhsjspXwIczADwPRN7PDA6TAjeN.ll7wQ_DBGgngPni0zMy3tF4r3Bhf2ZaQaRs.5bxim0qIwg6BMsRgtB_mFmQ9Q0KNZ7HgpAELRdH4QNRLu1ZwJhEdHI4VKX_ce_Kj.lXOXHQ7JvsyjjEgsbNxbufyCUnl8l6HcUMn0OjDB2gbK3BMJkaQAqN5Ea.MYJzZs8nJoQtsEaCbpW_XR299xBsRqz83U2c45S9Oans5Y0XpmErfDLljnx0Uml.KF5BWXtLm.aTOLRDIlpDM1cuUxjrpvXnqecR7Nxfx.vKlQKO7Q9c1q0uU6J1r4jImTTrKZWh8RE2lBKadCelCfzPypmWUvqrKtyiEYXWif4decmdPsujhq5zzg0641UWMq2h9FnkWnz0JAzl0tLoItCSbn948RBjCAjiIG1uBWNU33rA7.hpE1nXztijzYc1dleOOVxIX1vQcMbxqxzC0H8ccokAf88rS4_EVSfvff6.CDt1x6ySLKHSzv3XWuY.wXaC6IarLIwqw9r17QjN1QONDO_a5r7jAbQMeeJpXBU2bbnyXBlx9NYaPX_XHOoIxj.k1J8sFebn4_QGx7rYSyTElyG6JrsS48oHIr9L_SzGY34e5jeoM7kH7oDKbueMyuuwday5cTZNGrrsMzukjqQwQ1kepc1gpgGPB11EuOZFpRYOX0Ofy1EejhpJatBmCNkoWWbqrUHCnmIhlfEnVTgkqVRPHjOdLblEq8ok3z9jIwcS39NXLp79FwTgitV727lv8uXUGV07ljrsEUyFhAFElvIdfIG5Ffl9Ok_c6dp2Y6PwCtB00Wd442otX5o1rtAUN9WAaOJrIrAqS3T7b2ARcswUUdPFq0wPdePbzDyEWKN5kgRfWS_AQn_2UirhX8",mdrd: "tbkfpQtKWRbeNvATLQ942wKbXyT9EiCx45lXsk5973s-1728611854-1.1.1.1-XfHqylWeY9UWwh6XtaVb.6ZvkVoRra.8YFAJlbmPgMOvlPhHZchDamOVDfmH5JpGB5cQiQvX7X1zkUecEj7pcsetpAZX73m8gVSEmGezKMxL6AvRirKxEbWS8SG2K8H.xTsv8ZhitoXDAgCC0Q8sQoD8MxzfR5.gbTs6FWBHjDDEBCMA6ep7_dBP2C6UrFBhjHnI.Ltosu1v_Eub70rvW5CpGgqOZT.rv34sOlCAZQvefDgNdtRYie9VmC8cVEQWf_CdTwjmMSL0lphItJ1hmL1XXfWobZhg6psAiiDJJNW7s1OpI5SvbHhW5xlKdhJp4fUcgVlZGtija24WbSdczk0L7VEig4pfyWJ_U5Ab24Fho7hCWD2f21faZ08TMPkLsnO0EalS5qxIDv6kWdPXZGd2FoKWWIqiXvLu_VsW6WtIAAbmKnPMjNr_uGzMaEKT8__ddJ2zOZEOd5CUF99voC9fDofzkqAFjwaI9aoHpc0Md6FeQ4my5QWiGcy5njwWDy6Im29qe_pfC8mQjJoqjyp0X8wok_1prHWBHDvR.Yjv3JQoe6zDrctrK8cGMLs1XAeMzNQ6Jt4JSydq4B1XPjJ_UlLnbzcb1lIIm5s_Sgu4RAJ3dbQ7qW648u0IM5KqezH3ZxYWRrTpFQTJ3i0lr31lxYD0CFZRzXm0NVv81tSUI_eicgu3PKug1Aw8cNsbrsU1pO4TxC_Q7X.SyFDZIcxzruBN3K.tvh.a8W7jG.O3dfOWO.jXC3jRlPsTrz3Wm3bt.OyZTIVtF8532ajW5ElrJ8Cq3MiRqY9zRUEbS9rhyT2SrezOKTVRClDyn9XeVSzMmSoVi3KaAcuEgSSPWbjfIuXeR72oyvjNalzDfAp8Nq3O3JsR8nAduM6dvYuXX4kq5yudQaBd3eddOW2dEdIHWfM3g_HpBrm69fHRIJg8EBmi1MLuLhwFM3rOZ8R9JcUki4L3Wfber086GEqpZ18xdvG6RSGHkOg33bBdlWtTCxsUIjSgXlofP34KQ5boAD7SmsuGkRG0xWwkDAA9AR5kMLwq.FxZoPFuXNjZqkGq4iEhm2QDxpWnVa2S6i0sR.u9WALL3uei.oycNid5lSUQZlDP19OG9l1D1qpQ.oNLSzqlzXkvgDrCdgdxyNuwItYPoge6AzbuSEEINjEZODGAweljg4rlow5n2VgsBunuDCSyjd30NS_RaFCKZaZfIpHyYPRFMaT9nP2aa1JfGLNg65x0XeUK6vPfUxMgu_NKDKDdb4Phoru9c5GAX9ZBcUH_lWDS92i9tu6fGWuH6_UKIG8TI_moY_6xlZwZl.3bEEOLOrwvGsy4gvzmn4CS51.wDiYKZIhv7UyJKYwATTBR_wLA0miI0j8_X0EJIv6CdVu.d8wwjNevTEGei99YndyfdtaQoI67uaHVsYZc3iiq.MeinTuw4vY6bi4FQesCzUvLGnk7YXjNzU0_cAu9OUmstCOfr36I6mJlkyn_iyL8jhewzNpJVFMTCIqVnAn16X1rmwbjolVSQW.aGGLdAxPkolJBthoSp6dEdFZU7p1cog7e77x0XsPbumwRr0tC19D12vWavBTzcijxJHeAxmCDrjzqaQHYG3ckQMg_Bw7qrxfHDAeLMJqjepKZcDdZZrnoCNp7lh6L8KTZSeHBMk0DYEGkJXjV0OIg8reS0xxD6qMLcjjOEjR0MZASbQYUQsMtkr1.FntHhNph5k4ws69vY4HDZ.Dx7iIyBnwMLi3RAQobKeACV59S1YaoceR6_AlHtTZiX7OR1XYbqA_WWFJ930Tej4VgVnnp_B4oUVC34dBwe5_bMQkOkfKFEfgaMRhCHN_3zAl78aBaxZvzw6T.m26wVGYUs2BM8jglfRgrlh9jj3_uTiYCCmCaoKx8Bi5slY6BRFwZudTEnbpt8pmgMcc2l3tCLvvT0Ac2SurmziJqBB3GDOTAVRL.n55zj2h7eWDh_MDIzAci0Fzu5M8co6HcMctTZ7u12QKVQf_WSnHEDBOKNA3AHNea8QuHCU.u.KBqYFyXm8MRIe7w1Fq_92Wn.9aT7wstCjJgTvSWfO2oMij4rdeTy7_U4Ka06y68PPhHji4xe3jHiowoqUepHwZek9zrTaFH5Ibeps_xyDrmtMHq6l4V.Ti.CSwOzeQaMpsnDGWRIUrSCiMEadbrP3DZ7NPABharl.E0sGF7gApjRPdofr30NMRn4WcdO2gE2j_MDIfw74JWwwk1aO.RdA1jqcylNyfGv4PiYmnPBgSKKY4Ckl30DI5YsXWGyfcbpn_wny8Gfn3Ul8Zjm8QQHtf9kHadKjMWRxWomP8XUuP5tgCFqgmqWLuGDZqS61gGRmZoxFzjGBRnA_9tCoGgO3__WSjEfNdDGfdkDORfApEWHs2DC2zu.8WwXoQiMW2WWlwOXw5ZFYfVXAURApi11d9mUiJVu.SznJDVIvQpVqnW5BYyKWVev72nlopPzB.zNRTe9EIQVUsYEmtMugEY0HBCykOgQd14FWxj8DFjbXan2Chr7laSKRq1H4TS4ujcZ.DVhIsZY7zbYZ6YmOLFW43VtCOEovHRUW.Pd_luA8pbjg9h3hXL7SB82VXXC8QHZrmekEKb.VW7X7bBSKTYcR3N2l6tP_GoRPgNT8k0hhsw20zE9mim3YzE2jOPtBqXSX96CBZ0yM4ohNTM0PBihjij2WGCi_d9Lk7YNzlcGM5Wo_7A6gLl8I4fVItNNIeMDj0wwLaj7EbBuaI7cpqaiQm2qSUa.RZU7lDyDDQgSu.iGbG_S2dIzlMpVp3G4eyuulmP7Ayd.CmpMabWuBAhYDoN6Z9VuAdFA5n0JEv5Th7mfotkzelMyLrOmy0cdI1SXYute50mF6cbMXX7uVZJ01ce2R8k5BQLcAFGxCBcFlykazhOm9Ofr3NI0KwT4UEnsnD4uO_jYVYAdlM.V47D1oUHFmkyufjU.fY2xSUrhLiOoqbNqIUfg31S4vKpkWOAbAh0qKGBYTlTyHZXCOFsqMYOmfvGsJh.8mdE_1Wqobg7GLS8Ra0pIL.R05iOZwVU1srcRkUyOxSUI8RyFx753nRQSC.Oj9rbbABrUVRNfCWy.GLAh4nj0LYwVg19pye7qMgEYkAeX.ht_bbYkxIlyO5hgkPRIpNmSIb56KMa3b3GoorwOFIZA0CHLCwbbAyy3c1pjB5ma13J5DSZzciwuNNsMo_gWtUFmshpJjpdzNmfUPZeE.3okNp75.CfULESKNaxcgxw6LrVh05ZLGTbYW2IcAnXPLILtyre2JVVyOuglUnWJTg2CgSjmwem5.1ZC61VBNux25.9eBx2rhQz1gFWyrDO0d5nnwokk.CsqfRqdLuPVr4B4zwZX9wtcnZMj9fpOjFE7TG2PrZpsH8LqQfE2VFLImQy3HGvTaIC5bP2kLonZzDoI2PHn3puqYkFfVJNxrDdF3RoPamUtDp.uUMH_bzKLUaxRYVtLK2r46DPunJE8JaUA.TBsS7ic6awrxvfLnVsVKblkBehLunyTuUiF72nhI0rjTKPg4gDVFaRpplj6P1pwvWswgZGbP3z7x28BKEOl9AuDXU6v.9tdVQxqDc9HhdrmekhKPaErCbSIY7edVrr9utqFxttEikS65D2l49zQudzzno_cnS3APPmkCnCTgWVQnmeAMPdaJk10WGWqvIZRV1FQWN.OdMb3BUDNtthZZURZTHN2ClwprbN3rtcYUTDFIuNfygbj7mERcqNor2nzRl5yhdmE8HqqVrBbu.D6nJI0uHunilufxjz_MFt7X19Uv7IfkjwiKJT7Polcviu9P1IOtjTlM78cf2SnlvhKfHepO3m15QTSw1dnh7kh9WOJl3bYa01axRGvPZfhRkFLKus9JyY9ZZlATGC1U1N4NYa2zGoNAr.hPfqHNtwqEwI3QIwgQ",cRq: {ru: 'aHR0cHM6Ly9wYXN0ZS5jYWNoeW9zLm9yZw==',ra: 'Y3VybC84LjEwLjE=',d: 'k8BWEE6QkvXVdc/WFSIgKfoNscb2JMD9883ztRaY5XAk1EpA5sguIq0//GpwaTUahrFYkI3551LJ48dhHOuO4ansKe/SSGrjRseHMZi6zJqDQGqbXingYK9gC5VMh7C+Inp8/kFK1JK/gTCi0ajnvbFdX5oM0ZTigIN0hoqwc7XO/iiMkMzEf15r+fwuRdVdE6/n/92UlQ+cLaA/X8c0Xn+9cFojogjoTsEJe9fQvkAlngPbjyNmHq6jCc16ssYTFTI5mgWip+4uunqN6yzYUZKLjpc7OERd+fyPcjjJoOduS69S8Oe3Lb0cxEgEcMsHqXssnYm7+tOqbnDbyw6ylRboeVmBY4NQYTv71EJ/SpfQSB8Vz0C+mfwAU1AMc2X9GLWPuj7mQV333FzsEJYCEU2o7woxCMp3zm+SjaGvtG94Bi4gKeu+dNKWqC8HbL2PAqc5EKoqnDbkjWn4VZo/vn/1Q989zK79upuRYvyznYEckMROp2v0E2dgIQW6Fq3b0SrABCdqu2jc+0JW5P8uB1dyH2AotlTHKlAsiO8QS0/exC0CUCB6kikh8CG0u+/V9b8KKTD1CnzR4TS7PEZ03A==',t: 'MTcyODYxMTg1NC4wMDAwMDA=',cT: Math.floor(Date.now() / 1000),m: 'dUmGG6CKUM3dqLElhENdOh53qK6n+Mpjlyx7VscT5cU=',i1: 'O2yksse3jQv2fnZZpzaOQA==',i2: 'mKIyUwMVF01/Qxo7nPC/2w==',zh: 'qqjdLGCnLv8j4KJv78ApV8hnnf7xVM3KasQ0MIrcy2g=',uh: '0XYbRJCypaszpbgjT8qp/T2oYAsL1LgJ7UfSYh6uaoM=',hh: '03oqJz1gCX2VQ8aTtelcvmkn0jjci1DQat3qICChPZ4=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8d0b3d7a8e4957cc';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/?__cf_chl_rt_tk=6_AdXFPIUVKhpXmaVJ5Pt2rZvoFKgGfgncWf6lEHCis-1728611854-1.0.1.1-jB2sTa24D0kDomudU1kzJcCnf1sFCFCLD1DyS4RLyLc" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>.grub`

**Comment by 1Naim** [comment]
Yes this was a failed paste. Please upload the contents of the file manually to https://paste.cachyos.org

**Comment by dfd** [comment]
Here it is:
https://paste.cachyos.org/p/f5c29a9.txt

**Comment by 1Naim** [comment]
Sorry for the late reply, I keep forgetting to reply here even though I've seen that link 3 times now.

Nothing seems to be wrong there as far as I can see. Can you check if `linux-cachyos-hardened` exhibits this issue? That kernel is still on 6.10.10 and it'll help to confirm when the commit that brought this change started.

**Comment by dfd** [comment]
`linux-cachyos-hardened` also skips over grub on reboot for me.

**Comment by 1Naim** [comment]
Can you try this old 6.9.9 kernel next?

```sh
sudo pacman -U https://archive.cachyos.org/archive/cachyos-v3/linux-cachyos-echo-6.9.9-3-x86_64_v3.pkg.tar.zst https://archive.cachyos.org/archive/cachyos-v3/linux-cachyos-echo-headers-6.9.9-3-x86_64_v3.pkg.tar.zst
```

Below is also an older version of the hardened kernel

```sh
sudo pacman -U https://archive.cachyos.org/archive/cachyos-v3/linux-cachyos-hardened-6.10.6-2-x86_64_v3.pkg.tar.zst https://archive.cachyos.org/archive/cachyos-v3/linux-cachyos-hardened-headers-6.10.6-2-x86_64_v3.pkg.tar.zst
```

**Comment by 1Naim** [comment]
Can you also attach a video of the this happening?

**Comment by dfd** [comment]
Here is a video of a reboot.  Hard to get good quality.

https://github.com/user-attachments/assets/b91f12d3-2a29-4924-ab81-f4a3a9fab32a

**Comment by 1Naim** [comment]
Can you try increasing the the GRUB menu timeout in `/etc/default/grub` to something like 10 or 30.  I really can't find an explanation for this other than [a year old reddit post that experienced the same thing](https://www.reddit.com/r/archlinux/comments/183gq6t/for_some_reason_grub_randomly_decides_to_skip_the/).

**Comment by dfd** [comment]
6.9.9 kernel also does not reboot properly.  That reddit post does not sound like my issue, because mine does not properly boot into anything after skipping grub.  But I'll try increasing the timeout now just in case.

**Comment by dfd** [comment]
Extending the grub timeout did not fix it.

**Comment by 1Naim** [comment]
Okay to finalize this, can you confirm that this **doesn't** happen for both `linux-cachyos-lts` and `linux-lts` from Arch?

**Comment by dfd** [comment]
This is strange, but `linux-cachyos-lts` no longer reboots correctly for me.  Something else that has changed is that I can't log into it from sddm with KDE Wayland (it gave me a blank screen); I had to use Xorg.  I know it rebooted OK for me when I tested it last week, but for some reason is also skipping grub now.

Whenever I try to install the `linux-lts` kernel, the kernel manager just closes on me.

**Comment by dfd** [comment]
@nutcasewtf
Yes, both systems in the dual boot use gpt.

I tried changing to 
```
GRUB_PRELOAD_MODULES="part_gpt"
```
but that did not solve it.

Hooks:
```
HOOKS=(base udev autodetect microcode kms modconf block keyboard keymap consolefont plymouth encrypt filesystems grub-btrfs-overlayfs)
```

I have no external hard drives plugged in when it happens.
I also do not see any fast boot options in the bios settings.

I don't see a setting on the monitors for DDC/CI.  Running `sudo ddcutil detect` shows a Phantom Display, in addition to my two monitors.  The Phantom Display shares the serial number of the 1st display.

**Comment by dfd** [comment]
Removing `grub-btrfs-overlayfs` did not fix it.

I also tried removing the splashes from `GRUB_CMDLINE_LINUX_DEFAULT` and adding `plymouth.enable=0 disablehooks=plymouth` but that still skipped grub on reboot.

**Comment by dfd** [comment]
Is there something to look for in the logs to see what’s different between a cold boot and restart?

**Comment by 1Naim** [comment]
> Is there something to look for in the logs to see what’s different between a cold boot and restart?

I don't think there will anything in logs, but you can post it here for what it's worth.

In any case, this is becoming more and more evident that it is not a kernel bug but something that lies elsewhere. Is your BIOS up-to-date? I would suggest updating it if it's not just to get rid off some firmware bugs that might have crept in.

**Comment by dfd** [comment]
I've been keeping my BIOS up to date.
When I have time this week, I'll look at logs from cold boot vs reboot and post if anything looks different.

**Comment by dfd** [comment]
I'm not totally sure what's going on, but I think it's some sort of display issue that only happens on reboots.  I'm getting logs that look very similar to successful cold boots, but I don't get the display for grub or sddm.  Strangely I do get the display for the splash page between them.

**Comment by dfd** [comment]
I found a difference in the logs to support the idea that there's a display issue on the reboot.

In the cold boot, where it works properly, there are lines:

`sddm-greeter[1214]: Adding view for "DP-4-2" QRect(0,0 3840x2160)`

and

`sddm-greeter[1214]: Adding view for "DP-4-3" QRect(3840,0 3840x2160)`

in the reboot it just says:
`sddm-greeter[1201]: Adding view for ":0.0" QRect(0,0 640x480)`

I'm not sure if it's a similar issue for grub, since I don't see logs for it.
I'll try changing the loglevel for grub and see if that shows me more.

**Comment by dfd** [comment]
OK, I think I figured this out.  It appears to be due to using an MST Hub Splitter from the iGPU display port to the two monitors, although I'm not sure why it only seems to be affected by reboots; maybe something to do with the timing and recognition of displays.

With this MST Hub Splitter set up I see a phantom display, which may be causing the issue:
```
❯ sudo ddcutil detect
[sudo] password for dave: 
Phantom display
   Associated non-phantom display: bus /dev/i2c-15
   I2C bus:  /dev/i2c-14
   DRM connector:           card1-DP-4
   EDID synopsis:
      Mfg id:               GSM - Goldstar Company Ltd (LG)
      Model:                LG Ultra HD
      Product code:         23305  (0x5b09)
      Serial number:        
      Binary serial number: 00000 (0x00000000)
      Manufacture year:     2019,  Week: 8
   DDC communication failed
   Use non-phantom device bus /dev/i2c-15

Display 1
   I2C bus:  /dev/i2c-15
   DRM connector:           card1-DP-6
   EDID synopsis:
      Mfg id:               GSM - Goldstar Company Ltd (LG)
      Model:                LG Ultra HD
      Product code:         23305  (0x5b09)
      Serial number:        
      Binary serial number: 00000 (0x00000000)
      Manufacture year:     2019,  Week: 8
   VCP version:         2.1

Display 2
   I2C bus:  /dev/i2c-16
   DRM connector:           card1-DP-7
   EDID synopsis:
      Mfg id:               GSM - Goldstar Company Ltd (LG)
      Model:                LG Ultra HD
      Product code:         23305  (0x5b09)
      Serial number:        
      Binary serial number: 00001 (0x00000001)
      Manufacture year:     2019,  Week: 8
   VCP version:         2.1
```

If instead, I run the DisplayPort connections directly from the dGPU, the problem goes away on reboots, and I see this, without the phantom display:
```
❯ sudo ddcutil detect
[sudo] password for dave: 
Display 1
   I2C bus:  /dev/i2c-2
   DRM connector:           card0-DP-1
   EDID synopsis:
      Mfg id:               GSM - Goldstar Company Ltd (LG)
      Model:                LG Ultra HD
      Product code:         23305  (0x5b09)
      Serial number:        
      Binary serial number: 00000 (0x00000000)
      Manufacture year:     2019,  Week: 8
   VCP version:         2.1

Display 2
   I2C bus:  /dev/i2c-3
   DRM connector:           card0-DP-2
   EDID synopsis:
      Mfg id:               GSM - Goldstar Company Ltd (LG)
      Model:                LG Ultra HD
      Product code:         23305  (0x5b09)
      Serial number:        
      Binary serial number: 00001 (0x00000001)
      Manufacture year:     2019,  Week: 8
   VCP version:         2.1
```

In any case, it appears to not be a kernel issue, so I will close.  Thanks for the help!
