### ISSUE TITLE
Can't get nvidia-dkms-open to compile

### ISSUE THREAD

**Issue by xuanruiqi** [CachyOS/linux-cachyos#308]
I've confirmed that I'm installing the latest nvidia-dkms-open with CachyOS patches, which does have [this](https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/master/nvidia/nvidia-open-dkms/0004-6.11-Add-fix-for-fbdev.patch) patch, but I keep getting the error:

```
ERROR: modpost: "drm_fbdev_ttm_setup" [/var/lib/dkms/nvidia/560.35.03/build/kernel-open/nvidia-drm.ko] undefined!
```

How is this possible? Is this something due to erroneous configuration of my built Linux kernel?

**Comment by ptr1337** [comment]
Mhm, thats weird. Which kernel version youre running?

Im using nvidia-open-dkms from our repository and its working fine.

**Comment by xuanruiqi** [comment]
I'm running 6.11.2. Tried clearing my ccache and still the same happens

**Comment by ptr1337** [comment]
Can you try with a non modprobe kernel?

**Comment by xuanruiqi** [comment]
It compiles with other kernel headers (e.g., stock arch kernel) without trouble

**Comment by ptr1337** [comment]
> It compiles with other kernel headers (e.g., stock arch kernel) without trouble

Then I would suspect the stripped config, no?

**Comment by xuanruiqi** [comment]
Let me check!

**Comment by ptr1337** [comment]
Just built the latest one from the CachyOS-PKGBUILDs (since its not in repo yet) but it worked fine:

![image](https://github.com/user-attachments/assets/a1c6182e-d963-46cb-a0d7-45b6754f48ca)

**Comment by xuanruiqi** [comment]
Cleared ccache, recompiled my kernel, now everything's working. Really weird, must be some strange ccache bug or config bug.
