### ISSUE TITLE
kwin_wayland_drm: Pageflip timed out! This is a kernel bug

### ISSUE THREAD

**Issue by xd003** [CachyOS/linux-cachyos#321]
The system freezed totally while i just watching a video on youtube. I didn't waited long enough to see if it would recover. I had to force reboot after around 15-20 seoconds

I am attaching the output of `journalctl -b -1` with this post
[previous_boot.log](https://github.com/user-attachments/files/17613515/previous_boot.log)

![image](https://github.com/user-attachments/assets/20dce7fd-e15c-47fd-8099-5d74c22c0d19)

**Comment by ptr1337** [comment]
Mhm, we are not modifying the GPU Driver, specially on intel. Ive checked the kde tracker, and you can find several such reports.

Can you check, if this is happening on the 6.12 Kernel?

**Comment by xd003** [comment]
I am guessing you mean the cachyos os kernel v6.12 itself, how do i rollback to this kernel version & prevent it from automatically upgrading on a system upgrade ?

**Comment by 1Naim** [comment]
Check if this issue is present in the rc kernel.

```sh
sudo pacman -S linux-cachyos-rc linux-cachyos-rc-headers
```

**Comment by xd003** [comment]
I have switched to the rc kernel, i will report back if the issue happens again

**Comment by zono50** [comment]
i'm getting this error too, and had to hard reset my system to get it to come back up. TTY did not work. Happened in both autofdo and linux-cachyos

**Comment by 3DMicks** [comment]
I can also confirm that both `linux-cachyos 6.11.7` and `linux-cachyos-lts 6.6.60` have this issue, will try the rc kernel when I can. From anecdotal experience, the LTS takes longer on average to freeze the system. 

Also of note is the fact that sometimes the freeze is only < 1s long and the system manages to recover, if the freeze is any longer the system locks up indefinitely as usual. For the record, everything stops working except the audio, and all you can see is the last frame before the freeze.

**Comment by 1Naim** [comment]
> I have switched to the rc kernel, i will report back if the issue happens again

Please reopen this if you're still experiencing issues (although it should be reported to AMD instead). I'm closing this for now.
