### ISSUE TITLE
TT Has unplayable stutter with certain games but there is a merge fix underway.

### ISSUE THREAD

**Issue by LethalManBoob** [CachyOS/linux-cachyos#33]
https://github.com/hamadmarri/TT-CPU-Scheduler/blob/master/patches/6.0/tt-6.0.patch
Replaces the GRQ load balancer with the cfs, purports to fix the stutter.

**Comment by ptr1337** [comment]
We already have this scheduler in our 6.0 patches, and you can already use it with linux-cachyos-rc. I already run and tested it.

https://github.com/CachyOS/kernel-patches/blob/master/6.0/sched/0001-tt-cachy.patch

**Comment by ptr1337** [comment]
https://github.com/CachyOS/kernel-patches/blob/master/5.19/sched/0001-tt-cachy.patch

Here is a backport for 5.19, only works with the cachyos patches
