### ISSUE TITLE
0001-cachyos-base-all.patch fails on huge_memory.c

### ISSUE THREAD

**Issue by mikeserv-git** [CachyOS/linux-cachyos#330]
For Linux 6.11.8 and 6.11.9. I can't see how this could possibly flow, with all cachyos kernels using this same base patch in their PKGBUILDs

patching file mm/huge_memory.c
Hunk #10 FAILED at 3304.
Hunk #11 succeeded at 3337 with fuzz 2 (offset 13 lines).
Hunk #12 succeeded at 3357 (offset 17 lines).
Hunk #13 succeeded at 3395 (offset 17 lines).
Hunk #14 succeeded at 3435 (offset 17 lines).
Hunk #15 succeeded at 3451 (offset 17 lines).
Hunk #16 succeeded at 3463 (offset 17 lines).
1 out of 16 hunks FAILED -- saving rejects to file mm/huge_memory.c.rej

I fixed it for myself for Linux 6.11.9. It LOOKS like that code can be inserted in this new function here, as follows?

```
bool __folio_unqueue_deferred_split(struct folio *folio)
{
	struct deferred_split *ds_queue;
	unsigned long flags;
	bool unqueued = false;

	WARN_ON_ONCE(folio_ref_count(folio));
	WARN_ON_ONCE(!mem_cgroup_disabled() && !folio_memcg(folio));

	ds_queue = get_deferred_split_queue(folio);
	spin_lock_irqsave(&ds_queue->split_queue_lock, flags);
	if (!list_empty(&folio->_deferred_list)) {
		ds_queue->split_queue_len--;
        	if (folio_test_partially_mapped(folio)) {
		        __folio_clear_partially_mapped(folio);
		}
		list_del_init(&folio->_deferred_list);
		unqueued = true;
	}
	spin_unlock_irqrestore(&ds_queue->split_queue_lock, flags);

	return unqueued;	/* useful for debug warnings */
}

/* partially_mapped=false won't clear PG_partially_mapped folio flag */
void deferred_split_folio(struct folio *folio, bool partially_mapped)
{
...
...
```

Note that I'm not a CachyOS user, I'm just borrowing your kernel patches for my own custom kernel builds on Arch and Gentoo. I really like that THP Shrinker and your tweaks, as well as the BORE scheduler enhancement. Great work!

**Comment by 1Naim** [comment]
Patches get updated each kernel revision in https://github.com/CachyOS/kernel-patches/. If it's failing for you, then you have an old patch that wasn't updated. I just applied the patch to a fresh 6.11.9 tree. It applied cleanly without any hunks.

**Comment by mikeserv-git** [comment]
I'm sorry, I was going by what was in the source array in the PKGBUILD and subsequent commands to apply them.

_patchsource="https://raw.githubusercontent.com/cachyos/kernel-patches/master/${_major}"
"${_patchsource}/all/0001-cachyos-base-all.patch"

Sorry for the noise then, if that's not what's actually happening.
