### ISSUE TITLE
Cant build kernel since last commit

### ISSUE THREAD

**Issue by WhitePeace36** [CachyOS/linux-cachyos#331]
The validation of sourcefiles 

linux-6.12.tar.xz ... FAILED

since the last commit.

when checking out with commit 503f4835a29d4ea7925a5fd82344a553915 it works.

**Comment by ptr1337** [comment]
> The validation of sourcefiles
> 
> linux-6.12.tar.xz ... FAILED
> 
> when checking out with commit [503f483](https://github.com/CachyOS/linux-cachyos/commit/503f4835a29d4ea7925a5fd82344a553915091e1) it works.

Mhm, that one should not fail, since the source did not change. I have only pushed changes to the config, and updated its checksums.

**Comment by ptr1337** [comment]
Thats weird, now when generating the checksum it does put the old again. Maybe my download was corrupted or so :( Fixed now.
