### ISSUE TITLE
[PKGBUILD] Clang: If the kernel is compiled with clang add clang, llvm, lld to the dependencies of the header package

### ISSUE THREAD

**Issue by ptr1337** [CachyOS/linux-cachyos#346]
Currently, user which are installing the cachyos kernel from the AUR, or chaotic-aur running into issues, because the package does not depend on the llvm toolchain.

Currently, we are only using it for makedepends, if we put full or thin lto.
Since the base kernel, does not need to depend on the llvm toolchain, make the headers depending on llvm toolchain, which is required then for compiling external modules.

**Comment by 1Naim** [comment]
```diff
diff --git a/linux-cachyos/PKGBUILD b/linux-cachyos/PKGBUILD
index cfe12603..6f0a6bad 100644
--- a/linux-cachyos/PKGBUILD
+++ b/linux-cachyos/PKGBUILD
@@ -642,6 +642,10 @@ _package-headers() {
     pkgdesc="Headers and scripts for building modules for the $pkgdesc kernel"
     depends=('pahole' "${pkgbase}")
 
+    if _is_clang_kernel; then
+        depends+=(clang llvm lld)
+    fi
+
     cd "${_srcname}"
     local builddir="$pkgdir/usr/lib/modules/$(<version)/build"
```

Something like this should be sufficient, although as seen in #304 previously this breaks .SRCINFO generation when `_is_clang_kernel` is false (this is trivial, the actual package has the correct dependency metadata).

**Comment by 1Naim** [comment]
The above isn't a problem for `linux-cachyos` because we already use clang for that for the default. Issues arise for the other kernels which still default to GCC. e.g.:

```diff
diff --git a/linux-cachyos-bore/.SRCINFO b/linux-cachyos-bore/.SRCINFO
index 37c19ca8..ac5294d0 100644
--- a/linux-cachyos-bore/.SRCINFO
+++ b/linux-cachyos-bore/.SRCINFO
@@ -48,3 +48,6 @@ pkgname = linux-cachyos-bore-headers
        pkgdesc = Headers and scripts for building modules for the Linux BORE + Cachy Sauce scheduler Kernel by CachyOS with other patches and improvements kernel
        depends = pahole
        depends = linux-cachyos-bore
+       depends = clang
+       depends = llvm
+       depends = lld
```

**Comment by ptr1337** [comment]
> The above isn't a problem for `linux-cachyos` because we already use clang for that for the default. Issues arise for the other kernels which still default to GCC. e.g.:
> 
> ```diff
> diff --git a/linux-cachyos-bore/.SRCINFO b/linux-cachyos-bore/.SRCINFO
> index 37c19ca8..ac5294d0 100644
> --- a/linux-cachyos-bore/.SRCINFO
> +++ b/linux-cachyos-bore/.SRCINFO
> @@ -48,3 +48,6 @@ pkgname = linux-cachyos-bore-headers
>         pkgdesc = Headers and scripts for building modules for the Linux BORE + Cachy Sauce scheduler Kernel by CachyOS with other patches and improvements kernel
>         depends = pahole
>         depends = linux-cachyos-bore
> +       depends = clang
> +       depends = llvm
> +       depends = lld
> ```

We only need it for the default kernel in general, since this is the used from other repository, like chaotic-aur

**Comment by 1Naim** [comment]
> We only need it for the default kernel in general, since this is the used from other repository, like chaotic-aur

Fair point, ideally this should get fixed in pacman tho but this functionality is so niche that it might just get shut down immediately. What do you think about adding a post-install message for the non-default LTO kernels tho?

```diff
--- a/linux-cachyos-bore/PKGBUILD
+++ b/linux-cachyos-bore/PKGBUILD
@@ -207,6 +207,7 @@ if _is_clang_kernel; then
         LD=ld.lld
         LLVM=1
         LLVM_IAS=1
+    install=clang-kernel.install
     )
 fi
```

Contents would be something along the lines of "This kernel was built with the clang compiler. If you are dependent on any out-of-tree kernel modules, it is imperative that you install the clang-llvm family of packages for proper functionality."
