### ISSUE TITLE
recent kernel config changes break BPF app

### ISSUE THREAD

**Issue by glitsj16** [CachyOS/linux-cachyos#4]
Hi, ever since `MuQSS` [died](https://ck-hack.blogspot.com/2021/08/514-and-future-of-muqss-and-ck-once.html) I've been looking for a replacement CPU scheduler. After testing many, I've settled on [TT](https://github.com/hamadmarri/TT-CPU-Scheduler), which works great for me, thanks for that!. So my Arch Linux box installs the `linux-cachyos-tt` package from [here](https://mirror.cachyos.org/) for a while and all's fine once again. Or not :-)...

Version `5.15.11-2` though broke an app I've been testing, called [picosnitch](https://github.com/elesiuta/picosnitch). After [communicating](https://github.com/elesiuta/picosnitch/issues/7) with the dev it turned out that the cachyos kernels config changed recently and `CONFIG_BPF_EVENTS=y` got [removed](https://github.com/CachyOS/linux-cachyos/commit/fbe7ae3f39c58e35e5b5f16c2bbc635cf37b176d#diff-d749dcdcedbd315d78a4be70e4c6944421f24cf7d52eecd3e451ab890bd02673L10607).

I admit not being very familiar with the complex set of configuration options of the Linux kernel, but I wonder what's the rationale behind these latest changes, especially to the BPF stuff. There are other changes in the 5.15.11 cachyos kernels config related to BPF, and a quick comparison to the Arch Linux configs shows no such changes, not in the [linux](https://github.com/archlinux/svntogit-packages/blob/packages/linux/trunk/config) nor in the [linux-hardened](https://github.com/archlinux/svntogit-packages/blob/packages/linux-hardened/trunk/config) package.

Is there any room for reversing these BPF-related changes or do I have to drop using/co-working on picosnitch alltogether on the cachyos kernels?

**Comment by ptr1337** [comment]
Hey @glitsj1, 

First thanks for your detailed issue description!
I already reverted the config option for the upcoming kernel version.

I did the changes before through another custom kernel and myself i noticed not any issues, so thanks for reporting. 

Im testing right now the current kernel config (performance/stability) and will push it with 5.15.12 or if its not getting released today or tomorrow the new pkgver. 

Regards!

**Comment by SM9CC** [comment]
Welcome, glad you found CachyOS and hope that you are enjoying it so far 😉


May I suggest you try the bore scheduler? It runs really nice and possibly even better than TT depending on your usage. 

Regards

**Comment by glitsj16** [comment]
> I already reverted the config option for the upcoming kernel version.

That's very kind and much appreciated! I'll be testing any new release ASAP. Perhaps it's too late now, but some other config options might be worthwhile to look into for the next round. This is the BPF section of the stock Arch Linux kernel config:

```

#
# BPF subsystem
#
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_JIT_DEFAULT_ON=y
# CONFIG_BPF_UNPRIV_DEFAULT_OFF is not set
CONFIG_USERMODE_DRIVER=y
CONFIG_BPF_PRELOAD=y
CONFIG_BPF_PRELOAD_UMD=m
CONFIG_BPF_LSM=y
# end of BPF subsystem
```
The above ensures the bpf_preload module is available and loaded by default, which seems very nice to have now there's more and more BPF programming being done (especially for security-related enhancements).

Thanks for looking into this and enjoy a safe and pleasant end-of-year!

**Comment by glitsj16** [comment]
> May I suggest you try the bore scheduler? It runs really nice and possibly even better than TT depending on your usage.

@SM9CC Thanks for the tip, I'll definately check that out.

**Comment by ptr1337** [comment]
@glitsj16 

I'll do right now for all kernels the config + a refreshed PKGBUILD done, when i got the PKGBUILD from TT done, i will upload you a  compiled kernel.

**Comment by ptr1337** [comment]
@glitsj16 

There you go. Bore + TT. 

https://cloud.ptr1337.dev/s/239QzWfjNKe5HMm

Report please regarding performance and the other stuff :)

**Comment by glitsj16** [comment]
@ptr1337 Downloading those kernels as we type. Thanks for the servic! I'll do some testing and report back.

**Comment by ptr1337** [comment]
> @ptr1337 Downloading those kernels as we type. Thanks for the service! I'll do some testing and report back.

I hope they work. i faced into issues. did then a clang compile with tt and this one booted. Ill sent you the link if its working.

**Comment by ptr1337** [comment]
@glitsj16 

Here is the fixed TT version. 
https://cloud.ptr1337.dev/s/xTfELNWjiGf6gWS

But only compiled with generic since a user in the discord got only a generic cpu and wanted to test it. 

Tell me if everything is running, then i can do the other kernels.

**Comment by glitsj16** [comment]
@ptr1337 Thanks for the fixed TT version. I can confirm it's running fine here and the BPF issue with picosnitch is gone. I'll keep testing the TT and BORE CPU schedulers and will report back on that in a few days.

**Comment by ptr1337** [comment]
Yeah, tomorrow will be the release of the next kernel i think. 
I just let it oopen. I tested 5 kernels everything fine!

**Comment by ptr1337** [comment]
Fixed with the latest commit. Thanks for your report! 
The Kernels are compiling on the server right now! 

Regards
