### ISSUE TITLE
0001-Add-latency-priority-for-CFS-class.patch ... FAILED

### ISSUE THREAD

**Issue by explowz** [CachyOS/linux-cachyos#40]
The SHA512SUM for that file is not correct.

**Comment by ptr1337** [comment]
Happened through a revert of the lrng flags previously.
Fixed with https://github.com/CachyOS/linux-cachyos/commit/ef0c7072982adcc1ad1cf8bf28781105e98f0ddd

**Comment by compicat** [comment]
still happening with cachyos-bore compile. --skipinteg flag is the workaround for now.

**Comment by ptr1337** [comment]
> @ptr1337
> 
> still happening during cachyos-bore compile (sha256). --skipinteg flag is the workaround for now. Thanks in advance.

Oh. Do you mean the AUR?

**Comment by sirlucjan** [comment]
Please check now.

**Comment by compicat** [comment]
> > @ptr1337
> > still happening during cachyos-bore compile (sha256). --skipinteg flag is the workaround for now. Thanks in advance.
> 
> Oh. Do you mean the AUR?

nope, i m cloning the repo and compiling from there. It seems it is working now. Thank for the fix and prompt action.
