### ISSUE TITLE
Integrity checks (sha256) differ in size from the source array.

### ISSUE THREAD

**Issue by explowz** [CachyOS/linux-cachyos#46]
The kernel cannot compile due to this.

**Comment by ptr1337** [comment]
Which kernel exactly?

But should be fixed with:
https://github.com/CachyOS/linux-cachyos/commit/efd21ec1767c1ad6f522a67c0e50520c91621598

**Comment by ptr1337** [comment]
> It has not been fixed. Using cfs kernel. My PKGBUILD can be found [here](https://github.com/explowz/linux-cachyos/blob/master/linux-cachyos-cfs/PKGBUILD). I've done nothing but change the settings offered by default.

This is cause you disabled latency_nice. Since the patch is included at us as default, there are also the checksum in for that.
Simply run `updpkgsums` before compiling. Or run `makepkg --skipchecksums` when you start your compilation
