### ISSUE TITLE
"00001-clear-linux.patch" - Error patching 39 line intel.c

### ISSUE THREAD

**Issue by R1413** [CachyOS/linux-cachyos#5]
It patch intel.c two times, in the second time it do this

```
//0001-clear-linux.patch line 1292
@@ -38,6 +39,7 @@
#include <asm/msr.h>

//Error start here
 static const char ucode_path[] = "kernel/x86/microcode/GenuineIntel.bin";
+bool force_ucode_load = false;
 

 /* Current microcode patch used in early patching on the APs. */
 static struct microcode_intel *intel_ucode_patch;
```

You know a way to fix it without exclude clear-linux.patch of the build?
Maybe its because GenuineIntel.bin its a blob?
EDIT: delete the lines off error return "error in build()" after "AR      fs/built-in.a"

**Comment by ptr1337** [comment]
Hey, 

I gonna take a watch later later. So far i got no problems with the Clearlinux patch. But thanks for the issue. 
I'll test it later.

**Comment by Jeoshua** [comment]
You say that the file is being patched twice, and that's genuine. It's supposed to, it changes different lines each time. Is there some other issue occurring here?

**Comment by R1413** [comment]
> You say that the file is being patched twice, and that's genuine. It's supposed to, it changes different lines each time. Is there some other issue occurring here?

apparently the error occurs in the second patch so I wanted to remove that part of the code but I never worked with patches before so I was looking for a way to fix it

**Comment by R1413** [comment]
Fixed, my `arch/x86/kernel/cpu/microcode/intel.c` file have ```
static const char ucode_path[] = "/*(DEBLOBBED)*/"; 
****
```
but it need to have  `static const char ucode_path[] = "kernel/x86/microcode/GenuineIntel.bin";`
