### ISSUE TITLE
Missing checksum when enabling bore tuning.

### ISSUE THREAD

**Issue by subanz** [CachyOS/linux-cachyos#50]
Enabling _tune_bore=${_tune_bore-y} causes:

==> ERROR: Integrity checks (sha256) differ in size from the source array.

Adding the sha256 checksum of 0001-bore-tuning-sysctl.patch to sha256sums fixes the issue.

Not sure if the checksum just changed or if it needs to be added.

**Comment by sirlucjan** [comment]
If you have enabled the _tune_bore flag, you are downloading an additional patch. Therefore, the checksums are changed and this is an intended, purposeful and normal effect.

**Comment by subanz** [comment]
Oh I see, only the default patches are added to the checksums. I just noticed the cfs latency patch checksums are only in the bore package. I'll close this.
