### ISSUE TITLE
Where to find Debuginfo for CachyOS binaries?

### ISSUE THREAD

**Issue by Betaminos** [CachyOS/linux-cachyos#53]
Hello there,

I have been using CachyOS's binaries and have come across an issue that I would like to raise with the package developer, as I believe it to be caused by the original code.
However, to trace the issue back to its source, I need to provide a coredump with debug symbols.
The Arch binaries offer this via https://wiki.archlinux.org/title/Debuginfod
Could you please help me understand whether I can use these debug symbols for CachyOS binaries as well?
If not, could you please tell me where to find the CachyOS debug symbols?

Thank you.

**Comment by sirlucjan** [comment]
We provide debuginfo for v3 repositories. You need to add the following entry to pacman.conf:

```[cachyos-debug-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist```

**Comment by ptr1337** [comment]
Hey,

a debuginfod will follow soon! Right now you can add the debug repos and install the package you want to use! :)

**Comment by Betaminos** [comment]
> We provide debuginfo for v3 repositories. You need to add the following entry to pacman.conf:
> 
> ```
> [cachyos-debug-v3]
> Include = /etc/pacman.d/cachyos-v3-mirrorlist
> ```

Thank you.
However, I am struggling to use these.
Doing the normal `pacman -Syu` does not download debug symbols and doing a `coredumpctl gdb XYZ` does not download symbols either.
Could you please share how to make coredumpctl use the debug symbols from this?



> Hey,
> 
> a debuginfod will follow soon! Right now you can add the debug repos and install the package you want to use! :)

I am looking forward to it, as trying to trace and report a bug is very tedious right now, as it involves downgrading all packages to the official Arch binaries, so I can use their debuginfod.

**Comment by sirlucjan** [comment]
In CachyOS coredumps are disabled by default. You can do so by removing this entry:

https://github.com/CachyOS/CachyOS-Settings/blob/master/etc/sysctl.d/99-cachyos-settings.conf#L124

**Comment by Betaminos** [comment]
> In CachyOS coredumps are disabled by default. You can do so by removing this entry:
> 
> https://github.com/CachyOS/CachyOS-Settings/blob/master/etc/sysctl.d/99-cachyos-settings.conf#L124

I am not using this file, i.e. coredumps are being created on my system.
The lack of debug symbols makes them close to useless, though.

**Comment by ptr1337** [comment]
> > In CachyOS coredumps are disabled by default. You can do so by removing this entry:
> > https://github.com/CachyOS/CachyOS-Settings/blob/master/etc/sysctl.d/99-cachyos-settings.conf#L124
> 
> I am not using this file, i.e. coredumps are being created on my system. The lack of debug symbols makes them close to useless, though.

You need to install the debug package you want to use for.
You can install with pacman the package for which you want to get debug symbols following:
sudo pacman -S $pkgname-debug

**Comment by Betaminos** [comment]
> > > In CachyOS coredumps are disabled by default. You can do so by removing this entry:
> > > https://github.com/CachyOS/CachyOS-Settings/blob/master/etc/sysctl.d/99-cachyos-settings.conf#L124
> > 
> > 
> > I am not using this file, i.e. coredumps are being created on my system. The lack of debug symbols makes them close to useless, though.
> 
> You need to install the debug package you want to use for. You can install with pacman the package for which you want to get debug symbols following: sudo pacman -S $pkgname-debug

Oh, I see.
In that case I will need to wait for the debuginfod being available.
The last bug I have reported was running across several packages and it seems like an even more tedious approach to work my way through all of the packages to get their debug-counterparts.
I will stick with doing a full downgrade to stock Arch binaries (to use their debuginfod) for the time being.
Nonetheless, I would prefer to stick with the CachyOS binaries all the way and am looking forward to your debuginfod.

Thank you for helping me understand this situation and have a great day :)

**Comment by ptr1337** [comment]
Yes, correct.
As I said, the debuginfod server is planned so that it does automatically fetch then the required debug symbols for the package with it.
We are working on it and it is planned in the next time!

Regards!
