### ISSUE TITLE
invisible mouse pointer in x11

### ISSUE THREAD

**Issue by undeadbydawn** [CachyOS/linux-cachyos#54]
The mouse pointer is invisible under x11 with the new RDNA3 cards. Issue can [currently] be resolved by creating
`/etc/x11/xorg.conf.d/99-modsetting.conf`
containing
```
Section "Device"
          Identifier "modesetting"
          Driver "modesetting"
EndSection
```

This is not an issue under Wayland

**Comment by ptr1337** [comment]
Thanks. I moved it to the wiki:
https://wiki.cachyos.org/en/home/first-steps
