### ISSUE TITLE
Package Provides for linux-cachyos-*-zfs packages

### ISSUE THREAD

**Issue by medzine-us** [CachyOS/linux-cachyos#57]
Hello.

I'm really liking what you have done. 

I'm using ZFS and the modules you provide with your kernels are very convenient and helpful. 

Please add to all of your `linux-cachyos-*-zfs`, for "Provides", something similar to what's listed with `zfs-dkms`. Some packages (e.g. `zfs-auto-snapshots`) require `zfs` as a dependency and this induces updates to install `zfs-dkms` when it's not needed.

Also, perhaps the "Conflicts With" entry may also need to be updated.

```$> yay -Si linux-cachyos-bore-zfs
Repository      : cachyos-v3
Name            : linux-cachyos-bore-zfs
Version         : 6.1.5-1
Description     : zfs module for the Linux BORE scheduler Kernel by CachyOS with other patches and improvements kernel
Architecture    : x86_64_v3
URL             : https://github.com/CachyOS/linux-cachyos
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : pahole  linux-cachyos-bore=6.1.5-1
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 18.01 MiB
Installed Size  : 18.05 MiB
Packager        : CachyOS <admin@cachyos.org>
Build Date      : Thu 12 Jan 2023 19:59:56 IST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

```
$> yay -Si zfs-dkms
Repository      : cachyos-v3
Name            : zfs-dkms
Version         : 2.1.7-3
Description     : Kernel modules for the Zettabyte File System.
Architecture    : any
URL             : https://zfsonlinux.org/
Licenses        : CDDL
Groups          : None
Provides        : ZFS-MODULE=2.1.7  SPL-MODULE=2.1.7  spl-dkms  zfs
Depends On      : zfs-utils=2.1.7  dkms
Optional Deps   : None
Conflicts With  : spl-dkms
Replaces        : spl-dkms
Download Size   : 29.23 MiB
Installed Size  : 66.65 MiB
Packager        : CachyOS <admin@cachyos.org>
Build Date      : Fri 02 Dec 2022 16:27:42 IST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

Thanks in advance.

Sam

**Comment by ptr1337** [comment]
Hi!

Thanks for reporting it. I will look into.
I already thought earlier about this. I will look to integrate it with 6.1.7.
But if linux-cachyos-*-zfs provides the same as zfs-dkms, would it not conflict each other?

The current implementation, does allow that user also can use other kernels, which don't have a zfs module with. Then they need to use "zfs-dkms".

Generally you are right, but we need to look into that nothing will conflict.
Would be enough to add a "provides=(zfs)" ?
I need to test, if this would make a conflict, when other zfs modules installed from linux-cachyos. Im currently not on ZFS.

**Comment by ptr1337** [comment]
@medzine-us 

The only solution I see, would be adding to zfs-utils a provide=(zfs). Otherwise the kernel/modules each kernel would conflict each other. This i not the way to go.

**Comment by Pinghigh** [comment]
> Hi!
> 
> Thanks for reporting it. I will look into. I already thought earlier about this. I will look to integrate it with 6.1.7. But if linux-cachyos-*-zfs provides the same as zfs-dkms, would it not conflict each other?
> 
> The current implementation, does allow that user also can use other kernels, which don't have a zfs module with. Then they need to use "zfs-dkms".
> 
> Generally you are right, but we need to look into that nothing will conflict. Would be enough to add a "provides=(zfs)" ? I need to test, if this would make a conflict, when other zfs modules installed from linux-cachyos. Im currently not on ZFS.

ZFS-DKMS only tells something like "there is already a zfs module in the kernel and the dkms module didn't be installed" after compiling it.

Maybe you could add a new meta package to provide zfs package virtually, which can check zfs module of every kernel in the disk, probably like the kernel manager

**Comment by NextWork123** [comment]
Hello, I have created the PKGBUILD for zfs-meta. Can it be a good solution for resolving this issue and closing it?

```
pkgname=zfs-meta
pkgver=1.0
pkgrel=1
pkgdesc="A meta package for ZFS on Arch Linux"
arch=('any')
depends=('linux-cachyos-zfs' 'zfs-utils')
provides=('zfs')

package() {
echo "Finally, you have successfully installed ZFS on your system."
}
```

**Comment by ptr1337** [comment]
> Hello, I have created the PKGBUILD for zfs-meta. Can it be a good solution for resolving this issue and closing it?
> 
> ```
> pkgname=zfs-meta
> pkgver=1.0
> pkgrel=1
> pkgdesc="A meta package for ZFS on Arch Linux"
> arch=('any')
> depends=('linux-cachyos-zfs' 'zfs-utils')
> provides=('zfs')
> 
> package() {
> echo "Finally, you have successfully installed ZFS on your system."
> }
> ```

For me these seems ok, it should solve the issue.
If good, I will add this package to the repo and then also add it to the cachyos-installation, if zfs is selected

**Comment by Pinghigh** [comment]
> 你好，我已经创建了贡献软件包进入community软件对于容量-元。 它可以是一个很好的解决方案解决这一问题，并关闭它?
> 
> ```
> pkgname=zfs-meta
> pkgver=1.0
> pkgrel=1
> pkgdesc="A meta package for ZFS on CachyOS"
> arch=('any')
> depends=('linux-cachyos-zfs' 'zfs-utils')
> provides=('zfs')
> 
> package() {
> echo "Finally, you have successfully installed ZFS on your system."
> }
> ```

Hello.

What if there are other kernels?

Will it be better to check the zfs module in the kernels?

**Comment by sirlucjan** [comment]
@Pinghigh @NextWork123 

Let me present a different solution. More or less something like this is what we use with UKSMD. 

1. Add something like this in each PKGBUILD of the kernel in the appropriate place

```package-zfs(){
    pkgdesc="zfs module for the $pkgdesc kernel"
    depends=('pahole' linux-$pkgsuffix=$_kernver)
    provides=('ZFS-MODULE')

    cd ${srcdir}/"zfs"
    install -dm755 "$pkgdir/usr/lib/modules/${_kernver}-${pkgsuffix}"
    install -m644 module/*/*.ko "$pkgdir/usr/lib/modules/${_kernver}-${pkgsuffix}"
    find "$pkgdir" -name '*.ko' -exec zstd --rm -10 {} +
    #  sed -i -e "s/EXTRAMODULES='.*'/EXTRAMODULES='${pkgver}-${pkgbase}'/" "$startdir/zfs.install"
}```

2. Then the package proposed above would take this form

```pkgname=zfs-meta
pkgver=1.0
pkgrel=1
pkgdesc="A meta package for ZFS on Arch Linux"
arch=('any')
depends=('ZFS-MODULE' 'zfs-utils')
provides=('zfs')

package() {
echo "Finally, you have successfully installed ZFS on your system."
}```

This would then work on the basis of the uksmd/uksmd-git package and the entry "provides=UKSMD-BUILTIN" which we have been using for a very long time and it works. If you use ZFS maybe you could test this solution and confirm if it works?

**Comment by NextWork123** [comment]
LGTM, of course wait for someone to test that.

**Comment by ptr1337** [comment]
https://github.com/CachyOS/linux-cachyos/pull/60

Please check

**Comment by ptr1337** [comment]
@medzine-us @Pinghigh 

Please update to 6.1.9.
Then you can install the "zfs-meta" package, its in cachyos/zfs-meta.
Please report if it is now working well, if yes close the issue and this will be added to the installer further.

Thanks for reporting!

**Comment by ptr1337** [comment]
Well, I will close here. It should be solved and working.
