### ISSUE TITLE
lqx patch cannot be found, 404 returned

### ISSUE THREAD

**Issue by MrWissenschaft** [CachyOS/linux-cachyos#7]
Hello!

So lqx patch could not be found, turns out the patch is in the PKGBUILD, but in the kernel patched git it is still in 5.16/misc/unused 

might be worthwhile adding it to the 5.16 folder now it is needed in the PKGBUILD :)

Thanks!

**Comment by ptr1337** [comment]
Hey, 

yes i did delete it and forgot that it is needed in the old PKGBUILD. I parsed some default patches together. gonna up it again
