### ISSUE TITLE
Bluetooth Adapter mt7921

### ISSUE THREAD

**Issue by eaureliano** [CachyOS/linux-cachyos#84]
I have a notebook with MT7921 module, are wifi and bluetooth integrate.

`04:00.0 Network controller: MEDIATEK Corp. MT7921 802.11ax PCI Express Wireless Network Adapter`

Stock kernel are working.

On cachyos kernel don't recognize the bluetooth adapter only wifi, with error on dmesg.

Attached files are dmesg from stock and cachyos.

[dmesg.stock.log](https://github.com/CachyOS/linux-cachyos/files/10813734/dmesg.stock.log)
[dmesg.cachy.log](https://github.com/CachyOS/linux-cachyos/files/10813735/dmesg.cachy.log)

**Comment by ptr1337** [comment]
Hi,

Actually you are using a different kernel version. Maybe it got further removed from the newer kernels.
Please try following kernel from arch (https://archlinux.org/packages/testing/x86_64/linux/).

Generally we are using the same config as arch does and we also don't modify driver related things in the patches.

**Comment by eaureliano** [comment]
You are correct.
In newer version are broken too.

**Comment by ptr1337** [comment]
> You are correct. In newer version are broken too.

Alright. Then probably create a issue at https://bugs.archlinux.org

**Comment by ptr1337** [comment]
Does this got solved at upstream or is the issue still present?

**Comment by ptr1337** [comment]
Will be also fixed in 6.3. Ill close here.
