### ISSUE TITLE
Invalid signature when attempting update

### ISSUE THREAD

**Issue by T3RR5V0N** [CachyOS/linux-cachyos#87]
i receive this error message when attempting to run "sudo pacman update"
```
error: cachyos-v3: signature from "CachyOS <admin@cachyos.org>" is invalid
error: cachyos-community-v3: signature from "CachyOS <admin@cachyos.org>" is invalid
error: cachyos: signature from "CachyOS <admin@cachyos.org>" is invalid
```

**Comment by vnepogodin** [comment]
Hi @T3RR5V0N,

Run these commands to fix signatures:
```
sudo pacman-key --recv-keys F3B607488DB35A47 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key F3B607488DB35A47
```

**Comment by T3RR5V0N** [comment]
i'm still receiving the error message.

**Comment by NextWork123** [comment]
Hello, you can try to use that command`sudo pacman-key --lsign-key cachyos`

**Comment by T3RR5V0N** [comment]
that also did not work. if it helps you figure out the problem, i had discover uninstall itself on me or something like that. i reinstalled it with the command `sudo pacman -Sy plasma-discover`

**Comment by T3RR5V0N** [comment]
discovered a fix. it had something to do with /var/lib/pacman/db.lck and the discover app
run command `sudo rm -rf /var/lib/pacman/db/lck`
then `sudo pacman -Sy`
