### ISSUE TITLE
copr *.srpm for LTO version of 6.2.1 build

### ISSUE THREAD

**Issue by HippieMitch** [CachyOS/linux-cachyos#88]

**Comment by HippieMitch** [comment]
Sorry, I just now saw the copr means of messaging people.  I'll post this over there.

**Comment by sirlucjan** [comment]
@HippieMitch 

https://github.com/sirlucjan/copr-linux-cachyos

Here you have spec files.

**Comment by HippieMitch** [comment]
Thanks comrade.
