### ISSUE TITLE
all of the cachyos kernels won't boot

### ISSUE THREAD

**Issue by sandikata** [CachyOS/linux-cachyos#9]
Hello, i am trying all of your available kernels from cachyos repo, but no one of them works, just black screen and freeze after booting on.

Tested on different configurations.

1. HP ProBook 450 G8
2. GA990FXAUD3 Rev4.0 + AMD FX8320

Any suggestions about ?

Thanks in advance.
Regards

**Comment by ptr1337** [comment]
Hey, 

Thanks first for your issue. Do you face any errors with dkms at installing the kernel ? If you try to use the *-lto kernels, you need to be sure that clang, lld, llvm is installed, since it will fail if you dont have them installed. 

Are you using the _v3 repo? 

Regards

**Comment by sandikata** [comment]
Hello,

No errors with dkms (or just not visible), i am not tryingo lto, just default. 
I don't use v3 repo.

Cannot provide any logs as screen is blank and system seems to be freozen (kernel panic or so), and rebooting after couple seconds.

**Comment by aarrayy** [comment]
Hey ptr, it happens to me too, similar system as sandikata has, AMD FX 6300
maybe something is wrong with this cpu family?

**Comment by aarrayy** [comment]
slightly difference is basically it freezes completely at Loading initial ramdisk, no logs nothing

**Comment by sandikata** [comment]
> Hey ptr, it happens to me too, similar system as sandikata has, AMD FX 6300 maybe something is wrong with this cpu family?

Not just FX, same on Core I5 1135G7 no matter cachy or cachy_v3

**Comment by sandikata** [comment]
It seems to be a kernel panic, it happens almost in first second after boot, display is completely switched off, and in 5 seconds computer reboot (maybe because of kernel panic timeout)

**Comment by ptr1337** [comment]
Hey @sandikata  @aarrayy .

sorry for being late, was ill the last two days. I think its due the latest GCC update. The 5.16.10 Kernels should work. Would be nice for a feedback. 

But I will go and watch about any config or patch issue's tomorrow.

**Comment by sandikata** [comment]
Yesterday i've tried 5.16.10 same issue, or you have a new revision?

**Comment by sandikata** [comment]
Hello, anyway the feedback again.

https://i.imgur.com/CKygrW9.png

The result, immediately black screen (display turn off) 5 seconds letter reboot. No matter which of cachyos kernels, no matter if i build it manually or install from the repo.

**Comment by gel-crabs** [comment]
Ryzen 5 2400G, been having the same issue for the past few months. 5.16.10 doesn't fix it.

**Comment by gel-crabs** [comment]
Ryzen 5 2400G, been having the same issue for a while now. 5.16.10 doesn't fix it.

**Comment by SchrodingerZhu** [comment]
I am on intel xeon. Everything works just fine.

**Comment by SchrodingerZhu** [comment]
I used dracut EFI image as the loader

**Comment by sandikata** [comment]
> I am on intel xeon. Everything works just fine.

If it works somehow for you, doesn't mean it work at all for anyone.

**Comment by sandikata** [comment]
> Ryzen 5 2400G, been having the same issue for a while now. 5.16.10 doesn't fix it.

It is not about versions, there's something else and extremely wrong or broken. 
Any other kernel setups just works (speaking as experienced gentoo user since last 12 years i've build thousands of kernels with no such issues).

**Comment by SchrodingerZhu** [comment]
> > I am on intel xeon. Everything works just fine.
> 
> If it works somehow for you, doesn't mean it work at all for anyone.

Sure. I am just to sync info.

**Comment by ptr1337** [comment]
I did overworked the complete kernel + config. It should be fine now. 
https://github.com/CachyOS/linux-cachyos/commit/882b012a433a7d98c9572a4a310b18f63994fda6
The server is right now compiling the kernels. I hope after that everything will run fine! 

Kernels will be up within the next few hours. 

Regards

**Comment by gel-crabs** [comment]
Just compiled the 5.16.10-2 kernel, it works!

**Comment by sandikata** [comment]
I can confirm it works now.

**Comment by ptr1337** [comment]
Glad to hear! I close this issue! 

Sorry for the issues with the kernel version. 

Regards.

**Comment by isati** [comment]
This seems to be an issue again on the 5.18.0 kernel. Last working/booting kernel for me was 5.17.9-3, Ryzen 5500U, Just black screen so no output/logs.

**Comment by ptr1337** [comment]
> This seems to be an issue again on the 5.18.0 kernel. Last working/booting kernel for me was 5.17.9-3, Ryzen 5500U, Just black screen so no output/logs.

Is this issue also with every scheduler present ? Actually its known that cacule does not work in general with 5.18

**Comment by isati** [comment]
> > This seems to be an issue again on the 5.18.0 kernel. Last working/booting kernel for me was 5.17.9-3, Ryzen 5500U, Just black screen so no output/logs.
> 
> Is this issue also with every scheduler present ? Actually its known that cacule does not work in general with 5.18

I've now rebuilt with the new default BORE and it is booting again.

**Comment by ptr1337** [comment]
> > > This seems to be an issue again on the 5.18.0 kernel. Last working/booting kernel for me was 5.17.9-3, Ryzen 5500U, Just black screen so no output/logs.
> > 
> > 
> > Is this issue also with every scheduler present ? Actually its known that cacule does not work in general with 5.18
> 
> I've now rebuilt with the new default BORE and it is booting again.

Great, glad to hear. I did synced to config with the one from arch. 
Will push 5.18.1 in the upcoming hour. 

I will close it again for now. Just reopen/write if something equal happens again. Thanks for the report.

**Comment by sandikata** [comment]
I cannot confirm it as working, all 5.18 just won't boot with R5 3600x

**Comment by SirToffski** [comment]
I've built `linux-cachyos` with `bore` over the weekend and it booted normally. However `linux-cachyos-cacule` failed to boot as of yesterday. Was getting stuck on `Loading initial ramdisk`.

[PKGBUILD used for linux-cachyos](https://gist.githubusercontent.com/SirToffski/82f95bdbdbb3babe5d2c149070aaeb18/raw/fe5629b63f70c9f80cbab466e50591edd7b9bec6/PKGBUILD-bore)
[PKGBUILD used for inux-cachyos-cacule](https://gist.githubusercontent.com/SirToffski/49f49f232d8d792f7c4012ca8f7868f7/raw/1b5945f12edee9a1e3ba4b6710b9e83907dade7f/PKGBUILD-calcule)

Can test rebuilding `linux-cachyos-cacule` and trying to boot anytime.

**Comment by ptr1337** [comment]
Yes cacule got broken with 5.18. I’ll take a watch what’s up there. Seems a bit weird, but many people confirm that, me included.

**Comment by dlm21** [comment]
Another updoot to the "borked for me" posts here. AMD 5900X, Nvidia 3080, x570 mb, using linux-cachyos-cacule package from Arch's AUR. Has been broken for a few weeks now at least, currently at 5.18.1-1

**Comment by ptr1337** [comment]
Yes cacule is broken since 5.18, as written above. 

> Another updoot to the "borked for me" posts here. AMD 5900X, Nvidia 3080, x570 mb, using linux-cachyos-cacule package from Arch's AUR. Has been broken for a few weeks now at least, currently at 5.18.1-1

**Comment by ptr1337** [comment]
> As of right now, the package doesnt even go past validity checks on aur via paru

I did just updated the packages with the checksums, will push the packages in some minutes into the aur. Use the github tree what be for the next hour better.

**Comment by ptr1337** [comment]
> Another updoot to the "borked for me" posts here. AMD 5900X, Nvidia 3080, x570 mb, using linux-cachyos-cacule package from Arch's AUR. Has been broken for a few weeks now at least, currently at 5.18.1-1

cacULE 5.18 is fixed again. Have fun!

**Comment by ptr1337** [comment]
I will close it again for now, feel free to open/write in again.

Regards.
