### ISSUE TITLE
Kernel panic on shutdown 6.2.3 linux-cachyos kernel

### ISSUE THREAD

**Issue by orianflaust** [CachyOS/linux-cachyos#91]
[FS#77811 - linux package v6.2.3.arch1-1 causes a kernel panic at shutdown ](https://bugs.archlinux.org/task/77811?project=1&order=dateopened&sort=desc) 

I get the exact same behavior on my machine with latest kernel.

Would be nice if you could revert commit like shown in the bugreport in bugs.archlinux.org.

Thanks!

**Comment by ptr1337** [comment]
Yes. I’m aware about that. 6.2.4 got released and I update it in the next hrs

**Comment by ptr1337** [comment]
Hi, should be fixed with this commit https://github.com/CachyOS/linux-cachyos/commit/7ddb9ee125cee6bd207910b5a45aaf24d3af2472
6.2.4 got released with the two reverts
