### ISSUE TITLE
PDS and BMQ Schedulers not working?

### ISSUE THREAD

**Issue by wolfyrion** [CachyOS/linux-cachyos#98]
Hi ,
I dont know whats going on with Kernel 6.2.x but something is not working as intended. 

I did a test with the latest kernel version 6.2.11 of BMQ and PDS Schedulers with an NVIDIA 4090
Cachyos ,  TKG and LQX
Did a benchmark with Shadow of Mordor --
MAX FPS --> 550

I did the same test with LTS Kernel 5.15.x but this time with TKG  since only that was available both PDS and BMQ
MAX FPS --> 1085 

As far as I remember with 6.1 I didnt have any issues , so what changed in 6.2?

**Comment by wolfyrion** [comment]
Hi and Thanks for replying ...
I have recently replaced my PC and  I have an  Intel i9-13900KS 

I have tried to boot with BORE Scheduler but no luck.
I think it had problems with detecting my 4 monitors or something was wrong with refresh rates at 144hz and so on.

Also another issue I had it was that I couldnt install Any kernel x86-64-v3 it said that my CPU was not supported.
but if I do 

 /lib/ld-linux-x86-64.so.2 --help | grep supported
  x86-64-v3 (supported, searched)
  x86-64-v2 (supported, searched)

It says that is supported 

My Laptop has an older cpu 11th Gen Intel Core i7-1185G7 but it supports v4

/lib/ld-linux-x86-64.so.2 --help | grep supported
x86-64-v4 (supported, searched)
x86-64-v3 (supported, searched)
 x86-64-v2 (supported, searched)

but still cant install any v3 or v4 getting errors.

Anyway thanks for replying I will test again CachyOS when kernel 6.3 is released

**Comment by ptr1337** [comment]
@wolfyrion 

Please follow the README. You require our pacman to install the packages.
We include a patch which autodetects your cpu arch for an extra security layer.

Please do the following:
```
sudo pacman -U 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-keyring-2-1-any.pkg.tar.zst' 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-mirrorlist-17-1-any.pkg.tar.zst' 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v3-mirrorlist-17-1-any.pkg.tar.zst' 'https://mirror.cachyos.org/repo/x86_64/cachyos/cachyos-v4-mirrorlist-5-1-any.pkg.tar.zst' 'https://mirror.cachyos.org/repo/x86_64/cachyos/pacman-6.0.2-10-x86_64.pkg.tar.zst'
```
After that add the repo(s) or install the kernel manually.

Actually the Scheduler does not affect anything related to your Monitor Configuration.
I think this is a nvidia upstream issue at all.

**Comment by ventureoo** [comment]
> As far as I remember with 6.1 I didnt have any issues , so what changed in 6.2?

In 6.2 new squash optimizations have been added that have not been properly tested by us. Maybe it's just another PDS regression.
